### ISSUE TITLE
VS does not provide an Add resource file to a F# project

### ISSUE THREAD

**Issue by KevinRansom** [Microsoft/visualfsharp#1008]
I think it should.

**Comment by dsyme** [comment]
I noticed this today too.  I actually suspect there are lots of item templates in C# that could be added for F#

**Comment by KevinRansom** [comment]
Well .. I have a template, and it works fine.  Except the designer string code generation doesn't work of course, which I suspect is why one wasn't originally shipped.

**Comment by dsyme** [comment]
> which I suspect is why one wasn't originally shipped.

IIRC the reason was that the people who did Visual F# Tools 2.0 only thought of the item templates at late in the alpha, they chose the absolutely minimal set. Then they just didn't update them after that until TPs in F# 3.0, and added a few more (now mostly gone unfortunately now FSharp.Data.TypeProviders has moved out of this repo).  I think there was also a feeling that resx was only for WinForms - but resx for strings is actually very useful in all scenarios.

**Comment by baronfel** [comment]
Not sure if this is related to this issue but on my installation of VS 2015 I don't have any F# templates in the installation directory, which I am referencing against [this MSDN article](https://msdn.microsoft.com/en-us/library/y3kkate1.aspx). Here's a snapshot: 
![image](https://cloud.githubusercontent.com/assets/573979/14582962/8392c802-03d9-11e6-8fcf-b2205b5e1501.png)

By comparison, the VS 2013 templates folder does have an F# directory: 
![image](https://cloud.githubusercontent.com/assets/573979/14582969/ae063c9a-03d9-11e6-9aad-c1a12db25fdf.png)

I'm currently installing VS 2015 update 2 to see if that addresses the issue.  I was chatting with user @bigjonroberts on the functionalprogramming slack channel and he reported losing f# project/item templates on an existing project after the update, and seemingly changing the ToolsVersion down to 12.0 addressed that in part for him.

**Comment by KevinRansom** [comment]
Fixed
