### ISSUE TITLE
printf units of measure does not work for %M specifier

### ISSUE THREAD

**Issue by rexcfnghk** [Microsoft/visualfsharp#1034]
F# 4.0 has an improvement to [`printf` that supports units of measure](https://github.com/fsharp/FSharpLangDesign/blob/master/FSharp-4.0/PrintfUnitsOfMeasureDesignAndSpec.md). However it does not work for the `%M` specifier (for `System.Decimal`):

```fsharp
[<Measure>] type usd

printfn "%M" 1.m<usd>
```
Gives
> error FS0001: This expression was expected to have type
>     decimal    
> but here has type
>     decimal&lt;usd&gt;

Changing the `1.` literal to `float` and the format specifier to `%f` solves the issue:
```fsharp
[<Measure>] type usd

printfn "%f" 1.<usd>
```
Outputted:
> [&lt;Measure&gt;]
> type usd
> val a : string = "1.000000"

**Comment by rexcfnghk** [comment]
I can't seem to find where does the compiler checks for the format specifiers for unit erasures. The only commit I found related to this is [here](https://github.com/Microsoft/visualfsharp/commit/aa7e945db107d0baf8af8d39c2d82185213c2796#diff-b761c4622f57ade359032b50d58b4d96). If someone can point me to the right direction I can help with a PR.

**Comment by dsyme** [comment]
The problem is that ``%M`` doesn't introduce a "format choice type" (the type used internally for ``%d`` and ``%f``), it just places a hard ``decimal`` constraint

c.f.

https://github.com/Microsoft/visualfsharp/blob/master/src/fsharp/CheckFormatStrings.fs#L240

https://github.com/Microsoft/visualfsharp/blob/master/src/fsharp/CheckFormatStrings.fs#L217

Only printf choice constraints allow erasure.  Adapting the %M code to use a choice constraint that contains the single decimal choice should be the solution and should be safe (not a breaking change) - at least I can't immediately think why that wouldn't work.
