### ISSUE TITLE
New Visual Studio "15" installer doesn't install F#

### ISSUE THREAD

**Issue by forki** [Microsoft/visualfsharp#1039]
https://www.visualstudio.com/en-us/downloads/visual-studio-next-downloads-vs.aspx shows two installers for Visual Studio "15". While the classical "full installer" allows to install F# into VS the new "light installer" does not.

After using the new installer VS doesn't even allow "on demand" installation of F# when you open a F# project.

**Comment by NumberByColors** [comment]
The lightweight installer is an early experiment, at this point. You'll be able to install Visual F# from the final product when the new installer work is finished.

**Comment by forki** [comment]
Please keep it open until it's resolved. We had some trouble with the
installers in the past.

**Comment by hmemcpy** [comment]
The new "lightweight" installer pulls components from the internet during installation. List of components is updated via a feed. So in theory, it will appear "whenever its ready", or whenever Microsoft deems it being ready.

**Comment by forki** [comment]
But what about "on demand" install? That's "broken" now. Or will it work
when they add F# to the available languages?

**Comment by GerjanOnline** [comment]
Since they changed the installer pretty heavily my hope is MS (@NumberByColors) will do the following:

1.Create a "bundle" for F#

<img src="https://cloud.githubusercontent.com/assets/1153419/14311083/cbf6a7b8-fbe5-11e5-859b-227a6cc63292.png" width="800">
<sup>So we can pick F# here</sup>

Should this bundle include `VisualFSharpPowerTools`?

2.Create a "popup notification" when you are in a F# project (so `fs`, `fsx` and `fsproj`?) for on demand installs

![image](https://cloud.githubusercontent.com/assets/1153419/14311078/c56b9480-fbe5-11e5-9cee-84d5a812ec8f.png)
<sup>Example of what happens when you edit PS</sup>
I'm not sure how this feature exactly works, is this "knowledge" baked into VS? Can extensions opt in to this? Can you install a bundle from here?

**Comment by hmemcpy** [comment]
Just to make sure: there are two installers: 
the lightweight (which is in the preview stage) - currently does not have an F# bundle
the "classic" - iso-based installation - F# needs to be selected in "Customize" - not preselected by default.

So yeah, F# definitely needs to be made a first class citizen, but it will be supported.

**Comment by hmemcpy** [comment]
@GerjanOnline regarding the popup notification: I've seen it, not sure which API provides it though.... need to check, I'll ask in [extendvs](https://gitter.im/Microsoft/extendvs)

**Comment by GerjanOnline** [comment]
@hmemcpy Thank you, I'm curious how that works

**Comment by hmemcpy** [comment]
Hmm, looks like this UI can be created with the [IVsInfoBarUIEvents](https://msdn.microsoft.com/en-us/library/microsoft.visualstudio.shell.interop.ivsinfobaruievents.aspx) service (new in VS2015 and above). Now, what exactly is creating that specific message, I'm not sure. There's an [extension by Mads Kristensen](https://github.com/madskristensen/SolutionExtensions) that suggests extensions based on the file type, and it shows a similar infobar... Do you have it installed?

**Comment by smoothdeveloper** [comment]
Just to mention that today my boss, on a new machine tried to build our solution, our FAKE script went good till it hit a fsproj file.

I had to explain that F# wasn't installed by default and that he should run the setup again.

I'd had have preferred either:
* that it worked out of the box (our FAKE script invokes msbuild, msbuild could install the compiler)
* that it failed at first project which is a csproj (just to be on par with user experience and not make it appear that F# is any different than it's sibblings on the CLI)

**Comment by isaacabraham** [comment]
@smoothdeveloper there's another issue regarding this - I can't recall where - @forki can you remember?

There's another side-issue to this - I set up a colleague with VSCode and an F# script - he installed Visual F# Tools but actually was forced to install Visual Studio as well in order to get things working - some MSBuild stuff needed to be brought down as well. I'll try to get more details and raise a separate issue about this.

**Comment by smoothdeveloper** [comment]
@isaacabraham there is #1040 and I think there is one for VS2015 (sorry, my story is related to VS2015) but maybe it is closed now.

**Comment by smoothdeveloper** [comment]
What comes is that it would be great for the experience to be streamlined with msbuild as well as VS, haskell's **stack** actually pulls the correct compiler based on the project (the **stack** file) settings if needed before attempting compilation.

**Comment by dsyme** [comment]
Closing old discussion
