### ISSUE TITLE
Record equality doesn't check potential recursion and can cause infinite loop

### ISSUE THREAD

**Issue by Horusiath** [Microsoft/visualfsharp#1085]
When provided a record definition with possible recursive field definition, an instance of that record may cause `StackOverflowException` during the equality check.

#### Repro steps

```fsharp
type TypeDef = {
    Name: string
    mutable Fields: FieldDef list
}
and FieldDef = {
    Name: string
    Type: TypeDef
}

let Int = { Name = "Int"; Fields = [] }
let Complex = { Name = "Complex"; Fields = [{ Name = "X"; Type = Int}] }
Complex.Fields <- { Name = "Deep"; Type = Complex } :: Complex.Fields

// This line will cause StackOverflowException
Complex = Complex
```

#### Expected behavior

Equality check should return true.

#### Actual behavior

On checking equality with itself, instance causes `StackOverflowException`.

#### Known workarounds

I'm not aware of current implementation, but I guess that simple check `Object.ReferenceEquals(x, y)` at the beginning could solve the problem in the case of `x = x`. Further problems may occur however, when we'll try to make a structural equality on two different instances, that are not reference equal, but still are structurally equal.

#### Related information 

* Operating system: Windows 8.1
* .NET Framework 4.5, F# 4.0 (Fsharp.Core, 4.4.0.0) 
* Editing Tools: Visual Studio 2015, Visual Studio Code 1.0 + Ionide

**Comment by forki** [comment]
As a side note: this one is weird in particular since it's exactly the same instance.

**Comment by KevinRansom** [comment]
No it is still there: this is from fsi with the latest build of master:
````
d:\microsoft\visualfsharp\release\net40\bin>fsi

Microsoft (R) F# Interactive version (private)
Copyright (c) Microsoft Corporation. All Rights Reserved.

For help type #help;;

> type TypeDef = {
-     Name: string
-     mutable Fields: FieldDef list
- }
- and FieldDef = {
-     Name: string
-     Type: TypeDef
- }
-
- let Int = { Name = "Int"; Fields = [] }
- let Complex = { Name = "Complex"; Fields = [{ Name = "X"; Type = Int}] }
- Complex.Fields <- { Name = "Deep"; Type = Complex } :: Complex.Fields
-
- // This line will cause StackOverflowException
- Complex = Complex;;

Process is terminated due to StackOverflowException.
````

**Comment by forki** [comment]
So why is it not breaking my test?

**Comment by KevinRansom** [comment]
@forki that will require further investigation.  My current theory is that some degree of optimization happens that eliminates the error.

**Comment by KevinRansom** [comment]
Okay, well passing a couple of reference types to assert is not going to invoke the issue:

To make your test fail you need to do something similar to this:
````
[<Test>]
let ``recursive structure with same record reference should not stack overflow`` () =
    Assert.IsTrue( (Complex = Complex) )
````
However, this will tear down the entire NUNIT process which is at least a good indication that something went wrong, but slightly draconian.  That happens because since .Net 2.0 StackOverflowException is not recoverable, and so not catchable.

So this test case should probably compile and execute into a separate process and check the exit code for a specific success value.

Does that make sense?

Kevin

**Comment by dsyme** [comment]
This is by design.  The F# language spec states the behaviour of code generated for equality and comparison implementations.  This code doesn't do pointer equality checks based on reference equality.  If you create cyclic or "infinite" data structures through mutation then you will see this kind of behaviour.  In these cases, you should mark your types using NoEquality, NoComparison, CustomEquality and/or CustomComparison.

**Comment by forki** [comment]
@dsyme after reading § 8.15.3 at page 191 I understand that this is indeed correct according to the spec. 

Would it makes sense to emit a compiler warning? Something like "you created a recursive mutable record and we can't ensure equality semantics. Consider to implement custom equality"?

**Comment by dsyme** [comment]
@forki  Perhaps, though it feels too corner-case, e.g. we can't tell if the mutation is mediated by some other mutable type, e.g.

```fsharp

type R = { Field: R[] }

let R = { Field = Array.zeroCreate 1 }

R.Field.[0] <- R

```

**Comment by forki** [comment]
yeah I guess that warning would match exactly one case ;-)
