### ISSUE TITLE
Multiple folders in fsproj with same named resource will not load

### ISSUE THREAD

**Issue by KevinRansom** [Microsoft/visualfsharp#117]
opened at [Codeplex](https://visualfsharp.codeplex.com/workitem/100) by [marklam](https://www.codeplex.com/site/users/view/marklam)

After adding the opencvsharp NuGet package, I had an fsproj with subfolders x86 and x64 - each with dlls of the same name inside. Once the project was closed, I couldn't open it again. 

I have reproduced this with a simpler project structure - two subfolders A and B both containing Foo.txt and Bar.txt. 

The error message is: 
The project 'ConsoleApplication2.fsproj' could not be opened because opening it would cause a folder to be rendered multiple times in the solution explorer. One such problematic item is 'A\Foo.txt'. To open this project in Visual Studio, first edit the project file and fix the problem. 

The fsproj contains:

```
    <ItemGroup>
        <Compile Include="Program.fs" />
        <Content Include="A\Bar.txt" />
        <Content Include="B\Foo.txt"/>
        <Content Include="B\Bar.txt" />
        <Content Include="A\Foo.txt"/>
        <None Include="App.config" />
    </ItemGroup>
```

> comments
> latkin wrote Jul 21, 2014 at 9:51 AM [x] 
> Hmm, upon quick investigation this looks like a silly error somewhere. The problem only occurs if you separate items from the same folder, per your example:
> 
> ```
> <Content Include="A\Bar.txt" />
> <Content Include="B\Foo.txt" /> 
> <Content Include="B\Bar.txt" />
> <Content Include="A\Foo.txt"/>
> ```
> 
> If you keep items from the same folder together, it works:
> 
> ```
> <Content Include="A\Foo.txt"/> 
> <Content Include="A\Bar.txt" />
> <Content Include="B\Foo.txt" />  
> <Content Include="B\Bar.txt" />
> ```

**Comment by enricosada** [comment]
assign that to me, is related to #246

the error is wrong because these are Content item.
If these had been Compile item ( like a .fs file ) the error for the sequence [A ; B ; B ; A] would be correct ( A rendered twice )

**Comment by latkin** [comment]
We actually can't assign bugs to people outside of the Microsoft org at the moment.  We'll need to check if there is some permissions stuff that can be enabled to allow this.

For now I'll mark it as assigned to myself, just so it's clear that it's claimed.

**Comment by enricosada** [comment]
i am working on it. Without assignment i lost track and forgot :sweat_smile:

**Comment by enricosada** [comment]
ok, so, the only way i found require to rearrange the items
If i try without change the order of items, lot of tests fail because the order of msbuild items is different than the order of tree items.

If the Compile items pass the already rendered check, the project can always be opened moving the other items

So:

- check Compile items for already rendered folder, if fails the project cannot be opened (that's ok)
- for every item reapply the already rendered folder algoritm, if fail for an item:
  - try find the previous item with same folder, if exists move directly after the node
  - if not exists move to bottom of list (will retry after)

I'll try to submit a fix with current codebase, but dont know if it's enough minimal to inclusion in v2015

**Comment by saul** [comment]
@enricosada did you fix this?

**Comment by enricosada** [comment]
@saul nope, i fixed with https://github.com/Microsoft/visualfsharp/pull/391 the bug https://github.com/Microsoft/visualfsharp/issues/246 about the unique name,

but not this one.

**Comment by saul** [comment]
In which case I suggest that this issue is closed - I don't really think this is a bug.

**Comment by saul** [comment]
@cartermp see my previous comment

**Comment by cartermp** [comment]
Yeah, this seems like a wontfix to me.
