### ISSUE TITLE
Improve error reporting: Detect module declarations that incorrectly end with `=`

### ISSUE THREAD

**Issue by DanTup** [Microsoft/visualfsharp#1214]
Depending on whether you have a namespace or not, a module declaration may or may not require an `=`. This caught me out today (it's been a long time since I did any F#); I created a new file and deleted the namespace and got this compile error:

> Files in libraries or multiple-file applications must begin with a namespace or module declaration

As I had some F# code open in my browser that had `module blah =` I copied it and continued to get the same message:

![fsharp2](https://cloud.githubusercontent.com/assets/1078012/15455196/9808a7d8-2045-11e6-9797-5440414e88df.png)

In hindsight, the example given in the message doesn't have an `=` so I should've figured it out, but it actually took much googling and finding [a comment on this answer](http://stackoverflow.com/a/2250463/25124) that made me realise the issue.

I think it might be worthwhile calling this out in the message (or ideally, detecting when there is a module declaration with an `=` that shouldn't be there and giving a specific message). It seems effort is going into improving messages in #1103.

**Comment by isaacabraham** [comment]
Good one. So I guess that this is caused by the ``=`` fooling the compiler into thinking that we want to use the filename as the module (and that ``NesTest`` is supposed to be a submodule)?

I'm not sure that the standard guidelines for messages that we've been following that @dsyme has mentioned will work in this case (i.e. "what is the error / why is it occurring / how can you resolve it") because of the nature of the error.

Assuming that it's possible to identify this situation, I'd suggest an error along the lines of: -

```Only modules nested in namespaces or submodules require =. If this is a top-level module, consider removing the = to resolve this error```.

**Comment by dsyme** [comment]
Suggest

    Files in libraries or multiple-file applications must begin with a namespace or module declaration.  When using a module declaration at the start of a file, no '=' is required. If this is a top-level module, consider removing the = to resolve this error.

**Comment by isaacabraham** [comment]
That's better, yes. Perhaps just just replace ``no '=' is required.`` to ``'=' is not required.``.

**Comment by forki** [comment]
TBH I don't understnd why we give an error in this case.


    module X =
      let x = 1

Put this in a files called ModuleWithoutNamespace.fs and it doesn't compile. Why?

**Comment by forki** [comment]
I mean it looks like a perfectly valid file. Copy the same code into fsi and it compiles. @dsyme why do we reject that.

**Comment by isaacabraham** [comment]
Isn't it because ``module X = `` indicates a submodule?

**Comment by forki** [comment]
but why is that an issue?

If I disable the error message for a moment then it compiles just fine:

![image](https://cloud.githubusercontent.com/assets/57396/15541450/d48f8afc-228c-11e6-8058-cb963eab08fc.png)

I mean why can't we improve the error message by not showing an error at all?

**Comment by forki** [comment]
the code is like this:

 if not (isLast && isExe) && not (Filename.checkSuffix filename ".fsx" )) then 
            errorR(Error(FSComp.SR.buildMultiFileRequiresNamespaceOrModule(),trimRangeToLine m))

So if we are in fsx file we just use the filename as "outer" module. Why can't we do that in fs files?

**Comment by isaacabraham** [comment]
That only works for the last file in an exe AFAIK.... I've always wondered if that could be added for all files in a project.

**Comment by isaacabraham** [comment]
I would suggest raising a separate issue for that though - it's not about error message but about changing compiler behaviour.

**Comment by forki** [comment]
WIP PR for error message https://github.com/Microsoft/visualfsharp/pull/1220

**Comment by dsyme** [comment]
Basically, 

* ``namespace N`` and ``module X`` are headers of an implementation file which says ``don't use the file name as the initial namespace/module, but use this name instead``

* ``module X = `` is a declaration of a nested module inside an enclosing module/namespace


We don't allow the second to be interpreted as the first because of the following

1 - In a script or last file, we allow programs like

```fsharp
let x = 1
```

In these cases, the code is places in a module taken from the file name, say ``FN``.

2 - That implies that the following is valid code in a script or last file:

```fsharp
module X =
  let x = 1

module Y =
  let x = 1
```

This compiles to two nested types ``FN.X`` and ``FN.Y``.

3 - So, in the last file, we also expect this to be valid code:

```
module X =
  let x = 1
```

Further the compilation representation should be predictable and consistent: deleting Y shouldn't change the compilation representation of ``X``


4 - Adding a file shouldn't change the compilation representation of existing modules.  Hence adding a file after this last file shouldn't change the compilation representation of ``X``.

**Comment by KevinRansom** [comment]
@dsyme 
that is the best description of that behavior I have ever encountered.  Perhaps it would be worthwhile adding a page to the visualfsharpdocs that express the module naming behavior this clearly.
