### ISSUE TITLE
Possible missing warning for mutable assignment

### ISSUE THREAD

**Issue by ales004** [Microsoft/visualfsharp#1337]
I think that there should be a warning if the equal sign assignment operator is used with mutable variables in some situations.

#### Repro steps

Run this script:

```fsharp
let mutable mutVar = 0
mutVar = 1
mutVar
match mutVar with
| 1 -> 
    "Expected"
| _ ->
    "Not expected"`
```

#### Expected behavior

I would expect a warning at line `mutVar = 1`. 

I say this because I think that it is common for people coming from other programming languages not to understand that this is a comparison that returns a boolean. In my opinion the warning should be shown only in the case of a mutable variable.

#### Actual behavior

No warning is shown.

#### Known workarounds

No known workaround.

#### Related information 

This is a minor Bug.

![vs_screen](https://cloud.githubusercontent.com/assets/1430794/16691550/55ad5174-452d-11e6-8ba8-aac1ce3cdd31.png)

**Comment by dsyme** [comment]
It's tricky to give a warning here because the code is entirely valid F# code....

**Comment by isaacabraham** [comment]
Isn't this related to the warning message in the Improve Error Reporting area? There was one about the ignore boolean result there.

**Comment by ReedCopsey** [comment]
This is pretty much handled by https://github.com/Microsoft/visualfsharp/issues/1109 via  https://github.com/Microsoft/visualfsharp/pull/1115 (not merged, though)

**Comment by dsyme** [comment]
I think in a script situation (the repro) that fix won't apply, because it is legitimate to have implicitly ignored top-level expressions in a script

**Comment by ReedCopsey** [comment]
@dsyme I do have a question about that - 

I understand that scripts can't report warnings about ignored top-level expressions in general, since it's valuable to be able to do:

```fsharp
mutVar
```

and have it report: `val it : int = 0`

However, is there any reason why top-level expressions that aren't the last executed expression are and should be ignored?  When you type:

```fsharp
mutVar = 1
mutVar
```

FSI still only prints `val it : int = 0` (silently swallowing the `mutVar = 1` line).  It seems like they both should print, or the first should be a warning...

**Comment by dsyme** [comment]
@ReedCopsey Both should be printed.  It's really a long-standing bug. We should just fix it

**Comment by ales004** [comment]
@ReedCopsey  @isaacabraham you are absolutely right. It seems that the warning I am speaking about has already been added. Can't wait for the new release!
