### ISSUE TITLE
Custom Query Operators Fails at Runtime?

### ISSUE THREAD

**Issue by Thorium** [Microsoft/visualfsharp#1485]
I can extend QueryBuilder with custom operators, e.g.:

``` fsharp
open System
open System.Linq
open Microsoft.FSharp.Linq

[<AutoOpen>]
module AsyncQueryBuilderOperations =

    type QueryBuilder with
        /// A query operator that returns the number of selected elements.
        [<CustomOperation("countAsync")>]
        member x.CountAsync(source:Linq.QuerySource<'T,'Q>) =
            source.Source.AsQueryable() |> getCountAsync

        /// A query operator that selects the first element from those selected so far.
        [<CustomOperation("headAsync")>]
        member x.HeadAsync(source:Linq.QuerySource<'T,'Q>) =
            source.Source.AsQueryable() |> getHeadAsync

        /// A query operator that selects the first element of those selected so far, or a default value if the sequence contains no elements.
        [<CustomOperation("headOrDefaultAsync")>]
        member x.HeadOrDefaultAsync(source:Linq.QuerySource<'T,'Q>) =
            async {
                let! res = source.Source.AsQueryable() |> getTryHeadAsync
                return match res with Some x -> x | None -> Unchecked.defaultof<'T>
            }

```

Then I can actually use them like:

``` fsharp
[<Test >]
let ``simple select with countAsync``() =
    let dc = sql.GetDataContext()
    let query = 
        query {
            for cust in dc.Main.Customers do
            select cust.CustomerId
            countAsync
        } |> Async.RunSynchronously
    Assert.AreEqual(91, query)   
```

But the problem is that F# LINQ Query translator doesn't like them on runtime:

```
System.NotSupportedException : This is not a valid query expression. The 
method 'Microsoft.FSharp.Control.FSharpAsync`1[System.Int32] QueryBuilder.CountAsync
[String,Object](Microsoft.FSharp.Linq.QueryBuilder, Microsoft.FSharp.Linq.QuerySource`2
[System.String,System.Object])' was used in a query but is not recognized by the F#-to-LINQ query 
translator. Check the specification of permitted queries and consider moving some of the operations 
out of the query expression

at Microsoft.FSharp.Linq.QueryModule.TransInner(CanEliminate canElim, Boolean check, FSharpExpr immutQuery)
at Microsoft.FSharp.Linq.QueryModule.TransInnerAndCommit(CanEliminate canElim, Boolean check, FSharpExpr x)
at Microsoft.FSharp.Linq.QueryModule.TransInnerWithFinalConsume(CanEliminate canElim, FSharpExpr immutSource)
at Microsoft.FSharp.Linq.QueryModule.EvalNonNestedInner(CanEliminate canElim, FSharpExpr queryProducingSequence)
at Microsoft.FSharp.Linq.QueryModule.EvalNonNestedOuter(CanEliminate canElim, FSharpExpr tm)
at Microsoft.FSharp.Linq.QueryModule.clo@1737-1.Microsoft-FSharp-Linq-ForwardDeclarations-IQueryMethods-Execute[a,b](FSharpExpr`1 )
at QueryTests.simple select with countAsync() in C:\git\SQLProvider\tests\SqlProvider.Tests\QueryTests.fs:line 66

```

The problem is this file:

https://github.com/Microsoft/visualfsharp/blob/master/src/fsharp/FSharp.Core/Query.fs

raise ... unsupportedQueryConstruct

**Comment by Thorium** [comment]
I initially reported this to fsharp/fsharp#603 but now I think it belongs to here.

**Comment by dsyme** [comment]
This is by design - not all constructs are supported in query translation

**Comment by Thorium** [comment]
Would that actually hurt someone to pass those unknown method-calls forward as-is? So that I would get a LINQ-method call to my custom method?

**Comment by dsyme** [comment]
@Thorium That can't happen when translating to SQL (which is going to run on the datavase). It does happen when processing in-memory

**Comment by NinoFloris** [comment]
Now that EF Core allows Client Evaluation as well (and I've never found "not all constructs are supported" a good argument) could we re-open this?

Everything is expected to be async or task based with asp.net core or "you're not using asp.net core right". As it's async all the way it can't deal very well with sync as it becomes sync over async hogging threads in the work items threadpool.

I'd really like to see a way to add async equivalents to the query CE, I understand I would need to do that as the compiler isn't going to take a reference on EF Core but I would like to think it's possible if anyone wants to.

**Comment by Thorium** [comment]
It's not only EF, but all the data storages are IO-bound and async. Like CosmosDB. Compare the F# and C# code examples in the [Microsoft documentation](https://docs.microsoft.com/en-us/sandbox/functions-recipes/cosmos-db?tabs=fsharp&WT.mc_id=recipes-twitter-cephilli#using-documentclient): I remember the days when async was F#'s thing, and not the other way round.

Also, the problem is that `query{ ... }` is using LINQ base classes (which are doing internal capsulation and wrapping) like [this](https://referencesource.microsoft.com/#System.Core/System/Linq/Enumerable.cs,8bf16962931637d3) where MoveNext() is calling source.GetEnumerator() which causes non-async evaluation of the collection even if you try to execute your `query { }` in async mode. There it should call source.GetAsyncEnumerator().

So +1 for adding asyncQuery to language core.

**Comment by Thorium** [comment]
> That can't happen when translating to SQL (which is going to run on the database).

I never understood why, as there are so many SQL functions and T-SQL language seems to have new keywords each time a new version of SQL server is released, for example [this](https://docs.microsoft.com/en-us/sql/t-sql/functions/binary-checksum-transact-sql?view=sql-server-2017), so `query { ... }` is more like F#-to-SQL language compiler, and why should it be limited to not support any kind of extensions. What makes Fable so good is that it can use new JavaScript libraries and adapt when the JavaScript ecosystem evolves.

**Comment by NinoFloris** [comment]
@Thorium Well that's not entirely what I meant as IQueryable is just an abstraction so EF is of course one of the many, the problem is that the `ToListAsync` etc methods are defined in EF so it wouldn't be possible to add those in the box, I'm just asking for the possibility of adding them yourself. 

With regards to `query{ ... } is using LINQ base classes` the way I read it it's not entirely correct. What Query.fs does (below the definition of the builder) is rewrite the builder's expression tree depending on the expected output type. If it's Enumerable it'll keep most of it as `System.Linq.Enumerable` methods, if it's IQueryable it'll rewrite the AST to use methods from `System.Linq.Queryable`. These will in fact not synchronously fetch data as long as you don't call First(OrDefault)/Single(OrDefault) and friends (or their `query{...}` equivalents).

What I currently resort to doing is to write a `query{...}` and pipe it's resulting IQueryable into one of my helper functions that'll call the EF ToListAsync/SingleAsync/etc. This is also how I do navigation includes. 

@dsyme What also doesn't seem to help to close these gaps yourself is that auto-quotation doesn't seem to work on functions, just tupled methods seem to work, is that right? This hinders efforts of making a functional first EF/Linq api wrapper as I can't even get a `where (source: IQueryable<'a>) (predicate: Expression<Func<'a,'b>>)` to work, compiler complains about not expecting a function at that spot. 

Some of these issues might change when C# 8 ships async generators and truly async enumerables.

So to conclude I'm absolutely not happy with the current state, it feels fragmented and there are too many (compiler prevented) feature holes to fix it without compiler changes, resulting in much less elegant code than C# would produce due to the noisy lambda syntax in F#.

**Comment by baronfel** [comment]
@NinoFloris I don't know that we can get around the provider-specific `ToListXXX` methods, because of how each provider has to substitute and translate the Expression. For Example I use (Marten.Fsharp)[://github.com/TheAngryByrd/Marten.FSharp/blob/master/src/Marten.FSharp/Marten.FSharp.fs#L216] for talking to Postgres because I have to use the ToListAsync from Marten, etc.

Now, it does seem that there is a gap that you've identified when translating Expr into System.Expressions. there are some helpers that are included in Marten.FSharp to translate lambdas af a few arities, but in an ideal world those would be translated on the fly.

**Comment by NinoFloris** [comment]
Sure not saying that at all, I'd just like the option of being able to ship extra EF methods for the query CE inside of a lib for instance. Currently not possible due to the compiler balking at any unknown method because it expects to be able to translate everything, however as we see with say `expectOne` any result producing methods can obviously not be translated.
