### ISSUE TITLE
Why is there an error in this code ?

### ISSUE THREAD

**Issue by polsol** [Microsoft/visualfsharp#1621]
Change error within code using Microsoft (R) F# Compiler version 14.0.23413.0

#### Repro steps

let bubbleSort (brr : 'a []) : 'a [] =
    // in-place swap
    let swap i j (arr : 'a []) =
        let tmp = arr.[i]
        arr.[i] <- arr.[j]
        arr.[j] <- tmp
        
    // help function
    let rec loop (ar : 'a []) : 'a [] =
        let mutable swapped = false
        for i = 0 to (ar.Length - 2) do
            if ar.[i] > ar.[i+1] then
                swap i (i+1) ar
                swapped <- true
            else
                swapped <- false
            if swapped then
                loop ar
            else
                ar
                
    // bubblesort
    loop brr

#### Expected behavior

No error

#### Actual behavior

Microsoft (R) F# Compiler version 14.0.23413.0
Copyright (c) Microsoft Corporation. All Rights Reserved.

bubblesort.fs(15,9): error FS0001: This expression was expected to have type
    'a []
but here has type
    unit

bubblesort.fs(25,1): warning FS0020: This expression should have type 'unit', but has type 'int []'. Use 'ignore' to discard the result of the expression, or 'let' to bind the result to a name.

#### Known workarounds

do not know

#### Related information 

None 

* Operating system
Windows 10 (updated 15-october-2016

* Branch

* .NET Runtime, CoreCLR or Mono Version
Microsoft (R) F# Compiler version 14.0.23413.0

* Editing Tools (e.g. Visual Studio Version)
* Links to F# RFCs or entries on http://fslang.uservoice.com
* Links to performance testing scripts
* Indications of severity

regards Pol

**Comment by abelbraaksma** [comment]
The layout of your code got crippled, you may want to go back to your question and click Edit to layout the code (use backticks, or indent, just like on StackOverflow, or click the code-button).

The error is no bug, you have a `for...do` which returns unit (it doesn't seem to return unit, but the `for .. do` returns unit always). Just change the code so that it returns a value (i.e., add a line with `ar`).

After you fix it, you will get a _warning_ that your `for..do` loop is actually returning a value (which it shouldn't, as it is ignored), so here the compiler is helping you to not expect a value and to explicitly ignore it, which you should do with `ignore`.

I don't know if your code is correct, but if I indent it properly (indentation was totally off in the question), then I get something like the following, which compiles fine.

    let bubbleSort (brr : 'a []) : 'a [] =
        // in-place swap
        let swap i j (arr : 'a []) =
            let tmp = arr.[i]
            arr.[i] <- arr.[j]
            arr.[j] <- tmp

        // help function
        let rec loop (ar : 'a []) : 'a [] =
            let mutable swapped = false
            for i = 0 to (ar.Length - 2) do
                if ar.[i] > ar.[i+1] then
                    swap i (i+1) ar
                    swapped <- true
                else
                    swapped <- false
                if swapped then
                    loop ar |> ignore
            ar  

        // bubblesort
        loop brr

This is not a bug of the compiler. It is probably better to ask such questions on [StackOverflow](http://stackoverflow.com) as they are about general concepts of F# programming, there's a very active F# community over there.

An excellent introduction to F# can be found at [FSharp for Fun and Profit](http://fsharpforfunandprofil.com), here [a post on your current issue with FS0020](http://fsharpforfunandprofit.com/troubleshooting-fsharp/).
