### ISSUE TITLE
Inconsistent behavior or two ways of adding breakpoints: with mouse and with F9

### ISSUE THREAD

**Issue by vasily-kirichenko** [Microsoft/visualfsharp#1902]
Trying to add a breakpoint with mouse (it's appear in a wrong place), then successfully add/remove/add it with `F9`:

![1](https://cloud.githubusercontent.com/assets/873919/20764619/0342cc18-b740-11e6-961a-a7deb479d6d2.gif)

**Comment by cartermp** [comment]
Unsure if this is a regression, but it's definitely not the right behavior.

**Comment by cartermp** [comment]
So the cause of this behavior seems to be the [`GetBreakpointLocation`](https://github.com/Microsoft/visualfsharp/blob/master/vsintegration/src/FSharp.Editor/BreakpointResolutionService.fs#L34) being called twice.

With this as the only code in a scrip file:

```fsharp
let asyncGetString (s: string) = async {
    return s
}

let foo() = 
    async {
        let! str1 = asyncGetString "hello"
        let! str2 = asyncGetString "world"
        let! str3 = asyncGetString "hey"

        match (str1, str2, str3) with
        | ("hello", "world", "hey") ->
            return str1 + str2 + str3
        | _ -> 
            return str1 + str2 + str3 + "otherstuff"
    } |> Async.StartAsTask
```

If I set a breakpoint at any line within the `async { }` block,  `GetBreakpointLocation` will be called for the first time and determine that the correct line (after offsetting by 1 to account for Roslyn lines being 0-based).  But then it gets called again and always reports `6` as the line (again, after offsetting by 1).  This second call determines where the breakpoint is set.

**Comment by cartermp** [comment]
Also of note - `ResolveBreakpointAsync` is called three times if you set a breakpoint with `f9`.  But it resolves the line number correctly each time.

**Comment by vasily-kirichenko** [comment]
wow. pure magic :(

**Comment by cartermp** [comment]
Okay spoke with @cyrusnajmabadi about this, and this is indeed a bug in our code!  Yay!

The result of [this line](https://github.com/Microsoft/visualfsharp/blob/master/vsintegration/src/FSharp.Editor/BreakpointResolutionService.fs#L45) when called the first time produces a `TextSpan` that **incorrectly** represents the entire `async { }` block instead of the line which was clicked.  This is then given back to the debugger, which uses that value the next time it invokes us.  There are many reasons why the debugger can invoke us multiple times (and they are good reasons), but so long as we report the correct `TextSpan` back, that's good behavior.

**Comment by cartermp** [comment]
Okay, root cause found:

Clicking to set a breakpoint at line 13 in [my repro](https://github.com/Microsoft/visualfsharp/issues/1902#issuecomment-264279640) produces a `pos` object with `{Line = 13, Column = 13}`.  This makes sense, because it's at line 13 in the editor and it's in the margin.

When walking the parse tree in [this call](https://github.com/Microsoft/visualfsharp/blob/master/src/fsharp/vs/ServiceUntypedParse.fs#L108) to validate the breakpoint location, two calls are made to [checkRange](https://github.com/Microsoft/visualfsharp/blob/master/src/fsharp/vs/ServiceUntypedParse.fs#L113).  The `{Line,Column}` range _of the parse tree_ has the same line number as the `pos` object generated from the breakpoint twice while walking.

This call fails both times, because the `pos` object created by setting the breakpoint fails to meet the condition that its `Column` value is greater than or equal to the `Start` column value of the range it is being checked against.

This consistently causes `f9` to fail as well.  This is a more general problem, and not limited to computation expressions starting on their own, tabbed-over line.  I can repeat this behavior in a number of places, such as hitting `f9` anywhere outside the columnar range on [this line](https://github.com/Microsoft/visualfsharp/blob/master/src/fsharp/vs/ServiceUntypedParse.fs#L189) and others like it.

Since the history of this code goes back to when VisualFSharp was first on GitHub, I have no context for the code which does this check.  @dsyme or @latkin, anything you can recollect?

**Comment by latkin** [comment]
@v2m might have background. Breakpoint ranges have always been flaky/bad in my recollection, so it might be best to just fix it however you see fit and not worry too much about the historical reasons it's flaky.

**Comment by vasily-kirichenko** [comment]
I think it's worth to take a look at how c# editor handle clicking on the margin and F9 out of any symbol, maybe it's as simple as looking ahead / back the line to peek the first one.

**Comment by vasily-kirichenko** [comment]
It's strange, I cannot reproduce it on hello world project on current master (the first breakpoint was set with `F9`, all the others - with mouse):

![image](https://cloud.githubusercontent.com/assets/873919/20830715/dfa7fd60-b892-11e6-82bd-10685612953f.png)

![image](https://cloud.githubusercontent.com/assets/873919/20830675/b6dbf166-b892-11e6-9fa0-2195e12b6de3.png)

![image](https://cloud.githubusercontent.com/assets/873919/20830698/ce95f0b8-b892-11e6-8bd3-b0f05ce95fc2.png)

**Comment by vasily-kirichenko** [comment]
I've narrowed down this to a minimal repro:

1. OK

![image](https://cloud.githubusercontent.com/assets/873919/20831075/800e53f2-b894-11e6-95ff-374f45cd51a7.png)

2. Fail

![image](https://cloud.githubusercontent.com/assets/873919/20831096/924672fc-b894-11e6-8ecf-2ba405f87e36.png)

![image](https://cloud.githubusercontent.com/assets/873919/20831109/a76e3138-b894-11e6-9ef6-92c5df630be2.png)

So it seems a bug in one specific branch of AST traversing.

**Comment by vasily-kirichenko** [comment]
The AST for the first binding is:

```
Binding
(null,NormalBinding,false,false,[],
 PreXmlDoc
   (Microsoft.FSharp.Compiler.Range+pos,
    Microsoft.FSharp.Compiler.Ast+XmlDocCollector),
 SynValData
   (null,SynValInfo ([],SynArgInfo ([],false,null)),
    null),
 Named
   (Wild Program.fs (5,8--5,9) IsSynthetic=false,x,
    false,null,
    Program.fs (5,8--5,9) IsSynthetic=false),null,
 App
   (NonAtomic,false,Ident async,
    CompExpr
      (false,{contents = false;},
       YieldOrReturn
         ((false, true),
          Const
            (Unit,
             Program.fs (8,23--8,25) IsSynthetic=false),
          Program.fs (8,16--8,25) IsSynthetic=false),
       Program.fs (7,18--9,13) IsSynthetic=false),
    Program.fs (7,12--9,13) IsSynthetic=false),
 Program.fs (5,8--5,9) IsSynthetic=false,
 NoSequencePointAtLetBinding)
```
for the second (failed)

```
Binding
(null,NormalBinding,false,false,[],
 PreXmlDoc
   (Microsoft.FSharp.Compiler.Range+pos,
    Microsoft.FSharp.Compiler.Ast+XmlDocCollector),
 SynValData
   (null,SynValInfo ([],SynArgInfo ([],false,null)),
    null),
 Named
   (Wild Program.fs (5,8--5,9) IsSynthetic=false,x,
    false,null,
    Program.fs (5,8--5,9) IsSynthetic=false),null,
 App
   (NonAtomic,false,Ident ignore,
    Paren
      (App
         (NonAtomic,false,Ident async,
          CompExpr
            (false,{contents = false;},
             YieldOrReturn
               ((false, true),
                Const
                  (Unit,
                   Program.fs (8,23--8,25) IsSynthetic=false),
                Program.fs (8,16--8,25) IsSynthetic=false),
             Program.fs (7,18--9,13) IsSynthetic=false),
          Program.fs (7,12--9,13) IsSynthetic=false),
       Program.fs (6,15--6,16) IsSynthetic=false,
       Some Program.fs (9,13--9,14) IsSynthetic=false,
       Program.fs (6,15--9,14) IsSynthetic=false),
    Program.fs (6,8--9,14) IsSynthetic=false),
 Program.fs (5,8--5,9) IsSynthetic=false,
 SequencePointAtBinding
   Program.fs (5,4--9,14) IsSynthetic=false)
```
