### ISSUE TITLE
Find All References within a single project

### ISSUE THREAD

**Issue by cartermp** [Microsoft/visualfsharp#1965]
This is arguably one of the most important features from VFPT to be brought over.  It's definitely critical to F# development when you've got a lot of code.

It may be difficult to get this to work across projects (e.g. a method in a C# project consumes a type in an F# project), especially until F# sits on the [Roslyn Project System](https://github.com/dotnet/roslyn-project-system), but there is still incredible value in getting this to work within a single F# project.

**Comment by vasily-kirichenko** [comment]
We should use `IFindUsagesService` which is not part of `Microsoft.CodeAnalysis.Features.Editor` yet, see https://github.com/dotnet/roslyn/commit/1db055b7776c3c80b93f5fa00f371beee131a3fe which was made few hours after https://www.nuget.org/packages/Microsoft.CodeAnalysis.EditorFeatures/2.0.0-rc was released. 

We could implement the old, now removed from the codebase, `IStreamingFindReferencesService`, which also shows results on the new "Find All References" pane instead of the old "Find Symbol Results":

![image](https://cloud.githubusercontent.com/assets/873919/21072840/5a4532ec-bee0-11e6-9fe1-03db2683036c.png)

Naturally, we want to use this new UI, so I think we should wait until the new better API is released.

**Comment by vasily-kirichenko** [comment]
Hey, @CyrusNajmabadi, could you tell us when do you plan to release new `Microsoft.CodeAnalysis.xxx` packages which include the new Find Usages API, added in https://github.com/dotnet/roslyn/commit/1db055b7776c3c80b93f5fa00f371beee131a3fe?

**Comment by vasily-kirichenko** [comment]
https://github.com/Microsoft/visualfsharp/pull/1985

**Comment by CyrusNajmabadi** [comment]
@Pilchie @jasonmal When are our new packages being released?  Thanks!
