### ISSUE TITLE
Signature Help shows info for the first parameter when the caret at the end of the last parameter

### ISSUE THREAD

**Issue by vasily-kirichenko** [Microsoft/visualfsharp#1989]
Current master

![1](https://cloud.githubusercontent.com/assets/873919/21079244/4644b9d0-bf9d-11e6-9ace-0898198af2cd.gif)

**Comment by cartermp** [comment]
I can't reproduce this with my most [recent changes](https://github.com/cartermp/visualfsharp/tree/roslyn-tooltips):

![works-for-me](https://cloud.githubusercontent.com/assets/6309070/21081933/a1ccd16a-bf85-11e6-9f67-5cbde957976f.gif)

(Note that the active parameter at the bottom is missing because there aren't any XML docs for that parameter on `StartAsTask`)

**Comment by vasily-kirichenko** [comment]
Ah, good to know it's fixed. Now we need someone who can merge it :)

**Comment by saul** [comment]
@cartermp this has been fixed - please close.
