### ISSUE TITLE
Block Structure Uses Incorrect Column or Doesn't Render

### ISSUE THREAD

**Issue by cloudRoutine** [Microsoft/visualfsharp#2052]
- Seq, Arrray expression is on column too far to the right

![](http://i.imgur.com/1ZapD2F.png)
![](http://i.imgur.com/MzEf7e7.png)
![](http://i.imgur.com/OqE0Rgk.png)

- seq expression using start of keyword instead of open brace column

![](http://i.imgur.com/tnNGwnh.png)

- Constructors are using the end of the expression instead of the start and the args in parentheses aren't getting blocked 

![](http://i.imgur.com/aELRjEu.png)

- Object expression is using the start of the enclosing expression's range instead of the first brace

![](http://i.imgur.com/UUG48ZG.png)

- No block structuring inside an interface object expression (works in class object expressions)

![](http://i.imgur.com/V89tEKl.png)
![](http://i.imgur.com/pNP5bwi.png)

- placing constructor args on a separate line can break block structuring in an object expression

![](http://i.imgur.com/MHbDXMs.png)

- Individual match cases aren't getting block structuring

![](http://i.imgur.com/4do6MGB.png)

- no block structuring on match expression inside parens

![](http://i.imgur.com/rclkyF6.png)

- try is using the right side of the keyword range instead of the left

![](http://i.imgur.com/wcodetB.png)

- sometimes lambdas add block structuring in the wrong place, sometimes they don't add it at all

![](http://i.imgur.com/kBqPUgU.png)

- else block line overextended 

![](http://i.imgur.com/nKA7B4x.png)

- no block structuring in fsi files 

![](http://i.imgur.com/vDOCqNu.png)

- no block structuring for async expr

![](http://i.imgur.com/sQPAmyr.png) 
@vasily-kirichenko are the block structuring tags also being used for the outlining?

**Comment by vasily-kirichenko** [comment]
@cloudRoutine We provide a single Block Structure service, which is used by Roslyn for outlining and guidelines. Each tag has ctor arg "is collapsible", so we can provide blocks which has guidelines, but no outlining, but not vise versa.

**Comment by cloudRoutine** [comment]
Doesn't that mean we could make all of the block structure tags non collapsible and setup the outlining tags the same as we do in VFPT to get the best of both?

**Comment by vasily-kirichenko** [comment]
It can be the last resort way, yes. Or we can ask roslyn team to extend the api (if the trick with HintSpan does not work).

**Comment by vasily-kirichenko** [comment]
If `HintSpan` works, then it should be set to our VFPT outlining spans as is. `TextSpan` should be the same as `HintSpan`, but it's start column should be adjusted so that it begins where the whole this really begins.

I.e.:
```fsharp
type Foo (i: int) =
```
here `HintSpan` should start right after the type name, but `TextSpan` should start at column 0.

And please, do not resurrect smallish blocks, like "tryInTryWith", "tryInTryFinally" and friends. They adds too much noise and will not work anyway, because Roslyn throws exception when it tries to show guideline tooltip on overlapped block spans (which are spans those start on same _line_).

**Comment by Pilchie** [comment]
Tagging @curusnajmabadi to take a look at this.

**Comment by CyrusNajmabadi** [comment]
The editor team is coming up with a system whereby we can be more explicit about what span we want for collapsing as well as what span we want for structure-guides.  Right now they use a heuristic to infer things based on the spans in the current API.  That heuristic seems to work well for the mainline set of VS languages but falls down with F#'s approach to syntax.

However, it's going to take time for that API to make it in, and for Roslyn to start targeting it.  Because of that, it might not be a bad idea to pull structure-guides from F# (or only use them on constructs where the heuristic is good) until all that work happens.

See: https://github.com/dotnet/roslyn/pull/15914

**Comment by CyrusNajmabadi** [comment]
> @cloudRoutine We provide a single Block Structure service, which is used by Roslyn for outlining and guidelines. Each tag has ctor arg "is collapsible", so we can provide blocks which has guidelines, but no outlining, but not vise versa.

This has been changed in Roslyn.  BlockSpans now have an IsCollapsible property.  Set to false to not have outlining.

**Comment by CyrusNajmabadi** [comment]
Regarding HintSpan/TextSpan.  The purpose of TextSpan is to indicate the portion that should be collapsed.  And the purpose of HintSpan is to indicate the concept of the 'entire statement'.  i.e. in this function:

![image](https://cloud.githubusercontent.com/assets/4564579/21324932/b23329a6-c5d8-11e6-9047-ea1dbbe90b83.png)

TextSpan shows what should be collapsed (and starts after the close paren):

![image](https://cloud.githubusercontent.com/assets/4564579/21324943/bd2b8600-c5d8-11e6-8e0e-aef48447f250.png)

HintSpan gives the entire method span so that hovering over the ... works:

![image](https://cloud.githubusercontent.com/assets/4564579/21324953/c89429b6-c5d8-11e6-97af-ed87828365dd.png)

The HintSpan also becomes the span used for drawing the structure guide, and for figuring out the 'statement line' that we use when showing the structure guide tooltip:

![image](https://cloud.githubusercontent.com/assets/4564579/21325025/142c3792-c5d9-11e6-9fd3-9cd1767e1a86.png)

**Comment by CyrusNajmabadi** [comment]
i think the intent of the next editor API is to allow you to be explicit about what span constitutes the whole statement (useful for that last tooltip), whereas you might still have a different span controlling where you think the structure guides would be explicitly going between.

**Comment by vasily-kirichenko** [comment]
@CyrusNajmabadi Thanks for explanation! I think `TextSpan` and `HintSpan` can cover all our needs.

**Comment by CyrusNajmabadi** [comment]
Ok.  If you run into ones that aren't handled, let me know.  I can discuss the issue with the editor team to make sure hteir work will suffice for us!

**Comment by vasily-kirichenko** [comment]
@CyrusNajmabadi Thanks :)

/cc @cloudRoutine

**Comment by cloudRoutine** [comment]
@CyrusNajmabadi thanks for the explanation, I've been able to iron out most of the issues

**Comment by CyrusNajmabadi** [comment]
Terrific.  let me know if there are any you can't!
