### ISSUE TITLE
.NET Standard/.NET Core templates

### ISSUE THREAD

**Issue by cartermp** [Microsoft/visualfsharp#2181]
We need .NET Standard and .NET Core templates for the VS 2017 release.

I suggest that we take @enricosada's work [here](https://github.com/dotnet/cli/tree/rel/1.0.0/src/dotnet/commands/dotnet-new) and modify them with the new tasks and targets necessary to build/publish/etc.

**Comment by enricosada** [comment]
So as i said to @cartermp before vacations, i am finishing some work about that. I was offline a bit last weeks.

Atm the msbuild fsproj in preview4 works (the `dotnet new -l fsharp` templates are ok).
Pratically `dotnet build` is `dotnet msbuild /t:Build`. same for other commands like publish.

@cartermp i dont understand what new task/target you mean. Can we discuss that in the visualfsharp standup tomorrow with @KevinRansom too? I am installing vs2017 but didnt finish yet my vm to develop.

The only doubt i have is if we really need FscTask for visual studio integration, or not. If we need it, see below.

About using `FscTask` instead of `dotnet-compile-fsc`, i have a working solution in my [use_fsctask  branch](https://github.com/enricosada/netcorecli-fsc/tree/use_fsctask). Examples of projects are in [dev directory](https://github.com/enricosada/netcorecli-fsc/tree/use_fsctask/dev/preview4_fsctask), and target file is [there](https://github.com/enricosada/netcorecli-fsc/blob/use_fsctask/src/FSharp.NET.Sdk/FSharp.NET.Core.Sdk.targets#L113)

Pratically the `Microsoft.FSharp.Compiler.netcore` add an auto-included .props file, to set a property to specify the location of compiler and FSharp.Build.dll. like that works pratically like current solution. See the https://github.com/enricosada/fsharp-compiler-package-preview4/tree/master/pkgs/Microsoft.FSharp.Compiler.netcore.1.0.0-beta-160629-fixed who contains the fixed package.
This package use the fsc.exe as shared netcoreapp, so can be run as `dotnet /path/to/fsc.exe`. That's really important ihmo, and we shold use the .NET Core Sdk to create the .net core packages so can be consumed easier (same for fsi, there is no reason is so complicated atm, because fsc/fsi are just console app). I'll send a pr to discuss that, now that master is for next version.

The normal commands works (build/run/publish, the pack has some error but i am fixing it) and i am trying to use that in Suave as test in https://github.com/enricosada/suave/tree/upgrade_to_preview4

The current include behaviour for .NET Core Sdk works really well, i need to polish it a bit, but is like should going forward i think

**Comment by Huqin-China** [comment]
agree with you,netstandard lib can only create by c# in vs2017,f# only have some old templates,i want my math core writtened by f# targeting netstandard.

**Comment by cartermp** [comment]
This is dependent on project system support, hence the change in milestone.

**Comment by OnurGumus** [comment]
Perhaps, this issue should be separated into two issues for each of .net core and .net standard, since they are different things, in order prevent confusion.

**Comment by cartermp** [comment]
@OnurGumus they're inseparable for the purposes of project system support.  Both require support for the new MSBuild file formats and understanding the .NET Standard reference assembly model.

**Comment by cartermp** [comment]
Closing this, as templates for this are not planned to go directly into this repo.  They exist in the [dotnet/templating](https://github.com/dotnet/templating) repo and will be pulled in by the .NET Core SDK with the project system in VS 2017.

**Comment by jsclary** [comment]
Any chance someone could give people a hint on how to get that?  Neither 15.2 nor 15.3 preview2 with F# nightlies and the .NET Core 2.0 SDK preview1 seems to get you ".NET Standard" (or ".NET Core") templates for F# in VS.  "dotnet new" does indeed have F# templates but VS doesn't.  Maybe I'm missing a step?  It makes me sad that F# feels like a second class citizen in VS.  Though really it's more like VS itself is a second class citizen ever since .NET Core and I feel like I'm watching a slow motion death reminiscent of Amilyn/PeeWee's in the original Buffy the Vampire Slayer movie.

**Comment by cartermp** [comment]
@jsclary No way to get it right now, but when we release it in the forthcoming preview of 15.3, the templates will light up automatically.
