### ISSUE TITLE
Regression: Error ranges for double backtick identifiers are broken

### ISSUE THREAD

**Issue by forki** [Microsoft/visualfsharp#2219]
![image](https://cloud.githubusercontent.com/assets/57396/21803911/9736f190-d72c-11e6-86a1-2502aca38c86.png)

this happens on master, but works in VS2015

**Comment by vasily-kirichenko** [comment]
It seems to be fixed in https://github.com/Microsoft/visualfsharp/pull/2212

module vals:

![image](https://cloud.githubusercontent.com/assets/873919/21804132/603853ca-d73e-11e6-98d2-0930a3efa23f.png)

properties:

![image](https://cloud.githubusercontent.com/assets/873919/21804158/8a20656a-d73e-11e6-8423-bef06b4bdae0.png)

methods (but no suggestion in this case):

![image](https://cloud.githubusercontent.com/assets/873919/21804179/a2c662e0-d73e-11e6-8fcd-c4af771af0ad.png)

**Comment by forki** [comment]
ok let's first check that ranges are fixed. then we care for suggestions.

**Comment by forki** [comment]
i can confirm it's fixed:

![image](https://cloud.githubusercontent.com/assets/57396/21854850/966185b4-d81c-11e6-9418-97f77fc5b63b.png)
