### ISSUE TITLE
Incorrect namespace tooltips

### ISSUE THREAD

**Issue by dhwed** [Microsoft/visualfsharp#2271]
Using latest master with Visual Studio 2017 RC2:

![image](https://cloud.githubusercontent.com/assets/10184638/21990478/89415d08-dbd4-11e6-9288-29de45270ded.png)

It seems like the tooltip is generated by only looking at the part of the namespace after the dot, as if the text were instead `namespace Data`.

**Comment by vasily-kirichenko** [comment]
wow. interesting

**Comment by dhwed** [comment]
One more example of the same issue (cursor is over `Collections`):

![image](https://cloud.githubusercontent.com/assets/10184638/21991913/12d097aa-dbda-11e6-9d69-1333003679f2.png)

**Comment by vasily-kirichenko** [comment]
I think it's because we pass last part of long ident here https://github.com/Microsoft/visualfsharp/blob/master/vsintegration/src/FSharp.Editor/QuickInfo/QuickInfoProvider.fs#L46. We should use `QuickParse.GetPartialLongNameEx` (not as a replace for `CommonHelpers.getSymbolAtPosition`, but as an extra helper to get full long ident) https://github.com/Microsoft/visualfsharp/blob/master/vsintegration/src/FSharp.Editor/Diagnostics/SimplifyNameDiagnosticAnalyzer.fs#L60

My RC2 has expired, so I cannot do it myself.

**Comment by cartermp** [comment]
@vasily-kirichenko do you get the same license issue when installing VS Community?  AFAIK you can install them side-by-side.  VS 2017 RC2 works on Community for me on my machine.

**Comment by vasily-kirichenko** [comment]
Fixed in https://github.com/Microsoft/visualfsharp/pull/2298
