### ISSUE TITLE
Add Reference from file does not work when one or more projects in the solution are unloaded

### ISSUE THREAD

**Issue by vasily-kirichenko** [Microsoft/visualfsharp#2275]
![image](https://cloud.githubusercontent.com/assets/873919/21996670/716f2882-dc3c-11e6-8825-553b2e8df335.png)

**Comment by cartermp** [comment]
Interesting.  @Pilchie is this something we control, or is this handled by the VS Reference Manager?

**Comment by forki** [comment]
Ouch

Am 16.01.2017 8:41 nachm. schrieb "Phillip Carter" <notifications@github.com
>:

Interesting. @Pilchie <https://github.com/Pilchie> is this something we
control, or is this handled by the VS Reference Manager?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/Microsoft/visualfsharp/issues/2275#issuecomment-272946810>,
or mute the thread

**Comment by vasily-kirichenko** [comment]
I think it's somewhere in our implementation of workspace / language service.

**Comment by saul** [comment]
@vasily-kirichenko - out of interest are all of the projects in the solution loaded? I know this issue appears in VS 2015 if you try to add a reference and any projects in the solution aren't loaded.

**Comment by saul** [comment]
Just tried this on a solution and adding references from file works fine

**Comment by vasily-kirichenko** [comment]
@saul yes, one project was unloaded (FSharp.Core, because otherwise nothing works having the oss vsix installed). Interesting.

**Comment by saul** [comment]
In which case there's still an issue here but just not a regression.

**Comment by cartermp** [comment]
Updated labels.  This is going to be one of the areas addressed when we move to the Roslyn project system.
