### ISSUE TITLE
Send references to FSI only appears in F# projects

### ISSUE THREAD

**Issue by rojepp** [Microsoft/visualfsharp#228]
When I'm working in a C# project, I often like to use FSI to test stuff out. The 'Send references to FSI' command only appears for F# projects. Could we get it for C#/VB projects too?

**Comment by dsyme** [comment]
I think this would be a feature request for the C#/VB project systems. I think it's unlikely they will add it though (just as we would be unlikely to add "Send to C# REPL" for F# projects - it would clutter)

**Comment by dsyme** [comment]
As per [CONTRIBUTING.md](https://github.com/Microsoft/visualfsharp/blob/fsharp4/CONTRIBUTING.md), suggestions for the VF# Tools should go to [Visual F# Tools User Voice](https://visualstudio.uservoice.com/forums/121579-visual-studio/category/30935-languages-f-tools).

**Comment by dungpa** [comment]
It would be doable in VFPT :-). But I think the feature is too specific; VFPT also supports most common use cases i.e. F# projects.

**Comment by forki** [comment]
I think mixed language projects are on the rise. People have legacy code in C# and start by adding .fsx files to the project to test a small subset of the code. 

Solving this in VFPT is a good idea since we then can safely assume people are F# interested. Fixing this in the C# project system is probably not a thing they would do.

**Comment by latkin** [comment]
Opening an issue at http://github.com/dotnet/roslyn for this couldn't hurt. If it were implemented in the box, they are the ones who would do it.  Unfortunately, although the language service and editor stuff is now open, their project system is still closed-source C++, so you couldn't just send a PR.

**Comment by vladima** [comment]
This functionality can be implemented using only DTE interfaces on the F# side (and AFAIR there was a prototype that did that). However the downside for this approach is that menu item handler won't work unless F# package is loaded. Given that VS loads packages on demand in solution that don't contain any F# project user can easily end up in situation when this menu item does not work (because package was not loaded yet).

**Comment by dsyme** [comment]
Covered by the roslyn issue
