### ISSUE TITLE
Two VFT extensions installed at the same time

### ISSUE THREAD

**Issue by vasily-kirichenko** [Microsoft/visualfsharp#2281]
![1](https://cloud.githubusercontent.com/assets/873919/22031716/943b139c-dcf2-11e6-958e-7bd6218a6a49.gif)

**Comment by cartermp** [comment]
@vasily-kirichenko I'm assuming this is this after installing an VisualFSharpOpenSource VSIX?

I know that the previous process I followed was to uninstall the current VSIX prior to installing the current way via the commandline VSIX installer, but since that no longer works for vs2017 I'm not sure if that's meaningful or not.
