### ISSUE TITLE
Code completion regression in VS 2017

### ISSUE THREAD

**Issue by vasily-kirichenko** [Microsoft/visualfsharp#2289]
Having VS 2017 unavailable today, I had to open VisualFSharp solution in VS 2015. As I was editing `TypeChecker.fs`, I noticed that intellisense worked much, much faster than it does in VS 2017 (error checking is as slow though). Actually it was so fast that it was usable (!). I mean, I was able to edit the code and intellisense appeared in a second or two.

As error checking is slow, but intellisense is fast, I assume it calls some sort of cache _before_ file rechecking result is available (or maybe it wait for file check results for a seconds, then falls back to the cache). If it's the case, we should port that cache to VS 2017. 

(memory usage was also much lower - it did not even reach 1GB)

**Comment by smoothdeveloper** [comment]
@vasily-kirichenko do you mean intellisense started to work earlier or that intellisense itself is working faster?

**Comment by vasily-kirichenko** [comment]
@smoothdeveloper It appears in a second or two after `Ctrl+Space`. In VS 2017 it does not appear until the current file is type checked, which can take very long time on `TypeChecker.fs` (intellisense is basically unusable on this file in VS 2017).

**Comment by dsyme** [comment]
@vasily-kirichenko Yes, intellisense in VS2008-2015 used CheckFileInProjectIfReady and I think also stores the FSharpCheckResults in the "FSharpSource" object.  However **this technique accesses stale results** and lot of glitches and inaccuracies result from that.  It works in many, many situations but there are lots of glitches too.

The Roslyn re-implementation dropped the use of CheckFileInProjectIfReady  - and indeed doesn't store the checked results in any Roslyn object - it **always** goes back to FCS to ask for results.  This is also what Ionide and Xamarin Studio do.  

I didn't even argue about this changes because there was so many other problems of missing functionality already in the Roslyn implementation, so it's good you bring this up now.  

At the time I didn't have the heart to argue to put inaccuracies back in to the auto-complete implementation.  I don't think we should really do that now, but we should try to work out the common cases where we can address this without introducing inaccuracies.  For example, maybe we just need to find a way where we can avoid re-checking entire files and instead just restart checking part way through a file.  Or perhaps we could make two requests - one for the fast results, and one for the slow results, and timeout the slow results after 0.5s or something.

**Comment by saul** [comment]
I'd rather have stale results than no results. Most of the time I care about IntelliSense in modules in other files or assemblies. I think @dsyme's suggestion of waiting half a second for the slow results (timeout configurable in settings) is a reasonable middle ground.

**Comment by vasily-kirichenko** [comment]
https://github.com/Microsoft/visualfsharp/pull/2315

**Comment by dsyme** [comment]
Closing as https://github.com/Microsoft/visualfsharp/pull/2315 has been accepted
