### ISSUE TITLE
Invalid indentation warning when using [<Literal>]

### ISSUE THREAD

**Issue by rojepp** [Microsoft/visualfsharp#229]
The compiler warns me when I do this:

![screenshot 2015-02-12 15 12 13](https://cloud.githubusercontent.com/assets/445888/6168930/cd4fc538-b2c9-11e4-8961-6efa3f0e4080.png)

While this works:
![screenshot 2015-02-12 15 15 39](https://cloud.githubusercontent.com/assets/445888/6168957/07eb7688-b2ca-11e4-887e-97e8de7c90c9.png)

It looks like warnings but it also stops the program from compiling.
> The namespace or module 'Queries' is not defined

The 'Queries' module is the one that contains the code in the screenshot.

**Comment by enricosada** [comment]
found the same bug today

**Comment by dsyme** [comment]
Could you move this to fslang.uservoice.com, as a suggestion to "Iron out the inconsistencies about where [<Literal>] can be used on the same line as a keyword"?

Basically, there are a couple of places where you can use it on one line (e.g. "type"), but these are the exception rather than the norm.

Thanks
Don

**Comment by rojepp** [comment]
Can we please drop uservoice? I wont move this bug there. Feel free to do it for me. :)

**Comment by dsyme** [comment]
Hi @rojepp,

Posted here: http://fslang.uservoice.com/forums/245727-f-language/suggestions/7090326-make-the-single-line-use-of-literal-consistent

Right now http://fslang.uservoice.com is how we run the F# language/core-library design process.  As mentioned in CONTRIBUTING.md, language/core-library suggestions and adjustments must have an entry there.  It's important, or else we lose track of changes to the F# langauge specification amidst a sea of tooling and compiler implementation detail.

Right now, the behaviour above would, for better or worse, end up being classified as "inconsistent, but by design" for F# 2.0-4.0. This is because the risk of adjusting it is high - any change in the lexfilter would need very, very careful attention, as it's possible (though not certain) that it would cause a breaking change elsewhere in some corner cases. So as it stands, the suggestion is to potentially adjust the behaviour of the F# language.

Cheers
Don
