### ISSUE TITLE
wrong type for expression when piping expression to constructor

### ISSUE THREAD

**Issue by smoothdeveloper** [Microsoft/visualfsharp#230]
```fsharp
module Foo
open System.IO

let foo =
  use stream = File.OpenRead("foo")
  use reader = new StreamReader(stream)
  use reader2 = (stream |> new StreamReader)
  ()
```

somehow ```reader2``` has type ```IDisposable``` where I expected it to have type ```StreamReader```

It looks like a bug or I need to understand something I'm overlooking.

**Comment by latkin** [comment]
Using the `new` keyword is not allowed in this form.  Indeed, your code does not compile - see the squiggle on line 7

![image](https://cloud.githubusercontent.com/assets/5943573/6174391/41bfc64c-b2a3-11e4-89f4-2b40a76ba31d.png)

Your code should read:

```fsharp
module Foo
open System.IO

let foo =
  use stream = File.OpenRead("foo")
  use reader = new StreamReader(stream)
  use reader2 = stream |> StreamReader
  ()
```

This does cause a warning `It is recommended that objects that support the IDisposable interface are created using 'new Type(args)' rather than 'Type(args)' to indicate that resources may be owned by the generated value`, which is presumably why you tried adding `new`.

I agree this is not a perfectly-polished experience.  The 'ctors as first-class functions' feature at the moment does not support anything analogous to `new Type(args)`.

The easiest resolution is maybe to update the warning so it reads `...created using 'new Type(args)' rather than 'Type(args)' or 'Type' as a function value representing the constructor...`

@dsyme does that sound reasonable?

**Comment by dsyme** [comment]
Yes, that sounds reasonable.

**Comment by enricosada** [comment]
use something like?
```fsharp
stream |> (new StreamReader)
```
to avoid warning? less readable?

**Comment by latkin** [comment]
@enricosada yes that would be one approach for full-fledged support. We can just update the warning message for now since that's easy, while we wait for @dsyme to add `(new StreamReader)` syntax support :smile:

**Comment by smoothdeveloper** [comment]
@latkin & all thanks for the feedback, yes the initial warning led me to try out things.

I basically got puzzled while having statement which doesn't compile but still having type inferred for the binding (wrong as it was giving IDisposable, which I now understand is based on the ```use``` binding, if I put ```let``` it gives obj as inferred type).

I'm getting a better sense of inference engine as I write more F# code :)

**Comment by KevinRansom** [comment]
LGTM
