### ISSUE TITLE
How to use compiler from master to build projects from command line?

### ISSUE THREAD

**Issue by smoothdeveloper** [Microsoft/visualfsharp#2300]
#### Repro steps

* open prompt in master
* type `build.bat net40`
* build a project in VS 2015 with F# 4.0
* copy the command line in output window
* adjust compiler path to \release\net40\bin\fsc.exe in that command line and try to run

#### Expected behavior

project is compiled with master branch compiler

#### Actual behavior

> Unhandled Exception: System.IO.FileLoadException: Could not load file or assembly 'fsc, Version=4.4.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. Strong name validation failed. (Exception from HRESULT: 0x8013141A) ---> System.Security.SecurityException: Strong name validation failed. (Exception from HRESULT: 0x8013141A)
   --- End of inner exception stack trace ---

#### Known workarounds

None

#### Related information 

Provide any related information 

* win 10 64
* master
* .net 4.5
* VS 2015

**Comment by majocha** [comment]
Run `src\update.cmd` from admin dev prompt. It adds relevant exemptions from strong name validation.

**Comment by smoothdeveloper** [comment]
@majocha thanks, I have few questions:

* do I need to run this command after each `build.bat net40`?
* wouldn't it make sense to have the default build work out of the box (just calling `build.bat` even) and only release / MS inhouse builds with the signing stuff?

It feels this repository should aim to become as easy as possible for contributors to peek into, that means running build.bat once compiles FSC/FSI ready to use, and after that, just doing build in VS also works.

It feels we aren't there yet and I'm unsure if it is the explicit aim, all the bootstrapping / product / platform support (which are big deal and not as simple as the ideal experience I'm describing above) could live in more complex invocations of build script.

**Comment by KevinRansom** [comment]
Run the command once to get the registry strong name exemptions registered.
run it each time you rebuild to get the ngen compilation done, if you want it ngened.

The problem with aseasy as possible is that ever since we've started the latest and greatest build tools and even build sceanrios have been changing and they still are so we've optimized for building the repo and not worried about much else.

I am looking at the build again to use the new cross platform build tools and even figuring out a way to do what we currently do is a pain in the arse.  So ... I appreciate that it is currently unpleasant ... I want to see if we can create a basis on which to build a usable build system.  That satisfies the scenarios we need moving forward.  Once we have that basis we should be in a position to improve it's functionality.  However, that may be pure optimism on my part.

Kevin

**Comment by smoothdeveloper** [comment]
Thanks @KevinRansom !

I know it is not good time to get in the way, so I hope all my questions and poking around aren't disturbing too much.

When it is time to consider new system, I hope we will move the main driver to F# scripts and we can have more knowledge dissemination about the whole structure.

Please update us about what's cooking in a discussion issue when possible.
