### ISSUE TITLE
Type providers should have a way of affecting update check

### ISSUE THREAD

**Issue by rojepp** [Microsoft/visualfsharp#234]
In VS, I have code like this:
```fsharp
open FSharp.Data
type Query = SqlCommandProvider<"Query.sql", cn>

[<EntryPoint>]
let main argv = 
    let q = new Query()
    let result = q.Execute()
    for v in result do printfn "%A" k.col1
    0
```
and 'Query.sql' looks like this:
```sql
select 1 as col1, 2 as col2
union all
select 2, 1
```

If I change the name of `col1` in 'Query.sql' and save it, I get squiggles thanks to FileSystemWatcher code in FSharp.Data.SqlClient. If I then choose to build, the project is not rebuilt, so it looks like compilation succeeds! This is because 'Query.sql' is not checked by the project system when checking to see if the project needs to be rebuilt. The project system does not know that this file affects the build. Minor issue affecting F# demos everywhere. :) 
This issue affects every TP that reads a local file. 

A couple of ideas for solving this:
*   Modify TP interfaces to allow a TP to give a list of files to check. The list is checked after creation and after `Invalidate` is called.
    * Breaking change
    * Each TP needs to be modified to behave, making it an awkward jump to F# vNext for each TP.
*    Trigger a rebuild if `Invalidate` has been called on the TP
    * No breaking change
    * Won't work for incremental command-line builds
    * Will not behave properly when solution has just been opened (either always trigger rebuild or never), as invalid state is not persisted.
*    Add a new TP interface
     Can this be done in a way to still allow a TP to be usable from F# 3?

**Comment by dsyme** [comment]
Don't you just add Query.sql to your project and mark it as "Content" (or whichever of those settings is appropriate? :) )

**Comment by dsyme** [comment]
As per [CONTRIBUTING.md](https://github.com/Microsoft/visualfsharp/blob/fsharp4/CONTRIBUTING.md), suggestions for the F# Language/Compiler/Core-Library should go to [F# Language User Voice](https://fslang.uservoice.com/).

**Comment by rojepp** [comment]
I'd have thought so too, but that doesn't work. That may be because I'm running some 3.x preview build. 
Anyway, query.sql isn't content, it's source code without compilation, really.. :)
(Uservoice)[https://fslang.uservoice.com/forums/245727-f-language/suggestions/7090613-allow-type-providers-to-affect-update-check]

**Comment by dsyme** [comment]
Uggh.  It's hard to believe what a mess of options MSBuild gives you. 

Did you try BuildAction of "DesignData"?  It seemed to work for me when I just tried (not on a TP example though).  The docs indicate it's something to do with Xaml though so it may not be right http://stackoverflow.com/questions/145752/what-are-the-various-build-action-settings-in-vs-net-project-properties-and-wh

**Comment by rojepp** [comment]
@dsyme Indeed. Unfortunately, "DesignData" does not work for me, though I am running a preview build of 3.1.2 in which @latkin had been messing with update-checks. :)

**Comment by latkin** [comment]
Adding the file as Content *should* work with the new fast up-to-date check, as that's one of the item types that gets tracked. See [here](https://github.com/Microsoft/visualfsharp/blob/fsharp4/vsintegration/src/vs/FsPkgs/FSharp.Project/Common.Source.CSharp/Project/ProjectConfig.cs#L1469). If that's not working for some reason, first step to debug is to set the reg key mentioned [here](https://github.com/Microsoft/visualfsharp/blob/fsharp4/vsintegration/src/vs/FsPkgs/FSharp.Project/Common.Source.CSharp/Project/IDEBuildLogger.cs#L31) so that logging is turned on.

And FWIW this behavior is not a regression with new up-to-date check, the old msbuild-based check didn't know about these files, either.

**Comment by smoothdeveloper** [comment]
Sorry for this (sounds a bit like msbuild questions)

In my context I have dozens of .sql files (will become hundreds), and the code sample that @rojepp gave is generated whenever a file is added / removed.

Is there an option for me to make msbuild 'glob' all those files recursively (given a root directory) instead of having to maintain the project file?

Is there a way to make those file unseen in VS in case there is too much overhead showing those?
