### ISSUE TITLE
[RC3] Cannot install OSS VSIX

### ISSUE THREAD

**Issue by vasily-kirichenko** [Microsoft/visualfsharp#2342]
![image](https://cloud.githubusercontent.com/assets/873919/22402715/615d9746-e612-11e6-8dc1-a3a984280515.png)

![image](https://cloud.githubusercontent.com/assets/873919/22402717/7317fd00-e612-11e6-9ce1-70395e39941b.png)

Maybe it's time to merge `vs2017-rtm` to master?

**Comment by smoothdeveloper** [comment]
I've got similar issue following the RC3 steps (it worked on another machine, but with 2 windows 7 machines  I faced the same issue).

My only way to use last bits from now is to compile and run the VisualFSharp.sln Opensource vsix project.

**Comment by cartermp** [comment]
cc @brettfo

**Comment by brettfo** [comment]
Sadly this is a known issue with the VSIX Installer tool, and one that I'm currently pushing back on internally.  The installer only considers the first three parts of the version number (15.4.1 in this example) to be significant.

**Comment by smoothdeveloper** [comment]
What can we change at build time so the version number is different?

**Comment by brettfo** [comment]
The best thing I can tell you right now is to install `VisualFSharpOpenSource.vsix` (after building locally) which has its version set to `42.42.42.42` which will always override `15.4.1.x`.

**Comment by KevinRansom** [comment]
Ahhh I had this on my dell laptop last night.  I successfully installed the downloaded vsix by using the vsixinstaller directly like this:

````
%ProgramFiles(x86)%\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\VSIXInstaller.exe %USERPROFILE%downloads\VisualFSharpFull.vsix
````

I have to say it was pretty frustrating,  I knew the process was supposed to work since I had been through it successfully about a dozen times.  But one of my two main dev laptops it just didn't work.


I hope this works out for you ...

Kevin
