### ISSUE TITLE
( .. .. ) operator is always shown in completion list

### ISSUE THREAD

**Issue by vasily-kirichenko** [Microsoft/visualfsharp#2397]
![image](https://cloud.githubusercontent.com/assets/873919/22782174/e51b4b9c-eed6-11e6-817b-85d11485eaae.png)

**Comment by smoothdeveloper** [comment]
I've noticed weird completion in `#r` and `#load` directives:

![image](https://cloud.githubusercontent.com/assets/87944/22783039/476a19e8-eeca-11e6-8873-4c156f1aa5fe.png)

It affects string literals as well, and in any case, only happens if I trigger completion with ctrl-space (which is pointless, but people will actually do that to probe if there is actual completion available for that use case), this doesn't happen in VS2015.

not sure if related, but with debugger attached, the triggering completion in those cases would pause on prim-types.fs L3803:

```fsharp
        [<CompiledName("Raise")>]
        let raise (e: exn) = (# "throw" e : 'T #)
```

This is running from master (https://github.com/Microsoft/visualfsharp/commit/a58b5011c989bbca049502bf0759cbde3380d352)

**Comment by vasily-kirichenko** [comment]
The exception in prim-types.fs is always thrown and it's not related.

**Comment by vasily-kirichenko** [comment]
Fixed both in https://github.com/Microsoft/visualfsharp/pull/2398
