### ISSUE TITLE
Full FSI support on .NET Core 2.0

### ISSUE THREAD

**Issue by dbettin** [Microsoft/visualfsharp#2407]
From #2400 

>Properly handle the model for how .dlls are laid out on disk with .NET Core, thus fixing #r
Establish a good working model for how to do the above
Prompt to re-load an FSI session when #r’ing an assembly that targets a higher target than what FSI was launched with?
Error message asking user to re-load FSI manually?
Try to re-target and re-reference everything on the fly?

**Comment by KevinRansom** [comment]
@dbettin it's like you are channeling my nightmares today.  Assembly reference and loading in a coreclr world requires a lot of thought too.  FSI was and to a lesser extent the desktop FSC were very helpful in finding and resolving assemblies ... at the price of a lot of determinism.

It's a goal we need to fix by the time .NetStandard 2.0 is released.  The details however, are not yet available.

**Comment by dsyme** [comment]
My comment from the fsharp-opensource mailing list:


> There’s been progress – we’ve had variations on this working – but there’s a strong feeling that we need to get “#r on a nuget package” designed, implemented and finalized before the experience will be correct and stable for both .NET Core and .NET Framework. See also https://github.com/Microsoft/visualfsharp/pull/2483

**Comment by KevinRansom** [comment]
Support for FSI on dotnet core.

Yes it will happen absolutely.  That it hasn't yet, is extremely embarrassing to me.  The reason is technical, rather than priorities or anything else.  Well priorities have been impactful ... but they are not the main reason.

The issue is this: we test fsi.exe on coreclr and have done for a long ... long time, and it works well.  Unfortunately ... (and this is the embarrassing bit) it relies on a bug in the coreclr to work ... in AssemblyLoadContext.  If we fix the code to what we need it to be now that the bug is fixed in the coreclr, the entire way we test the coreclr build needs changing.  This is the exact same reason why we still rely on project.json in our build.

I fully understand the irony of what I just said above ... if we fix the bug we can't test it ... if we don't fix the bug we can't ship it.  I hate myself for this ... and if you want to expose me to the universe for the full idiocy of the position I just expressed I know how insane it is.

We must fix our build ... we must fix the testing ... I promise it will happen ...

I actually prefer Don's explanation, because coreclr FSI without built-in package management is definitely going to require external packagement to make scripts that reference libraries reliable.

However, in reality releasing fsi is not gated on adding packagemanagement it is gated on us digging out of a historic build/test mess that I created for us.

I am truly sorry about that.

Kevin

**Comment by forki** [comment]
What annoys me personally is that we bundle both things. We could already
have a nice package management story in classic fsi and could make HUGE
progress on FAKE 5. But we wait for netcore....

Am 01.09.2017 9:52 nachm. schrieb "Kevin Ransom (msft)" <
notifications@github.com>:

**Comment by KevinRansom** [comment]
I haven’t bundled both things.  I’m saying, and I think quite clearly, that my stupidity on the build and test is what is blocking this.  Fixing the build and test will enable FSI.  Good Package management in FSI will make the world pretty groovy.

Kevin

**Comment by matthid** [comment]
@KevinRansom I just really wanted to write that I appreciate and value your response. While I can see that this is embarrassing it feels like honesty is really a good way forward for this repository.

Too often (and maybe even only for historical reasons) we feel like there is some hidden agenda or political reasons behind stuff. So this really helps a lot. Thank you.

About what @forki said: I think a response on the other issue regarding the latest suggestions from the community might help.

**Comment by dsyme** [comment]
> Unfortunately .it relies on a bug in the coreclr to work ... in AssemblyLoadContext. 

I wasn't aware of this.  Do you have a link to the bug for this?  Thanks. Also a link to the place in the F# code where we are relying on this. Full transparency please :)

**Comment by KevinRansom** [comment]
The bug is in how you implement load contexts.  What we do in FSI results in a stack overflow on bug fixed coreclr’s.

The fix looks like this:  https://github.com/Microsoft/visualfsharp/pull/3140/files#diff-3229c72e3fbd323c1dde9692aceedd65L322

It was part of PR to basically enable FSI on netstandard 2.0.   However, work you and I have done superseded this PR, apart from this little bit.

**Comment by matthid** [comment]
Just to add: The runtime people suggested to me to use my own assembly load context (as I was hitting some similar issues with FAKE at the time), since I have done that the code and the loading logic feel a lot "cleaner". 

Technically, this also fixes a lot of outstanding problems in FAKE like that you cannot use a different fcs version in your script code (for example when using fsf). 

So maybe this should be something to consider. But yeah especially for fcs this might be breaking as existing users might depend on having the same set of assemblies available in the script code as in the host code.

**Comment by halcwb** [comment]
Is there any progress regarding this issue?

**Comment by cartermp** [comment]
@halcwb Not at the moment, no. We've been occupied primarily with some critical issues in existing workflows for .NET Core and IDE support. Hoping to pick up the in progress work on this soon.

**Comment by abk-x** [comment]
fsi.exe that comes with SDK 2.1.302(.dotnet/sdk/2.1.302/FSharp/fsi.exe) works, you get missing reference exceptions sometimes (e.g. System.IO.File), but it takes all of 1 minute to work around it:

Create a F# project and add the functions you want, e.g. `let read = System.IO.File.ReadAllBytes`, then compile this project, and `#r` the resulting DLL in fsi.exe

As a nice plus, it works well with VsCode, including colours. There are some readline warts, but its still worlds better than mono fsharpi

**Comment by cotyar** [comment]
@abk-x How you managed to run it please? 
Cannot get neither .dotnet/sdk/2.1.302/FSharp/fsi.exe nor .dotnet/sdk/2.1.400/FSharp/fsi.exe working on Win10 x64

**Comment by nosami** [comment]
You can use `--readline+`

```
dotnet /usr/local/share/dotnet/sdk/2.1.302/FSharp/fsi.exe --readline+
```

**Comment by nosami** [comment]
@zpodlovics 

![readline](https://user-images.githubusercontent.com/667194/44629269-732d0280-a944-11e8-9298-ffc8ecc05c71.gif)

Strange - it seems ok on OSX

**Comment by nosami** [comment]
@zpodlovics - I see what you mean now, there is definitely something wrong with readline when used from `dotnet`

![readline2](https://user-images.githubusercontent.com/667194/44629328-6957cf00-a945-11e8-9cb2-75d064984cb7.gif)

**Comment by zpodlovics** [comment]
The callgraph looks horrible:
https://gist.github.com/zpodlovics/68eab3f5188313e33c665ed1a9af4c09

**Comment by zpodlovics** [comment]
I have managed to get a source build of fsi.exe (using the tricks from https://github.com/Microsoft/visualfsharp/issues/5636) and created a quick callgraph profiling (using --readline+ option). The first 4/5 of the callgraph is F# startup, the more interesting parts is on the remaining 1/5. 

On backspace the writeChar / render loop looks really weird as it use some deeply nested read/change call chain.

The svg callgraph are available here (download it if you want zoomable interface):

https://gist.github.com/zpodlovics/28c61d357b054bd4659cd5b8bd7294d3

![screenshot from 2018-09-16 14-00-22](https://user-images.githubusercontent.com/8523206/45596227-3afb6b80-b9a8-11e8-91a0-e17d488313c4.png)

A typical callstack looks like this from the callgraph:

![screenshot from 2018-09-16 13-24-07](https://user-images.githubusercontent.com/8523206/45596201-d213f380-b9a7-11e8-8802-5c3138728d48.png)
![screenshot from 2018-09-16 13-21-22](https://user-images.githubusercontent.com/8523206/45596203-d213f380-b9a7-11e8-8e69-901fb86258f8.png)

The text profile are available for speedscope (https://github.com/jlfwong/speedscope or online https://www.speedscope.app/):

https://gist.github.com/zpodlovics/d0ac67c47680df1e68c0704e918c2b16

![screenshot from 2018-09-16 14-19-52](https://user-images.githubusercontent.com/8523206/45596400-e2799d80-b9aa-11e8-97bb-299ccf3bca75.png)

**Comment by AviAvni** [comment]
@zpodlovics from the code https://github.com/Microsoft/visualfsharp/blob/master/src/fsharp/fsi/console.fs#L381-L470
it's look that something with the tail call is not working
did you profiled the fsi.exe from the Debug or Release directory?

**Comment by zpodlovics** [comment]
@AviAvni I have tried out originally with the SDK packaged fsi.exe which is a release build (and unusable when readline enabled), but I was not able to resolve the managed symbols in the profile. It was probably the release build, I will create an another profile later. Checked now, the source build release version is still unusable with readline enabled.

**Comment by AviAvni** [comment]
@zpodlovics the problem with --readline+ is also happen in the .net framework fsi on windows

**Comment by mtnrbq** [comment]
Is there a rough view on the ETA for this support ?
Am I correct that we missed (aka were thrown off) the v2 Azure Functions boat already? - Azure/azure-functions-host#3414

**Comment by cartermp** [comment]
We have the necessary infrastructure built in and a first run at a NuGet plugin built. @KevinRansom can share more details, but I would expect this to land in a .NET Core SDK update before a Visual Studio update.

![image](https://user-images.githubusercontent.com/6309070/47618319-ca5b6a80-da8e-11e8-8a3f-b80f2e0c5d62.png)

(Note: syntax of `#r` is not finalized; this is just so there is a straightforward parser)

**Comment by costincaraivan** [comment]
Any news on this front? 😨

**Comment by cartermp** [comment]
Closing this as it's now in preview: https://devblogs.microsoft.com/dotnet/announcing-net-core-3-preview-3/

`dotnet fsi --readline` is what you can use now.
