### ISSUE TITLE
While reviewing the typedefof raise ... colouring PR I noticed that type keywords are coloured blue in signatures

### ISSUE THREAD

**Issue by KevinRansom** [Microsoft/visualfsharp#2481]
I wonder if this is intended or a by product of keyword colouring this items.

To my mind this looks a bit off ....

![image](https://cloud.githubusercontent.com/assets/5175830/23279802/8bf7aa06-f9cb-11e6-816d-e2e43cd0cca5.png)

**Comment by vasily-kirichenko** [comment]
A number of well known type aliases are colored as keywords, similar to C#, for about a couple of months :) @cloudRoutine hates it and removed in its PR, but I think this feature should be optional but we don't have used settings page because we cannot access Roslyn UI base classes (no nuget and it requires version 15 of CodeAnalysis packages).

**Comment by KevinRansom** [comment]
@vasily-kirichenko 
What is the justification for coloring them blue as keywords rather than cyan as types?  I don't want to bikeshed this but @cloudroutine has a point.

**Comment by vasily-kirichenko** [comment]
@KevinRansom that was not me who implemented this or even suggested the initial idea. I'll make a PR removing it soon.
