### ISSUE TITLE
Message about the missing System.ValueTuple reference should be visible in editor

### ISSUE THREAD

**Issue by gsomix** [Microsoft/visualfsharp#2547]
#### Repro steps

1. Create new F# project in VS2017.
2. Use System.ValueTuple somewhere in code, e.g.:
``` fsharp
[<EntryPoint>]
let main argv = 
    let origin = struct (0, 0)
    printfn "%A" origin
    0
```
3. Remove the reference to System.ValueTuple assembly from the project to observe the error message

#### Expected behavior

Failed build with message in the Error List window with code `FS0074` and description:
```
The type referenced through 'System.ValueTuple`2' is defined in an assembly that is not referenced.  You must add a reference to assembly 'The system type 'System.ValueTuple`2' was required but no referenced system DLL contained this type'
```

This error also should be highlighted in the editor window.

#### Actual behavior

There is no message neither in Error List, nor in the editor.

#### Known workarounds

Only way to determine why build was failed is to check Output window.

#### Related information 

* **Operating system:** Windows 8.1
* **Branch:** the one included into VS2017 release, "F# 4.1 (FSharp.Core 4.4.1.0)"
* **.NET Runtime, CoreCLR or Mono Version:** building project for .NET 4.5.2 (the default)
* **Editing Tools (e.g. Visual Studio Version):** VS 2017 release
* **Indications of severity:** minor

Similar code in C# indicates about error both in the Error List window and in the editor.

![struct error list](https://cloud.githubusercontent.com/assets/832449/23700301/d748ee8a-040b-11e7-9149-c7f3a3a9e597.png)

**Comment by cartermp** [comment]
This could be tricky...@KevinRansom would you have an idea as to why this is the case?

Just for context, this is a language feature which depends on a NuGet package for .NET Framework because it's not part of .NET Framework proper today.  That sort of muddies things up a bit.

It fails with `FS0074`, so there's definitely a true error to flow through diagnostics.

**Comment by KevinRansom** [comment]
There are two separate reasons for this:
1   .It seems as if Build output isn't accumulated into the error window.  Only intellisense errors.
2.  The language service doesn''t need the nuget package for system.valuetuple.dll, sine a copy of the dll is already loaded and so the definition for those types can be found.

1. We should definitely fix.  
Not sure what to do about 2.  when build output is merged with intellisense the error will show up, that is probably easier than making the language service unaware of the ambient system.valuetuple.dll.

Kevin

**Comment by KevinRansom** [comment]
Additional discussions: https://github.com/Microsoft/visualfsharp/issues/2548

**Comment by cartermp** [comment]
Since this issue has been filed, the error is correctly flowed into the output window:

<img width="1081" alt="screen shot 2018-06-09 at 16 41 50" src="https://user-images.githubusercontent.com/6309070/41197000-0f70823a-6c04-11e8-8b52-297791a2b778.png">

And there are .NET Frameworks that now have SVT in there. I'm going to close this because I don't think it's worth doing the work to get the squiggles in place, given that there's no way for this error to occur unless you explicitly remove the reference.
