### ISSUE TITLE
FSI fails with two references to the same assembly name in different dlls

### ISSUE THREAD

**Issue by KevinRansom** [Microsoft/visualfsharp#2554]
@dsyme,

FSI fails with two references to the same assembly name in different dlls.
````
type c:\temp\foo1.fsx
#r @"\projects\ReferenceExample\ImplementationAssembly\bin\Debug\ReferenceAssemblyExample.dll"
#r @"\projects\ReferenceExample\ReferenceAssembly\bin\Debug\ReferenceAssemblyExample.dll"
let c = new ReferenceAssembly.MyClass()
let _ = c.X

c:\microsoft\visualfsharp>debug\net40\bin\fsi --exec c:\temp\foo1.fsx
System.InvalidProgramException: JIT Compiler encountered an internal limitation.
   at <StartupCode$FSI_0001>.$FSI_0001.main@()
Stopped due to error
````
This has undoubtedly been an issue forever with FSI on the desktop but because references were always hand coded as part of the script.  It was considered a case of ... the script is broken fix the script.

Unfortunately with the package dependency approach being taken by @dsyme and @forki which generates portions of a script containing #r directives from files downloaded by a dependency manager it is fairly likely that assembly name collisions are going to happen.

The fix will be something like:  
__When adding a reference, if an assembly with a matching name has already been referenced ignore the subsequent reference.__

You could consider taking the later reference and dropping the first, except, in FSI state is accumulated, if types have already been generated based on the initial reference then they would not match types generated against the earlier reference.

I don't think it is the responsibility of the package manager to deal with this.  It seems to me that it's job is to deal with the packages, not the implementation details of the tools that use it.

We could consider a warning or an error on the #r .

What do you think?

**Comment by dsyme** [comment]
> When adding a reference, if an assembly with a matching name has already been referenced ignore the subsequent reference.

That seems fine, perhaps with a warning from FSI (though only if the full paths are different)

**Comment by smoothdeveloper** [comment]
> which generates portions of a script containing #r directives from files downloaded by a dependency manager it is fairly likely that assembly name collisions are going to happen.

This is already taken care in the sane case:

* package A depends on C
* package B depends on C

the script which is generated and `#load`'ed will only have C once, it will also resolve C based on selected strategy if the versions relied upon are conflicting in A & B.

The case which is not detected is 
* package A depends on CA
* package B depends on CB

where both CA and CB are in fact the same assembly (whatever the version) but somehow package publishers didn't agree and published  it under two package names.

I hope that makes sense.

**Comment by KevinRansom** [comment]
@smoothdeveloper 
package dependencies and dll's are not strictly the same.  Except in the case of one dll per package.  Which may be what you mean by the sane case.

**Comment by smoothdeveloper** [comment]
@KevinRansom yes, if a package has several assemblies, it still behave properly in paket (I worked with @matthid and @baronfel on that generate script feature), I'm using it everyday to load large amount of packages with many assemblies and haven't faced a "version" conflict yet.

If I try to do the same in a F# project, I do need binding redirects, but FSI handles it well somehow.

**Comment by KevinRansom** [comment]
Well ... in the new world ... we compile against reference assemblies and execute against implementation assemblies.  So FSI is going to need to be able to deal with this ("Frankly horrifically busted scenario") somehow ... 

So you just filter out subsequent dll's with the same name?

**Comment by smoothdeveloper** [comment]
@KevinRansom I didn't really understand the specifity of new world...

In current world, (assuming we can perform the resolution in one hop) paket will:
* identify nuget packages (includes transitive, and resolve conflicts, only one version of C in my first example, even if A and B depend on two different versions)
* for each package, it will check the assemblies to resolve the order (one package has several assemblies, they need to be loaded in correct order)
* generate a single list of #r with everything in order and no duplicates

the difficulty we are having with FSI is that the resolution in case of transitive `#load`'ed scripts doesn't seem to happen in one pass, this needs to be fixed in FSI, you can try this test: https://github.com/Microsoft/visualfsharp/pull/2483/files#diff-2e59414db11caec24f5db18179e98ff1 which shows the issue.

**Comment by KevinRansom** [comment]
@smoothdeveloper 

indeed if there were no references assemblies what you describe would be correct.  Indeed, that is how it is on the desktop most of the time.  Except with portable profiles of course.

When you compile against System.Runtime.dll, on the desktop the implementation of the types in it are in mscorlib.dll.  On coreclr they are in System.Private.Corlib ... at lest some of the types are.

For framework types the CLR deployments kind of take care of the details and so FSI can mostly work.  On the coreclr FSI doesn't know what to load or where to find it.

So to compile the code the CLR needs to load the System.Runtime reference assembly to generate types, and it also needs to load the System.Runtime.dll implementation assembly so that it can run the generated code.

Ahhh!!!! I hear you say but ... we could just compile against the implementation version of System.Runtime,dll that has to have the types after all it is executing them ... except it doesn't have the type the implementation version of that assembly is just type forwarders to mscorlib and System.Private.CoreLib.dll and probably a few other DLLs.

Well that's okay you  might say, it's just type forwarding ... let the loader take care of it., except these types are in a nuget package folder and not necessarily in the same directory as the framework and so we are reliant FSI being told where to find them and being able to load them and work with them.

Now ... System.Runtime.dll is a bad example because it is part of the core framework currently guaranteed to be available to runtime apps.  But the techniques it demonstrates represent the likely way the framework will evolve, as well as libraries from sophisticated developers.

Why should the model support a ref/implementation split ... whilst a straight IL assembly is good for all platforms ... developers may well want to tune their libraries to operate better on different platforms.  So in the normal case the implementation and reference  will be the same assembly some developers may want the ability to deliver platform optimized libraries.

Currently F# does not support the ability to create reference assemblies,  but it does interoperate with C# which certainly does allow it.

The current desktop focused FSI model works pretty well on the Desktop and Mono. We will deploy FSI and FSC to use the shared framework model this will mean deploying the framework once. 

Any way not having a GAC and allowing for a model with Reference/Implementation split complicates FSI a lot more than it did FSC.

**Comment by smoothdeveloper** [comment]
@KevinRansom thanks, this helps understand all what it is about, and the fact that FSC can remain oblivious because it just needs the interfaces/signatures, while FSI has to eventually load actual implementation assemblies which can be different on each platform.

In new world, is it always "one ref assembly points to a single impl assembly" or there can be more than one impl assembly involved?

Looking forward to see how VF# team will implement those changes in the loader.

**Comment by KevinRansom** [comment]
For two years I have struggled to understand how to move forward on FSI.  It didn’t really click until Don and I had a long …. long chat about the issue, and about what was happening with the paket integration that it became clear that the real issue was to teach FSI about Ref assemblies and implementation assemblies.

There must be a loadable assembly with a name that matches the assembly name for the reference assembly.  It may well contain type forwarders to other assemblies.

E.g.
              System.ValueTuple is currently in a separate assembly.  It is going to move to mscorlib in dotnet 4.3.

In order to continue to continue to support apps that compiled against it when it was in svt.dll the implementation will consist of an svt.dll with a typeforwarder to mscorlib.  I.e one ref, two implementation assemblies.  And the technique is not proprietary and so sophisticated developers could use the same techniques.

Are you loading the assemblies in the dependency manager in order to figure out what order to load them so that you can write the #r’s in the correct order?  If so you probably shouldn’t do that for performance.  FSI should not try to load and execute code from those assemblies until the script has been completely executed.  After all the script is only a list of #r, if FSI fails to load them because they were presented in the wrong order then we should fix that.

**Comment by smoothdeveloper** [comment]
>  And the technique is not proprietary and so sophisticated developers could use the same techniques.

So is this information located in the ref assembly itself? Is there any way we can avoid introducing extra `#r "impl:"` or others just to handle that and let FSI/runtime do the right thing?

> if FSI fails to load them because they were presented in the wrong order then we should fix that.

It has come before, I haven't faced this but people told me they faced the issue and we decided to implement it.

We could disable this as an option in paket and indeed it would save some time, for all packages with more than one assembly.

**Comment by matthid** [comment]
Sorry to interrupt this discussion, but I need more information about exactly this process you are discussing for implementing the new FAKE.netcore version.
I think I have understood the principle and what I did for now was using reference assemblies for compilation (ref folder) but loading the runtime dlls from the current folder (which worked in preview2).
With "current folder" I meant the current distribution of FAKE, which obviously needs to work as it is running at this point.

@KevinRansom As I understand your comments this process is more generic, so is that documented which assemblies need to be loaded at runtime (or at least which need to be copied to the output when compiling for netcore). Or alternatively point me to the current implementation?

So my question is:

>  There must be a loadable assembly with a name that matches the assembly name for the reference assembly. It may well contain type forwarders to other assemblies.

Where is it? In the current "lib" folder?

> And the technique is not proprietary and so sophisticated developers could use the same techniques.

How? Is there documentation?

And one last question: Is there some special case for some runtime assemblies/nuget packages or does it work generically once implemented?

Or to simplify all questions above: I can now compile with the "ref" folder (instead of the "lib" folder) but how exactly do I run it :)

I think this might help @smoothdeveloper and others as well to see whats happening.

**Comment by KevinRansom** [comment]
@smoothdeveloper. nugget/msbuild creates an assets file which is json format.  I expect paket does something similar.  You can determine from the assets whether a dll is reference, or runtime.
