### ISSUE TITLE
IDE Feature Suggestion: goto anything for member signature

### ISSUE THREAD

**Issue by smoothdeveloper** [Microsoft/visualfsharp#2588]
I'd like to leverage the "goto anything" from Visual Studio to allow to search for member signature:

example of signatures:
* `_ -> System.Type` matches anything which is a function (whatever arity) and returns a System.Type
* `'a [] ->'a -> bool ` matches things like `Array.contains` (it doesn't care of the order of arguments)
* `string seq -> string` matches things like `String.concat`

Equivalent systems:
* https://www.haskell.org/hoogle/
* http://fsdn.azurewebsites.net/
* http://pages.cs.wisc.edu/~jignesh/publ/sigmatch.pdf (@cloudRoutine)

We would need to discuss the conventions for the signature patterns, but this tool would be super helpful trying to figure out what to use from large code base (like the compiler).

**Comment by cartermp** [comment]
The first thing we'd need is a decision on the prefix character.  We could try to extend `t` to recognize when you're tying a type signature rather than a type name, or come up with another prefix character.

Part of the issue is that Go to All is fundamentally based on names, so introducing this is a whole new mode of use.  I think it's a fantastic idea, but we'd also have to make sure whatever we do isn't pushing us into our own little universe.  I'm not privy to the details of how to add a new prefix character, but if so, we may need to make that a feature request for the team which owns Go to All.

**Comment by vasily-kirichenko** [comment]
go to anything uses parser trees. this feature requires typed ast, which I don't think possible for performance reasons.

**Comment by smoothdeveloper** [comment]
@vasily-kirichenko / @cartermp actually thinking it doesn't have to fit in goto anything if that's a constraint, it could be a specific search tool similar to find all references.

**Comment by SebastianAtWork** [comment]
test
