### ISSUE TITLE
Is the nightly auto publisher dead?

### ISSUE THREAD

**Issue by vasily-kirichenko** [Microsoft/visualfsharp#2664]
![image](https://cloud.githubusercontent.com/assets/873919/24096862/6a34a4ca-0d74-11e7-93e4-f304b82c0938.png)

![image](https://cloud.githubusercontent.com/assets/873919/24096841/59b615b6-0d74-11e7-8a5a-3cd0783cce47.png)

**Comment by majocha** [comment]
Switched off for the weekend? When Redmond wakes up someone will flip the switch back :)

**Comment by cartermp** [comment]
@brettfo Would know more, but this could be due to one of two reasons:

1. Coincidentally, no microbuild was kicked off
2. No automated microbuild gets kicked off over the weekend

If it's the latter, maybe we can do something.  Closing for now though, since the process isn't dead

**Comment by brettfo** [comment]
In short, the package should get updated every morning, Monday through Friday.

Long answer:
- A new package is published every time our internal `microbuild` branch builds successfully.
- That branch is set to build on every push.
- We have a scheduled task that merges `master` every weekday morning at 2am (Redmond time).
- If there were no changes then there is no build.

We chose to not build on the weekends because there won't be anybody in the office to look at the build failures.

**Comment by forki** [comment]
If there is a build failure then no vsix will be produced and we will wait
until Monday. No need to disable, right?

Am 20.03.2017 17:56 schrieb "Brett V. Forsgren" <notifications@github.com>:

**Comment by brettfo** [comment]
> If there is a build failure then no vsix will be produced

That's correct.

> No need to disable

Nothing gets disabled on a build failure (or re-enabled on a build success.)  The package upload is simply the last step of the build script so any failure before then will short-circuit the package publish step.

**Comment by forki** [comment]
No I meant no need to disable the build on weekends.

Am 20.03.2017 18:03 schrieb "Brett V. Forsgren" <notifications@github.com>:

**Comment by brettfo** [comment]
Ahh, I understand the question now.

Ultimately it comes back to the part about nobody being in on the weekends to look at build failures.  We try to keep our build queues green and if a build break gets merged on Friday afternoon, we'd have 3 red builds come Monday morning to triage; Saturday, Sunday, and Monday.  Even though all three build failures would (likely) be the same issue, we've been asked to try to avoid build noise and our attempt at doing this is to simply not do a build when there'd be nobody to look at it.

This is also the same approach other VS teams use, including Roslyn, of not building on the weekend.

If we regularly start getting lots of code coming in on the weekends, we can revisit the option of running merges/builds every day.

**Comment by forki** [comment]
I think most of the code comes on weekends. But tbf if Kevin is not in the
office it usually would not land in master. So that's OK. I also now think
more important that build failure is a a big bug in the vsix itself. So if
a new vsix is released and nobody is there to roll it back then this can
indeed be bad. So I think I now agree. Keep it as is and don't release in
weekends.

Am 20.03.2017 18:16 schrieb "Brett V. Forsgren" <notifications@github.com>:
