### ISSUE TITLE
[Feature Enhancement] Quickinfo with Navigation links

### ISSUE THREAD

**Issue by cloudRoutine** [Microsoft/visualfsharp#2673]
Feauture added in [Clickable QuickInfo with "go to type" ](https://github.com/Microsoft/visualfsharp/pull/2574)

I really love this feature and I think we can take it a lot further than its initial implementation 

- **Allow navigation to modules**

![](http://i.imgur.com/IMWQcQA.png)

- **Allow navigation to function bindings**

![](http://i.imgur.com/WHs8jmf.png)

- **Allow navigation to operator definitions (type or module)** 

![](http://i.imgur.com/p3XQvyg.png)

- **Allow navigation to discriminated union and enum cases** 

![](http://i.imgur.com/z0dBWxV.png)

- **Allow navigation to type members/methods/properties** 

![](http://i.imgur.com/i7v3SVG.png)

- **In signatures link to other signatures, not implementation files** 

![](http://i.imgur.com/2nc3OFV.png)

- **In implementation files link to other implementation files** 

![](http://i.imgur.com/BwqROkm.png)

- (Eventually) allow navigation to external symbols via metadata signature generation 

Some additional comments documenting the functionality would also be useful, especially in `Quickinfo Provider.fs`, just from looking at the source it's unclear how the navigation functionality works and where one should look to see it's implementation.  I'd already forgotten where it was by today and had to go digging back into the PR to find it.

cc @majocha , @cartermp, @smoothdeveloper

**Comment by majocha** [comment]
Thank you, @cloudRoutine. I have a small improvement to add so I'll write missing comments with it and also make it a bit less scattered.

The interesting stuff of the implementation is deep inside, true :) Searching all references to `NavigableTaggedText` helps here.

It builds on @vladima's titanic commit ed948aba. The idea is to piggyback some more info on top of the classified text in `Layout` that in the end is being used in quick info. I tried to identify places where types are laid out and pass navigational data there.
With this approach making more entities browsable is possible as long as the required data is available at the point the layout is created. I'll try to work on this.

Another thing that worth considering is using `PreferProvisionalTab` option. Currently it is buggy, causing occasional duplicate tabs :(

Navigating to `.fs` instead of `.fsi` looks hard. Currently `EntityRef.DefinitionRange` is used and it seems it always points to .fsi definition for referenced projects.

**Comment by cloudRoutine** [comment]
Couldn't you move quickinfo down in the compilation order, move the tooltip generation to a class method, construct the class with an MEF import on the gotodefinition class and then use that to handle the navigation?

**Comment by vasily-kirichenko** [comment]
We use `PreferProvisionalTab` in `FSharpGoToDefinitionService` and it works OK I think.

**Comment by vasily-kirichenko** [comment]
@majocha that small tooltip-for-tooltip should be colorized as well ;)

**Comment by vasily-kirichenko** [comment]
...and has links to navigate to, say, intermediate module... ;)

**Comment by majocha** [comment]
@vasily-kirichenko colorized and browsable, yes :)
I'm not sure what's going on with the ProvisionalTab. Should work.

**Comment by majocha** [comment]
@cloudRoutine I can try, but in the and GotoDefinition service also just calls TryNavigateToSpan.

**Comment by majocha** [comment]
@cloudRoutine Now I see that would be the correct approach. GoToDefinitionService sometimes blocks for quite some time, but that should not happen in our case. At the moment quick info shows up, the document is parsed and checked already.

**Comment by smoothdeveloper** [comment]
Hey, right click / find all references could be useful too!

**Comment by vasily-kirichenko** [comment]
:)

**Comment by cloudRoutine** [comment]
@majocha I've addressed the speed issue in my generate metadata PR, so eventually that won't be a big deal

**Comment by majocha** [comment]
More entities allow navigation now. In the end there is no obstacle to make everything navigable, ![function](https://cloud.githubusercontent.com/assets/1760221/24198844/d3088b44-0f07-11e7-8d65-dfc6582dec9b.gif)
but it doesn't always look nice:
![more](https://cloud.githubusercontent.com/assets/1760221/24198847/d5b73b06-0f07-11e7-8bfb-896d3ffd65d2.gif)

GoToDefinitionService is used now but there is some repetition here I'm not happy with. Basically we give it the position we want to go to, because we already have it. The service makes an unnecessary roundtrip to look up the symbol and then navigates.
[https://github.com/Microsoft/visualfsharp/compare/master...majocha:navigable-improvements](https://github.com/Microsoft/visualfsharp/compare/master...majocha:navigable-improvements)

**Comment by cloudRoutine** [comment]
@majocha I'll PR some of the gotodef speed improvements I made onto your branch and try to get rid of that roundtrip

**Comment by majocha** [comment]
@cloudRoutine I don't think we can get rid of it because it's what GoToDefinitionService do, it looks up a definition.

**Comment by cloudRoutine** [comment]
@majocha I totally got rid of it ;) https://github.com/majocha/visualfsharp/pull/1

**Comment by cloudRoutine** [comment]
@majocha totally got rid of it https://github.com/majocha/visualfsharp/pull/1

**Comment by majocha** [comment]
Awesome! One minute because I was mucking around with it later and there's a conflict.

**Comment by vasily-kirichenko** [comment]
I think we can close it now?

**Comment by vasily-kirichenko** [comment]
@cartermp Close it?
