### ISSUE TITLE
No tooltips for core union cases

### ISSUE THREAD

**Issue by vasily-kirichenko** [Microsoft/visualfsharp#2806]
![1](https://cloud.githubusercontent.com/assets/873919/24721698/c8005c48-1a49-11e7-963c-7b314a1fe7c7.gif)

**Comment by vasily-kirichenko** [comment]
It turns out this is reproduced on https://github.com/Microsoft/visualfsharp/pull/2805 only, closing it.

**Comment by majocha** [comment]
I think it's because here 
[https://github.com/Microsoft/visualfsharp/blob/master/vsintegration/src/FSharp.Editor/QuickInfo/QuickInfoProvider.fs#L196](https://github.com/Microsoft/visualfsharp/blob/master/vsintegration/src/FSharp.Editor/QuickInfo/QuickInfoProvider.fs#L196)
`getTooltipFromRange` will fail when range doesn't point to a file in the solution.
