### ISSUE TITLE
Visual F# Tools "More information" immediately starts download of vsix

### ISSUE THREAD

**Issue by BentTranberg** [Microsoft/visualfsharp#2832]
#### Actual behavior

In the Extensions and Updates dialog in VS 2017, when looking at the entry for Visual F# Tools, version 15.4.1.17040601, and clicking on the "More information" link, this link will promptly download VisualFSharp.15.4.1.17040601.vsix

This doesn't make sense. I asked for more information, not a download without confirmation.

#### Expected behavior

1) I would expect a link titled "More information" to lead to a page with more information, specifically information about the releases so that I can see what's happened since the last update. I would not expect a link with such a title to start a download without any confirmation.

2) Also, what's the point of downloading something you obviously already downloaded? The green tick was next to the entry for Visual F# Tools.

If this link can be used instead, then at least it is possible to see the dates for the versions. If somebody really intends to download a vsix manually, then any vsix can be downloaded from that page. This would be more user friendly.

https://dotnet.myget.org/feed/fsharp/package/vsix/VisualFSharp

And on that page it would be nice with a link or links to release notes. That's what I was looking for.

#### Related information 
Severity: Very low

**Comment by cartermp** [comment]
Unfortunately, I don't think this is something we can control.  It's likely some old VS behavior.  @brettfo could you clarify on if this is something we can control?

**Comment by KevinRansom** [comment]
@brettfo can you forward this to someone on the vsix team please.  Perhaps they have an explanation, my guess is that the "more information" is stored in the vsix manifest.

**Comment by brettfo** [comment]
The feed itself (https://dotnet.myget.org/F/fsharp/vsix) doesn't expose a useful link that would be a good candidate for the "More Information" link and browsing the settings for the MyGet feed I was unable to find anything meaningful to set.  I've filed internal bug 406674 against the team that owns that dialog.

@KevinRansom, I looked through our VSIX manifest and didn't see anything that looked promising, but I suspect this value would be specified on the feed itself and not in the manifest, because that would still require downloading and unpacking the VSIX first, which seems a bit heavy-handed just to get a text link.  I'll also continue looking around on the MyGet feed settings and ask them, too.

**Comment by KevinRansom** [comment]
@brettfo :  
If it's just a URL, then send it to either fsharp.org or to the docs here:  
https://msdn.microsoft.com/en-us/visualfsharpdocs/conceptual/visual-fsharp

@cartermp is there a better landing page for "further info"?

Kevin

**Comment by cartermp** [comment]
@KevinRansom https://docs.microsoft.com/en-us/dotnet/articles/fsharp/

The MSDN docs are retired aside from the FSharp.Core API reference, which will soon be migrated to docs.microsoft.com as well

**Comment by brettfo** [comment]
I contacted the VSIX team and @KevinRansom was right; the link gets specified in the manifest file.  I've opened #2841 with a fix.

**Comment by brettfo** [comment]
Fixed in #2841.
