### ISSUE TITLE
High DPI: On a high dpi screen the layout of the Build properties dialog is broken

### ISSUE THREAD

**Issue by KevinRansom** [Microsoft/visualfsharp#285]
Description:

I think this is because my laptop is high dpi.  But it could apply to standard screens too.Image below

Note:
* the prefer 32-bit label is cropped
* the output section is cropped

Expected:
Layout to be good for a range of screen types including my laptop

Repro:
* Open an existing F# console app or create a new one
* Select Project properties
* Select the Build Tab

Twitter ID: @codecutterman

![bug4](https://cloud.githubusercontent.com/assets/5175830/6429126/40c6cd20-bf74-11e4-8132-ff4f535a3764.jpg)

**Comment by enricosada** [comment]
High dpi and windows form is tricky, got bugfix til 4.5.2.
maybe is better to have a cleanup strategy instead of single bugfix (these fix the problem, but not make easier to improve the code) 
A good medium term option is an up-for-grab to convert the project view in xaml.
Using [WindowsFormHost] and [ElementHost] to easier migration, we can convert a view at time.

- easier: convert single page to xaml and embedd with [ElementHost]
- best: container control converted to xaml, page (like build/debug/etc) are embedded with [WindowsFormHost]

when are all converted, remove host and we are good to go :D. 
After the first page, the others are easy to do

Also a good idea is to convert the whole project from vb to c# with a project converter. vb->c# converter are pretty solid

[WindowsFormHost]: https://msdn.microsoft.com/en-us/library/system.windows.forms.integration.windowsformshost(v=vs.110).aspx
[ElementHost]: https://msdn.microsoft.com/en-us/library/system.windows.forms.integration.elementhost%28v=vs.110%29.aspx

**Comment by latkin** [comment]
Same bucket as #284

**Comment by KevinRansom** [comment]
I'm unable to repro this on exactly the same machine.  Although it is a different build of VS and Visual F#.  I will leave this active for a bit, in case I can figure out the steps that caused it to get out of whack.  But it is probably best not to burn too many cycles on this.

**Comment by dsyme** [comment]
Closing as it is old and not-reprod
