### ISSUE TITLE
Go to Definition (F12) does not work in scripts

### ISSUE THREAD

**Issue by vasily-kirichenko** [Microsoft/visualfsharp#2850]
![1](https://cloud.githubusercontent.com/assets/873919/25007895/a6dec7d0-206a-11e7-837a-66d66f1d1418.gif)

**Comment by smoothdeveloper** [comment]
I've noticed that in between two scripts (one loaded by the other), it would work only if both editors are open.

It works in VS2015 given VFPT is installed.

**Comment by majocha** [comment]
@smoothdeveloper single file projects created for scripts are eagerly removed as soon as the editor is closed. New project system will hopefully fix this.

**Comment by smoothdeveloper** [comment]
@majocha thanks, do you know if it will work even without opening the loaded .fsx in the first place?

**Comment by majocha** [comment]
@smoothdeveloper No idea, but it's what I would expect.

**Comment by majocha** [comment]
[https://github.com/Microsoft/visualfsharp/blob/master/vsintegration/src/FSharp.Editor/Navigation/GoToDefinitionService.fs#L339](https://github.com/Microsoft/visualfsharp/blob/master/vsintegration/src/FSharp.Editor/Navigation/GoToDefinitionService.fs#L339)

It changes extension from fsx to fs and then fails to get the file because it doesn't exist.

**Comment by vasily-kirichenko** [comment]
Fixed in https://github.com/Microsoft/visualfsharp/pull/2855
