### ISSUE TITLE
Changes in referenced projects are not seen until restart

### ISSUE THREAD

**Issue by vasily-kirichenko** [Microsoft/visualfsharp#2872]
![1](https://cloud.githubusercontent.com/assets/873919/25119795/446134cc-2424-11e7-8b52-ab15f104b6b0.gif)

I think it's a huge bug.

**Comment by majocha** [comment]
I've noticed it will refresh when you click and focus the editor.
Still, it's not what one would expect.

It's bad already that you need to save the changes in one project to get them propagated to other project.

**Comment by vasily-kirichenko** [comment]
@majocha things are much worse. Restarting VS does not help (!). Rebuild does not help. Only deleting `obj` and `bin` folders does. And it does not reproduced on Debug configuration, only on Release (I mean the configuration that the test solution uses, not VFT is build on).

**Comment by majocha** [comment]
New project system desperately needed.

**Comment by vasily-kirichenko** [comment]
:) I strongly believe someone is working on it right now. Right now.

**Comment by dsyme** [comment]
@vasily-kirichenko I would have thought the DLL timestamps of the newly compiled DLL were being checked, causing a recheck in the dependent file.  I don't think it's a project system bug.  This is the incremental builder or something else in the process of rechecking files.

Any chance you could you make a minimal repro with exact steps?

**Comment by dsyme** [comment]
I believe this is fixed by https://github.com/Microsoft/visualfsharp/pull/3025, at least for the cases I've been looking at.  I've manually tested on an EXE project referencing a DLL library project, and changes in the library project such as 

* [x] remove file from library project (correctly makes red squiggly appear automatically in open file of EXE project)
* [x] add file to library project (correctly makes red squiggly disappear automatically in open file of EXE project)
* [x] remove reference from library project 
* [x] add reference to library project 

There may be additional cases such as renames and others not covered by that, where we need to listen to RDT

**Comment by vasily-kirichenko** [comment]
I've tested it on a small solution, it's fixed in #3025.

**Comment by dsyme** [comment]
Fixed by https://github.com/Microsoft/visualfsharp/pull/3025
