### ISSUE TITLE
Add "Install package" code fix

### ISSUE THREAD

**Issue by vasily-kirichenko** [Microsoft/visualfsharp#2873]
![image](https://cloud.githubusercontent.com/assets/873919/25124177/a712570e-2433-11e7-8da1-33549de234e0.png)

We could steal / use packages indexing logic from Roslyn sources.

**Comment by forki** [comment]
Noooo. Please please please please let's not repeat that epic mistake. It will make dependency management even harder

**Comment by vasily-kirichenko** [comment]
Why? It would use Paket of course, respect paket.references for the current project, etc. What's the problem?..

**Comment by forki** [comment]
If the stuff is in lock file then fine. But things like R# are AFAIK
referencing stuff from nuget.org and just putting that package into your
app. That's madness.

Am 18.04.2017 11:55 vorm. schrieb "Vasily Kirichenko" <
notifications@github.com>:

**Comment by vasily-kirichenko** [comment]
Ah, no. If we will implement it, we implement it so that you and Peket are happy :)

**Comment by cartermp** [comment]
cc @CyrusNajmabadi, who built this feature for C#

There were some reasons why this was turned off by default for C#, part of which came down to needing to drop a new typeforwarding `.dll`.  If this were to be built, and the C# feature turned on, then we'd have two on-launch downloads of a compressed database of symbols, two typeforwarding `.dll`s, and two mechanisms by which packages get added this way.  Not ideal, and may end up suffering the scrutiny of VS shiproom.

I believe what was built depends on `ISymbol` based on quickly browsing the source.  That may mean it's very difficult for us to use, if not impossible.  Perhaps work could be contributed in Roslyn to make it usable by F#?  I think the best approach is the following:

1. Work to make the existing feature usable by F#
2. Work to allow the existing feature to use Paket instead of NuGet if that's what the user would prefer

I don't know what either of those looks like, but I would guess it's a fair bit of work.  Would love to see this in the IDE for F#, though.

**Comment by vasily-kirichenko** [comment]
@CyrusNajmabadi Yes, we need the index only. So we can import `ISymbolSearchService` and use it?

**Comment by CyrusNajmabadi** [comment]
right now it's internal.  do you have IVT?  Note: we reserve the right to change this interface at any time.  :)

**Comment by vasily-kirichenko** [comment]
@CyrusNajmabadi we don't http://source.roslyn.io/#Microsoft.CodeAnalysis.Workspaces/GeneratedInternalsVisibleTo.cs :(((

We want to :) Is it possible to add FSharp.Editor assembly there?

**Comment by CyrusNajmabadi** [comment]
I currently doubt it :)    IVTs are a super high burden for us.  They effectively open the door for any change becoming one that can break you.

Better would be a request for us to expose the ISymbolSearchService.

**Comment by forki** [comment]
No. Really. Please don't activate that feature. It's just wrong.

Am 18.04.2017 6:00 nachm. schrieb "Phillip Carter" <notifications@github.com

**Comment by vasily-kirichenko** [comment]
@forki what's wrong with it?
