### ISSUE TITLE
Bugs in the Error List

### ISSUE THREAD

**Issue by dsyme** [Microsoft/visualfsharp#2927]
Version 5.4.1.17042601

I'm getting consistent situations where the errors shown in the error list are incorrect.   I don't have a specific repro yet - I just notice it all the time when using FSharp.sln.

- Fixed intellisense errors not ever disappearing 
- Unfixed intellisense errors not ever appearing 
- Fixed intellisense errors taking a very long time to disappear

Notes:

- This applies both to red suigglies and the Error List window
- Autocomplete and quick info is accurate, indicating that the Reactor is still processing requests  (so it's not a case where the reactor queue has just gotten very long)

I don't have any workaround yet except to restart VS.  The problem starts happen very soon after re-opening FSharp.sln and trying to get some work done.

It's a very major problem that's relatively new (it has been happening the last 2-3 days).  I'll try to find possible PRs that might have caused this, but if anyone has any ideas please link them below.

**Comment by dsyme** [comment]
It's possible that https://github.com/Microsoft/visualfsharp/pull/2839 fixes this but that seems to only be about "Build" errors

Also, ti seems to be a recent regression, whereas I think that was fixing a problem that's been around VS for a fair amount of time.

**Comment by cartermp** [comment]
I've noticed this as well in large files.  In particular, mucking about with `Salsa.fs`:

* Sometimes IntelliSense errors won't go away even if they're fixed
* Sometimes the Delete and Backspace keys don't work, neither do the arrow keys
* Sometimes I'll have errors reported for a line which I removed, and that reporting won't go away until a bit

I suspect this is related.

**Comment by majocha** [comment]
@cartermp backspace and arrow keys are recent indeed (#2921).
Other recent thing I'd add: switching branches often causes the colorization (and all other IDE functions) stop working.

**Comment by dsyme** [comment]
@saul @vasily-kirichenko Any ideas on anything that might have regressed error lists in the last couple of weeks?  Prior to  #2839?

@saul Any thoughts on whether #2839 night fix this?

**Comment by saul** [comment]
Hmmm... I'd be really surprised if #2839 caused this. The most likely candidate for the problems is some change in the compiler service. My PR only linked up build errors back to the error list... I can't imagine how they'd interact (despite them both appearing in the same window). Any changes in the document diagnostic service in FSharp.Editor? I'd be more inclined to believe that my task cancellation PR caused this than the build error list one. However I doubt it's either of them.

It's worth mentioning that I've seen all of the problems that you're mentioning but I only saw them when working on my project loading PR, so I assumed it was to do with changes I'd made there (apparently not...)

I'd start looking in the document diagnostic provider and/or checking how long the reactor queue is. If errors aren't disappearing, it's probably because the diagnostic service is taking a while to pass the IntelliSense errors back to Roslyn.

**Comment by dsyme** [comment]
@saul Yes, for sure #2839 didn't cause it - it was happening the day before that got integrated.  But I suspect something in the last 2 weeks

>  I'd be more inclined to believe that my task cancellation PR caused this than the build error list one. 

I'll take a look at that.  

> The most likely candidate for the problems is some change in the compiler service

I'll check all recent commits to vs/...

I'll also try to get a repeatable repro

**Comment by dsyme** [comment]
I feel that we can use around April 6th as a cut off date (I may be wrong

For the detective work, here are the commits in [src/fsharp/vs](https://github.com/Microsoft/visualfsharp/commits/master/src/fsharp/vs) and [FSharp.Editor](https://github.com/Microsoft/visualfsharp/commits/master/vsintegration/src/FSharp.Editor) since then

**Comment by dsyme** [comment]
I haven't got a repeatable repro for this yet, closing until we do
