### ISSUE TITLE
Structured printing of enum values missing enum name prefix (MyEnum.)

### ISSUE THREAD

**Issue by isaksky** [Microsoft/visualfsharp#2957]
When using `sprintf "%A"` with enum values, the name of the enum is missing.

#### Repro steps
```fsharp
type MyEnum = Good = 1 | Bad = 0
sprintf "%A" MyEnum.Good
```
#### Expected behavior

Including the name of the enum, like we have to do in valid code:

`val it : string = "MyEnum.Good"`

#### Actual behavior

It only prints the "case" name:

`val it : string = "Good"`

This also occurs when using `any_to_string` from `sformat.fs`.

**Comment by dsyme** [comment]
@isaksky This is expected behavior - we just rely on the ToString on enum values.   We could change this - in theory the spec for ``%A`` is "human readable" - but I'm somewhat loathe to since in practice it could easily be a breaking change.  

Also adding the prefix doesn't guarantee that the result is machine readable, since the relevant namespaces may not be open.
