### ISSUE TITLE
Nothing works on ProjectSystem project

### ISSUE THREAD

**Issue by vasily-kirichenko** [Microsoft/visualfsharp#2970]
![1](https://cloud.githubusercontent.com/assets/873919/25590177/1abf13f2-2eb8-11e7-8238-f12cd5fc8d3b.gif)

@saul I may find interesting the strange behavior with trying to save the project file.

**Comment by saul** [comment]
I'm also seeing this, see https://github.com/microsoft/visualfsharp/issues/2788#issuecomment-298221877.

I only really see it in the debug hive - I've noticed that if I build from build.cmd instead of Visual Studio, it seems to work better. "Sequence contains more than one element" is an error I saw when trying to add a reference to a project a week ago or so... so that may be another way to reproduce this.

**Comment by saul** [comment]
Okay now I'm seeing this on my normal instance - it was affecting every project. It was triggered by reloading the solution. Restarting VS fixed it however 😕

**Comment by dsyme** [comment]
@vasily-kirichenko Things are now working in this project for me, please reopen if you continue to have problems

(Intellisense take a long while to first appear due to need to first typecheck the rest of the solution)

**Comment by dsyme** [comment]
(The issues in this project were all about the behavior of IDE features in the presence of missing transitive assembly references.  It is worth testing new IDE features with this project now and then as a test case to see if a new IDE feature works)

**Comment by vasily-kirichenko** [comment]
Now I have this issue on OSS VSIX release as well. 

1. git clean -dfx
2. build vs debug (otherwise nothing will work for any project in VFT solution)
3. build vs
4. release\net40\bin\VisualFSharpOpenSource.vsix

result

![image](https://cloud.githubusercontent.com/assets/873919/25891151/a7a658f4-3578-11e7-801b-c10b6fcc7056.png)

**Comment by dsyme** [comment]
> build vs debug (otherwise nothing will work for any project in VFT solution)


This should not be needed.  Will look at it.

**Comment by dsyme** [comment]
@vasily-kirichenko OK I can repro some of these problems

1. git clean -dfx
2. build vs
3.  VSIXInstaller.exe /u:"VisualFSharp"  (admin prompt)
4. VSIXInstaller.exe release\net40\bin\VisualFSharpOpenSource.vsix (admin prompt)

and opened a script and things worked ok.  But when opening VisualFSharp.sln I saw the problems where it tries to reference the "Debug" FSharp.Core DLL

**Comment by dsyme** [comment]
There are several problems

1. Major: The treatment of cached project options and other tables in LanguageService.fs and ProjectSitesAndFiles.fs is wrong when the active solution configurations change .  (Note, that code is also known to be the cause of our major problems with other changes such as solution unload/load/reload).  In this case, VisualStudio starts up with an empty and/or Debug configuration and then sends an ``OnActiveProjectCfgChange`` notification.  When processing this we do something wrong - either we fail to flush the project options table, or something like that.  Hence even when opening VisualFSharp.sln in "Release" configuration we still get the error about missing "Debug" dll.

2. Minor: When editing VIsualFSharp.sln (i.e. when FSharp.Core is a project reference) we are requiring a physical FSharp.Core.dll on disk rather than using a virtualized FCS cross-project assembly reference.  The requirement for a physical file on disk stems from ``fsharpBinariesDirValue``. This is not a big deal as it only affects compiler developers since other users don't have FSharp.Core.fsproj as a cross-project reference

The systematic problem we as a group are having is that we have been introducing changes, features and performance work in the Language Service (e.g. LanguageService.fs) under the assumption that projects, solutions and the active configuration are static things.  However in reality projects change over time - as does the active configuration.   

We actually have hundreds of tests for this sort of thing but they exercise the "old" non-Roslyn logic.   So it feels like we have lost significant test coverage and/or basic testability in the process of Roslynizing the code.

@saul's PR https://github.com/Microsoft/visualfsharp/pull/2909 may be helpful but I also think that we should first do a less ambitious PR focused entirely on correctness under changing the active configuration, solution load/reload, and/remove project, add/remove project references, add/remove files, and then later focus on performance.

Lessons: 
1. We have to dig out a number of significant regressions and do a lot more testing around changing configurations etc.

2. We have to make this stuff more testable and perhaps try to recover our unit testing

3. Further churn may not help things, we have to be careful not to make the situation worse,

**Comment by dsyme** [comment]
@saul When you get the chance could you DM me on twitter , or email me?  I'd like to skype-chat to run a few questions by you about how/where to maintain the correct FSharpProjectOptions objects in the face of configuration changes, project reloads etc.

**Comment by dsyme** [comment]
This was fixed a while back
