### ISSUE TITLE
Do not add ValueTuple NuGet package reference if targeting .net 4.7

### ISSUE THREAD

**Issue by vasily-kirichenko** [Microsoft/visualfsharp#2983]
As .net 4.7 is generally awailable now (https://blogs.msdn.microsoft.com/dotnet/2017/05/02/announcing-the-net-framework-4-7-general-availability/), it would be logical if templates did not generate reference to ValueTuple NuGet package if user chose .net 4.7 as target framework.

**Comment by dsyme** [comment]
Indeed I'm not sure what the behavior would be (which System>ValueTuple types would be referenced?) if we do

**Comment by cartermp** [comment]
I'm not aware of any way to express this in our template system for VS.  As an aside, these sorts of things are precisely why the dotnet/templating system was built.  @KevinRansom would you know?  Otherwise, we'll have to ask around

**Comment by dsyme** [comment]
Could make the reference use an MSBuild ``Condition``?

Or we just remove it and make people add the package reference by hand when using struct tuples with new projects for < .NET 4.7. I'd be ok with that - I've always found it looks OTT to reference a nuget package by default for a relatively corner-case feature of F#.

**Comment by cartermp** [comment]
This is what C# did - they force you to get the NuGet package.  It hasn't really been received well, but at the same time I don't think there were a whole lot of people using the new tuples in non-.NET Core (or not .NET Framework 4.7) projects.  Honestly, I don't think there's a good solution to this.

**Comment by dsyme** [comment]
@cartermp Right, though for F# the feature is more marginal still, since you can always use ref tuples.  I think dropping the default reference is likely to be the best approach as it gets us where we want to be in the long term

**Comment by cartermp** [comment]
Hmmm.  In thinking about it, I think we're okay.  I haven't seen any uptick in F# 4.1 features talked about in blogs ("You won't BELIEVE how I increased my performance with this struct tuple trick!"), and since that's really the only measuring stick I have for these things, I'd be okay with that experience-wise.

**Comment by KevinRansom** [comment]
.NET 4.7 should need the System.ValueTuple package.  The BCL team 'forgot' to add a type forward in the ref assembly for the profile.  4.7.1 should be correct.

**Comment by KevinRansom** [comment]
I will update the reference in the templates.  Roslyn can get away with not auto-referencing ValueTuple because they have an analyzer which proposes and adds the reference.  I don't consider ValueTuple a corner case ... struct tuples with ref returns should be a big perf gain.  We do need to get used to using them.
There should be no problem with build perf on having the nuget package reference, since  project new deploys the package.  It only needs to go back to nuget.org if the packages folder is deleted.

**Comment by dsyme** [comment]
Closing as @KevinRansom says:

> .NET 4.7 should need the System.ValueTuple package. The BCL team 'forgot' to add a type forward in the ref assembly for the profile. 4.7.1 should be correct.
