### ISSUE TITLE
Running fsharpqa tests results in files being added to unstaged list

### ISSUE THREAD

**Issue by brodyberg** [Microsoft/visualfsharp#302]
Observed: 

After running fsharpqa tests there are ~42 files that appear in the unstaged list. Something like 39 dlls, an exe and a pdb. 

Expected: 

The same number of unstaged files before and after an fsharpqa test run. 

Possible fix: 

We could ignore all dlls, exes and pdbs below tests/fsharpqa, [like this](https://github.com/brodyberg/visualfsharp/commit/cc8bbeab575ac980ddbdaf2cdcf742e9aa72fe33). However, nearby lines in the .gitignore are much more focused. Assuming we want to address this, should we do it in a broad way (like the link) or in a focused way? If we choose the broad way would we remove the focused lines since the ** will handle those cases?

Thanks, 

Brody

**Comment by latkin** [comment]
It looks to be safe to ignore `*.exe` and `*.pdb` from `tests\fsharpqa\source` (there are checked-in EXEs at `tests\fsharpqa\testenv\bin`)

Right now there are some checked-in DLLs that are used for fsharpqa tests (some are managed, others are native).  From a quick check, the majority have their source code checked in next to them, and for those cases it would be great if we did the work to compile on the fly so that checked-in DLLs are not needed.

**Comment by dsyme** [comment]
closing old discussion (please send a PR to update .gitignore if you see this happening)
