### ISSUE TITLE
Compiler does not fold constant division expressions 

### ISSUE THREAD

**Issue by vasily-kirichenko** [Microsoft/visualfsharp#3060]
![image](https://cloud.githubusercontent.com/assets/873919/26106005/21bb373a-3a4d-11e7-9326-3c18ca7555d0.png)

**Comment by vasily-kirichenko** [comment]
![1](https://cloud.githubusercontent.com/assets/873919/26106141/a6715072-3a4d-11e7-9224-b8cdfc36a9bc.gif)

**Comment by vasily-kirichenko** [comment]
C#:

![image](https://cloud.githubusercontent.com/assets/873919/26106347/54d11c7e-3a4e-11e7-8f3f-91f98d5db26b.png)

**Comment by dsyme** [comment]
I suspect this is one very particular case - because state machine generation is done so late in the compilation pipeline (right before code generation).

**Comment by vasily-kirichenko** [comment]
@dsyme 

![image](https://cloud.githubusercontent.com/assets/873919/26110341/b6dca738-3a5a-11e7-8e05-9bd48cba1784.png)

**Comment by dsyme** [comment]
Ah yes - the optimizer doesn't fold integer division - presumably because of the zero and negative cases where you have to be carreful.  If someone would like to add the case then it goes here: https://github.com/Microsoft/visualfsharp/blob/master/src/fsharp/Optimizer.fs#L706

There will no doubt also be some other IL instructions that can be interpreted there too.

**Comment by asik** [comment]
The JIT does take care of it though, at least in simple cases:

```
let test() =
    let n = 10
    let b =
        if n + n / 2 = 15 then "a" else "b"
    Console.WriteLine b
```

```
    Console.WriteLine b
00007FF9B9FB04B0  sub         rsp,28h  
        if n + n / 2 = 15 then "a" else "b"
00007FF9B9FB04B4  mov         rcx,26990003578h  
00007FF9B9FB04BE  mov         rcx,qword ptr [rcx]  
00007FF9B9FB04C1  call        00007FF9FB77DE80  
```
