### ISSUE TITLE
A standalone compiler

### ISSUE THREAD

**Issue by nabeelomer** [Microsoft/visualfsharp#317]
When will you release a standalone compiler for f♯? I tried searching the web for a standalone compiler, but all I could find were promises.

**Comment by KevinRansom** [comment]
What do you mean standalone compiler?  The Visual F# PowerTools 3.1.2 can be installed on a computer without Visual Studio and uses as command line tools  Or from within other development tools that have F# bindings.  Although it is true I am unaware of any windows based tools.

Visual F# 3.1.2 can be downloaded and installed from [here](https://visualstudiogallery.msdn.microsoft.com/06b5edaf-9557-4987-b64e-f1722b015e86?SRC=Home)

The Visual F# 4.0 Tools (Preview) can be installed from [here:](https://github.com/Microsoft/visualfsharp/releases/tag/V4.0.Preview-03.02.2015)

I hope this helps

Kevin

**Comment by latkin** [comment]
F# Power Tools is a Visual Studio extension, I think you just meant "Visual F# Tools 3.1.2".

But yeah, the Visual F# installer will drop just the compiler/runtime/interactive if you don't have VS. That's been the case since the 3.1.1, released in January 2014.  See the section "Standalone Compiler and Runtime Install" in the [3.1.1 announcement blog](http://blogs.msdn.com/b/fsharpteam/archive/2014/01/22/announcing-visual-f-3-1-1-and-support-for-desktop-express.aspx).

**Comment by KevinRansom** [comment]
I did I wonder what I was thinking, it was early though.

**Comment by KevinRansom** [comment]
@nabeelomer did you checkout:  

[http://blogs.msdn.com/b/fsharpteam/archive/2014/01/22/announcing-visual-f-3-1-1-and-support-for-desktop-express.aspx](http://blogs.msdn.com/b/fsharpteam/archive/2014/01/22/announcing-visual-f-3-1-1-and-support-for-desktop-express.aspx).

Is there something different you had in mind?

Thanks

Kevin

**Comment by KevinRansom** [comment]
Closing this because there is nothing to be done.
