### ISSUE TITLE
type solver fails with Linq .ToDictionary(fun,fun)

### ISSUE THREAD

**Issue by 0x53A** [Microsoft/visualfsharp#3170]
I would expect the following code to work and produce a Dictionary<Guid,Guid>:

```F#
open System
open System.Linq

type GuidWrapper = GuidWrapper of Guid
    with member x.Id =
            let (GuidWrapper id) = x
            x

let id = Guid.NewGuid()
let map = [GuidWrapper id, GuidWrapper id] |> Map

map.ToDictionary((fun m -> m.Key.Id), (fun m -> m.Value.Id))
```

## Actual:

> stdin(12,49): error FS0072: Lookup on object of indeterminate type based on information prior to this program point. A type annotation may be needed prior to this program point to constrain the type of the object. This may allow the lookup to be resolved.

## Workaround:

```F#
            let toId (m:KeyValuePair<GuidWrapper,GuidWrapper>) = m.Value.Id
            map.ToDictionary((fun m -> m.Key.Id), toId)
```

## Version:
FSI from
![image](https://cloud.githubusercontent.com/assets/4236651/26686765/43652e10-46ee-11e7-9477-1506094c013c.png)

**Comment by forki** [comment]
I can repro. It's indead a bit weird that the first argument infers the type and the second doesn't

btw: I think you meant:

    with member x.Id =
            let (GuidWrapper id) = x
            id // not x

**Comment by forki** [comment]
It looks like something in typeChecker at

    and TcUnnamedMethodArg  cenv env  (lambdaPropagationInfo,tpenv) (i,j,CallerArg(argTy,mArg,isOpt,argExpr)) = 
        // Try to find the lambda propagation info for the corresponding unnamed argument at this position
        let lambdaPropagationInfoForArg = 
            [| for (unnamedInfo,_) in lambdaPropagationInfo -> 
                 if i < unnamedInfo.Length && j < unnamedInfo.[i].Length then unnamedInfo.[i].[j] else NoInfo |] 
        TcMethodArg cenv env (lambdaPropagationInfo,tpenv) (lambdaPropagationInfoForArg,CallerArg(argTy,mArg,isOpt,argExpr))


is weird. but can't see details. maybe @dsyme knows

**Comment by forki** [comment]
4f731a4 fixes it for me. but it needs REAL review by @dsyme and @kevinransom

**Comment by matthid** [comment]
I have definitely required similar not understandable workarounds for `FS0072` before.
See for example [this](https://github.com/fsprojects/Paket/blob/master/src/Paket.Core/PaketConfigFiles/DependenciesFile.fs#L319).
Maybe this is a regression?

`FS0072` is particular nasty because people probably don't report it as strictly as other errors (as you have a simple workaround). It's most of the time just not worth the trouble trying to minimalize it. Thanks @0x53A !

@forki Do you think this would fix the linked sample as well or does it have a different cause? (Or maybe the annotations are even required by the spec).

**Comment by forki** [comment]
No idea. Create a minimal repro and I'm happy to check ;-) but this needs to be small otherwise I'm totally lost in type inference.
