### ISSUE TITLE
15.3 preview 3: Solution Explorer does not show SDK nodes for .NET Core 2.0 preview 2 projects

### ISSUE THREAD

**Issue by vasily-kirichenko** [Microsoft/visualfsharp#3263]
![image](https://user-images.githubusercontent.com/873919/27578976-930178d0-5b2e-11e7-91b5-5039aeaf7b8b.png)

**Comment by dsyme** [comment]
Please reopen in https://github.com/dotnet/project-system/

**Comment by enricosada** [comment]
can repro. using `<Project Sdk="Microsoft.NET.Sdk">` projects.
And no `Dependencies` node either.

using `<Project Sdk="FSharp.NET.Sdk;Microsoft.NET.Sdk">` projects:
![image](https://user-images.githubusercontent.com/147243/27592179-20d200d8-5b54-11e7-89ac-981800ad3699.png)

**Comment by enricosada** [comment]
fix in https://github.com/Microsoft/visualfsharp/issues/3266 /cc @brettfo @KevinRansom @cartermp @Pilchie 

locally change `C:\Program Files\dotnet\sdk\2.0.0-preview2-006502\Sdks\Microsoft.NET.Sdk\build\Microsoft.NET.Sdk.FSharp.targets` to apply the PR changes

**Comment by KevinRansom** [comment]
@enricosada 

So ... the fix for this is in, however, it is not yet in master, nor is it in the preview 2.0 branch, it is in the release 2.0.0 branch.

https://github.com/dotnet/sdk/blob/release/2.0.0/src/Tasks/Microsoft.NET.Build.Tasks/build/Microsoft.NET.Sdk.FSharp.targets#L51

@cartermp will be working on updated instructions.

**Comment by cartermp** [comment]
Yes, this is now fixed.  You can get things to show up with this CLI/SDK install combo: https://github.com/dotnet/cli/tree/release/2.0.0

That is, the following should work if you install:

* 15.3 Preview 3
* The above linked CLI
