### ISSUE TITLE
VS2013 - Intellisense + Record Types

### ISSUE THREAD

**Issue by xenocons** [Microsoft/visualfsharp#337]
The problem I have experienced just now is when I am using System.Data.DataTable within a record type like so:

type checkResp = { resp : System.Data.DataTable }

The problem occurs when trying to use this record. It is unusable, intellisense reports that 'resp' is not a record field, and checkResp cannot be used within a type signature, further more hovering over the type name in Visual Studio shows that it is not processed by Intellisense. This leads us to believe there is an error in how the record type, but there is no error anywhere within the record, and strangely, it compiles in FSI fine!

I traced back the problem by trying to use DataTable() elsewhere in my code and seeing a <Note> popup saying that I need System.Xml.dll, so I added that reference and suddenly all errors went away. I believe this type of information should be surfaced at the time of defining the record type, as it turned into a 15 minute debug trip for a simple adding of a reference.

**Comment by latkin** [comment]
Adding a bit more detail on this.  If you create a blank F# console app with just below content

```fsharp
type checkResp = { resp : System.Data.DataTable }

let foo (x : checkResp) = ()
```
You initially get an error due to missing ref to `System.Data`.  Ok, fine.

![image](https://cloud.githubusercontent.com/assets/5943573/6925518/aa8d6a4c-d794-11e4-8e33-9abe775b1ba9.png)

When you add the `System.Data` reference, now you get cryptic squiggles on the type annotation, and no other obvious errors.  What's the deal??

![image](https://cloud.githubusercontent.com/assets/5943573/6925532/dc3a26ac-d794-11e4-8135-2acf81f4c875.png)

When you try a full compile, finally you see an error that indicates you need a reference to `System.Xml`

![image](https://cloud.githubusercontent.com/assets/5943573/6925567/1550c338-d795-11e4-9140-cad456ef767a.png)

Note that the file/line for that error are dummy values, which is why you don't get squiggles.  Also note that if you *do* go add the `System.Xml` reference, the compile succeeds but the resulting binary *doesn't even reference System.Xml*

This is a long-standing usability bug that's been kicking around internally since at least 2012.  IIRC the compiler is a bit too aggressive about requiring transitive closure of referenced assemblies.

It works in FSI because `System.Xml` is in the list of assemblies referenced by default in interactive sessions.
