### ISSUE TITLE
We have been asked to by a community member to change our license from Apache 2.0 to MIT

### ISSUE THREAD

**Issue by KevinRansom** [Microsoft/visualfsharp#3440]
**This issue asks for a License change:**  https://github.com/Microsoft/visualfsharp/issues/1727

We have discussed the matter with our legal types and they have approved us making this change.

For contributors:   It will mean a bulk edit of the headers, sorry folks but the headers include the licence the software is released under:  see here:   
````
// Copyright (c) Microsoft Corporation.  All Rights Reserved.  Licensed under the Apache License, Version 
2.0.  See License.txt in the project root for license information.
````

The text of the MIT licence can be found here: https://mit-license.org/

We are inclined to make the change and so we would like to give notice that we will be making the change.  Please let us know if the License change will cause difficulties for you.

I propose that we will make the change on September, 1st 2017 to allow you the time to consider this change.

Thanks

Kevin

**Comment by eriawan** [comment]
This is a good news! The MIT license is in a sense more community friendly.
Thanks @KevinRansom !

**Comment by forki** [comment]
Will it be cross-licensed so that we don't break anyone?

Am 15.08.2017 9:07 nachm. schrieb "Eriawan Kusumawardhono" <
notifications@github.com>:

This is a good news! The MIT license is in a sense more community friendly.
Thanks @KevinRansom <https://github.com/kevinransom> !

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/Microsoft/visualfsharp/issues/3440#issuecomment-322559452>,
or mute the thread

**Comment by alexandru** [comment]
Saw this mentioned on Twitter and I've put some thought in this choice for my own projects, so here are the problems:

1. for MIT there are multiple variations in the wild, as it has been used by amateurs and whenever I see an MIT license, my alarms go off for booby traps, like the [famous JSON license](http://www.json.org/license.html), which isn't OSI compliant
2. MIT does not have an explicit patents grant with a sane termination clause, Apache 2.0 does

When speaking of MIT, for me the lack of an explicit patents grant is a deal breaker.

Of course, recently the trend is to release code with BSD + Patents License (e.g. Facebook), but note those patent licenses are usually incompatible with Open Source as well. See for example the [Apache Foundation banning Facebook's libraries](https://react-etc.net/entry/apache-foundation-bans-use-of-facebook-bsd-patents-licensed-libraries-like-react-js).

Note that [the original issue](https://github.com/Microsoft/visualfsharp/issues/1727) is mentioning that:

> A more permissive license would, in some cases, prevent the scrutiny of legal departments, which can inhibit adoption

To me that doesn't make much sense, since without an explicit patents clause that *allows derivative works*, then legal departments should freak out. Also note that MIT and BSD probably have what is called an *implicit patents grant*, but AFAIK, that doesn't necessarily hold outside the US or for derivative works.

Apache 2 should be better for the legal departments, because the text is standard and was made by lawyers and you don't have to approve Apache 2 multiple times, whereas you do have to approve MIT + BSD multiple times, because usage depends on extra licenses needed, jurisdiction and threat level.

I am not a lawyer, this is just my 2 cents.

**Comment by gank-stir** [comment]
MIT +1

**Comment by et1975** [comment]
Can someone state clearly which specific problem(s) does the switch solve?
And to add to @alexandru 's point, here's one legal take on MIT license, [line by line](https://writing.kemitchell.com/2016/09/21/MIT-License-Line-by-Line.html), quoting:
>Lastly, as a result of this mishmash of legal, industry, general-intellectual-property, and general-use terms, it isn’t clear whether The MIT License includes a patent license.[...] More recent permissive open-source licenses, like Apache 2.0, address copyright, patent, and even trademark separately and specifically.

**Comment by realvictorprm** [comment]
I prefer Apache for Visual F# so I'm interested in the issues with it too.

**Comment by KevinRansom** [comment]
Following up on your question about dual licensing, here’s what our OSS attorney advised:

`We can dual license since we own the code, but it would be very unusual to dual license under the Apache and MIT licenses (I have never seen this done before – normally dual licenses are copyleft and permissive). I would urge the clients to just move to MIT.
`

Based on the above, it would preferable to change the license from Apache to MIT, assuming you’re still amenable to doing this, rather than dual licensing.

**Comment by KevinRansom** [comment]
**This issue asks for a License change: #1727**

We have discussed the matter internally and have decided to change the license from Apache 2.0 to MIT.
For contributors: This will mean a bulk edit of the headers, sorry folks but the headers include the license the software is released under: see here:

````
// Copyright (c) Microsoft Corporation.  All Rights Reserved.  Licensed under the Apache License, Version 
2.0.  See License.txt in the project root for license information.
````
The text of the MIT license can be found here: https://mit-license.org/
We plan to make the change on September 1, 2017.  Please let us know if you have any questions.

Thanks

Kevin

**Comment by forki** [comment]
thanks for asking about dual license. Yes I'm no layer and have no idea what I'm asking.
My naive assumption was: if we dual license then we don't take things away from people. We only append to the rights.

Anyway: thanks for asking. I'm sure the lawers will decide what's best here.

**Comment by 0x53A** [comment]
> but it would be very unusual to dual license under the Apache and MIT licenses

I'm no lawyer either, but unusual isn't necessarily bad. are there any actual downsides?

**Comment by realvictorprm** [comment]
@KevinRansom well if it's about F# Core I think the situation is different 🤔 

I'll go for Dual then... of course only if it's working fine.

**Comment by alexandru** [comment]
Question: will there be a [PATENTS.TXT](https://github.com/dotnet/coreclr/blob/master/PATENTS.TXT) accompanying the MIT license?

**Comment by KevinRansom** [comment]
@0x53A in terms of the law unusual is unprecedented, and unprecedented is where the risk is.  Usual is known and therefore excellent.
------------------------------------------------------------------------------------------------------------------- 
@realvictorprm the Lawyer was not enthusiastic about that change.  Each License enables our goals for the repo, and so we are happy with either.
Honestly ... I am no Lawyer, and I hate the notion that I may be making legally binding statements, and so ... our Lawyers said to me pick one and live with it.  Given that a change to MIT has come up several times in the past, with developers unable to contribute based on their legal Advice, we are okay with making this change.
-------------------------------------------------------------------------------------------------------------------
@forki is a huge and valued contributor, and so I value his opinion highly.  I am unable to go with dual, and so is MIT unworkable for you?
-------------------------------------------------------------------------------------------------------------------
@alexandru this is not relevant to the license change from Apache 2.0 to MIT for this repo.
However, I have asked the Lawyers about this ... I will let you know the outcome of that discussion.
Please open a separate discussion for that ask.

**Comment by forki** [comment]
Yes for me and our company MIT is perfectly fine. My statement was naive
assumption that law somewhat works similar to tech and adding licenses
would be non breaking ;-)

Am 28.08.2017 21:15 schrieb "Kevin Ransom (msft)" <notifications@github.com

**Comment by KevinRansom** [comment]
@forki as far as I can tell there is nothing about the law, that one can safely be naïve about.

**Comment by eriawan** [comment]
@KevinRansom 
I think the decision is clear, MIT license is acceptable. You can close this issue now, imho 🙂

**Comment by alexandru** [comment]
> @alexandru this is not relevant to the license change from Apache 2.0 to MIT for this repo. However, I have asked the Lawyers about this ... I will let you know the outcome of that discussion. Please open a separate discussion for that ask.

It's not irrelevant given that the biggest difference between Apache 2.0 and MIT is the explicit patents clause.

And if such a change happens, then the change is really not going to be from Apache 2.0 to MIT, but to MIT + PATENTS.txt.

**Comment by et1975** [comment]
> I think the decision is clear
I think the decision has already been made. In fact it looks like it has always been already made.
If the original concern is about legal scrutiny due to patents clause, MIT by itself should be a bigger issue, as already mentioned in that link I posted above.

**Comment by KevinRansom** [comment]
@et1975.  Lawyers will be advising on the request for inclusion of Patents.TXT.  I can make no prediction on where or when that will land.

Please note ... that the switch to the MIT license is at the request of the community, and the majority have expressed satisfaction with it.

**Comment by realvictorprm** [comment]
Thank you for clarifying @KevinRansom

**Comment by alexandru** [comment]
@KevinRansom
> @et1975. Lawyers will be advising on the request for inclusion of Patents.TXT. I can make no prediction on where or when that will land.

The reason for concern is that the inclusion of that PATENTS.txt, depending on the text used, can render it incompatible with GPL, Apache-2 or even the OSI definition of Open Source, which is why each license has to be independently submitted to OSI for approval.

Quoting for example straight from the [PATENTS.txt](https://github.com/dotnet/coreclr/blob/master/PATENTS.TXT) of .NET Core:

> Microsoft Corporation and its affiliates ("Microsoft") promise not to assert  any .NET Patents against you for making, using, selling, offering for sale, importing, or distributing Covered Code, as part of either a .NET Runtime or as part of any application designed to run on a .NET Runtime. 
> ...
> ".NET Runtime" means any compliant implementation in software of (a) all of the required parts of the mandatory provisions of Standard ECMA-335 – Common Language Infrastructure (CLI); and (b) if implemented, any additional functionality in Microsoft's .NET Framework

Again I am not a lawyer, but I can read English, and what this describes is that the patents grant is limited in scope, not applying to "*derivative works*" in general. Even more so, by including PATENTS.txt in the repository, the allegedly implicit patents grant of MIT / BSD no longer applies. Given that the "community" has accepted this for .NET Core, I'm guessing that it's fine, if the alternative might have been for .NET Core to not be released at all.

Again, I have no such concerns for Apache 2.0, because Apache 2.0 was reviewed in full by both OSI and the FSF. So when you switch from Apache 2.0 to MIT, you have to clearly communicate what the intent is in regards to publishing a PATENTS.txt or not and what that text will be. 

Going back to the "community" asking for this change, these are concerns from the community that aren't being addressed.

**Comment by KevinRansom** [comment]
@Alexandru, thank you for your comments, we appreciate them, and understand them.

On the internet universal agreement is not very common, I am satisfied, based on this thread and other threads discussing this, that the consensus of the regular contributors and consumers of this repository are satisfied with the license change as proposed.

**Comment by fommil** [comment]
The expat license (or MIT as you're calling it) is a permissive free/libre software license that is compatible with the GPL. We'll done for releasing your software under an FSF approved license!

However, let me summarise what this means for those who may have gotten a bad impression from Apache: the MIT license only gives you access to the Software and you must agree to pay royalties to Microsoft for any patents that they lay claim to.

Back when this was Apache 2, Microsoft were giving you the rights to the patents too. And if you sued Microsoft then you lost the rights to the patents and had to pay Microsoft to use them. i.e. you'd be in the situation you're in now.

I find this quite funny. I suspect the Microsoft lawyers had a right old giggle to themselves. I recommend that Virtusstream get a lawyer who knows what they are talking about and this whole thing could have been avoided. But then, I wouldn't have been given such a funny thread the read this morning, so thank you!

**Comment by alexandru** [comment]
While I agree with what @fommil said above, I believe some extra extra clarifications are needed for this claim:

> if you sued Microsoft then you lost the rights to the patents and had to pay Microsoft to use them. i.e. you'd be in the situation you're in now

The Apache 2.0 license is actually healthy in this regard. And I quote:

> If You institute patent litigation against any entity (including a cross-claim or counterclaim in a lawsuit) alleging that the Work or a Contribution incorporated within the Work constitutes direct or contributory patent infringement, then any patent licenses granted to You under this License for that Work shall terminate as of the date such litigation is filed

So the license says termination happens if you sue Microsoft for _their contributions to the project_, however you can still sue Microsoft for unrelated projects and the patents grant of this license still holds.

This is actually the criticism of Facebook's [PATENTS](https://github.com/facebook/react/blob/master/PATENTS) grant for React, in which they say:

> The license granted here under will terminate, automatically and without notice, if you (or any of your subsidiaries, corporate affiliates or agents) initiate directly or indirectly, or take a direct financial interest in, any Patent Assertion: (i) against Facebook or any of its subsidiaries or corporate affiliates ...

So basically if you sue Facebook for *anything*, they terminate the patents grant they gave you for React. Compare this text with the text from Apache 2.0. The Apache 2.0 license carefully puts that grant and its revocation only in the context of "`The Work`" being licensed.

Also, I see that this project is now licensed under MIT, but with no PATENTS file. In my mind that's actually better, but another problem is that any PATENTS file can always be added later to the repository and estoppel will no longer apply, the MIT license not protecting users in any way.

Personally I don't understand why some people prefer this over Apache 2.0, but then again it's their choice and I've added my thoughts here only for other people to get informed about what they are getting into, as the choice has been made anyway.

Cheers,
