### ISSUE TITLE
How to handle mutable highlights for less obvious cases

### ISSUE THREAD

**Issue by cartermp** [Microsoft/visualfsharp#3455]
See this tweet by @eiriktsarpalis: https://twitter.com/eiriktsarpalis/status/898207938241810432

The binding to an array is immutable, its contents are mutable.  Not highlighting the binding is correct insofar as the binding itself cannot be changed in-place, but because you can modify the values inside of the array, it can also "feel" inconsistent with the highlighting that mutable bindings get.

Arrays aren't the only case where this can seem a bit inconsistent.  You can have mutable properties on objects in F#:

```fsharp
type C() =
    member val P = 0 with get, set

let c = C()
c <- C() // Will not compile
c.P <- 1 // Will compile just fine
```

One could make the case that `P` should be highlighted as mutable in this case.  But should every value in an array be highlighted like that as well?  What would that look like?

Generally speaking, it's not clear to me how cases like this should be highlighted.  @dsyme Makes the point that consistency matters the most here, and I agree with that.  I also think that we should consider any change with configuration in mind, and if something is on or off by default.  Would love to hear the thoughts of others here.

**Comment by OnurGumus** [comment]
I am a little confused. By adding a getter and setter you make your object mutable. What immutable is your reference c, that it cannot point to another object. Try same example by making Type C as struct by decorating attribute. Then it will not allow you.

**Comment by cartermp** [comment]
@OnurGumus That is exactly what I'm saying here.  It's not clear what the behavior needs to be.  The object changes, but the binding does not.  When you refer to the binding `c`, it may have changed at some earlier point.  Is it valid to highlight `c` in the same way that mutable bindings do?  If not, is it valid to highlight it differently, or the "parts" of it that can change (e.g., `P`)?

**Comment by chadunit** [comment]
At minimum I think the `P` in your `c.P` should be highlighted, and mutable `[0]` indexers should be too (F# arrays, BCL dictionaries, etc.) -- if not the whole indexer then at least the square bracket characters. Really, any nested item that can appear to the immediate left of `<-` I guess.

Additionally it would be nice to have some semantic indication that the top-level object is a mutable object if any of its nested contents anywhere are mutable. After all, it's the whole object that is not "safe" over subsequent usages due to mutability of its contents, and when talking about immutability in general I am usually more interested in mutability of the contents of a data structure rather than of the binding. Maybe a new similar color to represent "content-mutable" but not "binding-mutable" in this scenario?

**Comment by cartermp** [comment]
Closing old discussion, as this didn't seem to arrive to a place of definitive action
