### ISSUE TITLE
--standalone fails if type names are duplicated

### ISSUE THREAD

**Issue by 0x53A** [Microsoft/visualfsharp#3473]
Take this repo and run dotnet build: https://github.com/0x53A/fsc-standalone-test

Result:

```
FSC : error FS2014: A problem occurred writing the binary 'C:\source\fsc-standalone-test\obj\Debug\net461\fsc-standalone-test.exe': duplicate entry 'System.AssemblyVersionInformation' in type index table [C:\source\fsc-standalone-test\fsc-standalone-test.fsproj]
```

If I remove ``` <OtherFlags>--standalone</OtherFlags> ``` from the project file, it builds.

The issue is that both this project and a reference (probably Argu) define ``System.AssemblyVersionInformation`` (which is autogenerated by FAKE: https://github.com/fsharp/FAKE/issues/1637)

**Comment by dsyme** [comment]
@0x53A As things stand, this is by design.  ``--standalone`` doesn't disambiguate type names and requires no duplicates among the assemblies being referenced.  If you want to workaround this, you will need to run some kind of disamibuating tool that does IL-to-IL conversion, or use a different static linker such as ILMerge (though I'm not sure that handles it either)

We could adjust the error message to say that in the case of failed static linking

**Comment by 0x53A** [comment]
Yes, that's probably sane. You _could_ hack around it by renaming conflicting types, but as you say, that's probably out of scope for fsc itself and better suited to a dedicated merge tool.

**Comment by matthid** [comment]
Should we deprecate `--standalone` technically it really is no problem to have multiple assemblies with the same type. Technically (as far as I know) it is not even a problem to have the same named type in the same assembly (by using multiple "modules"). So this really is a major drawback.
