### ISSUE TITLE
MSBuild reference resolver lacks .NET 4.6.2+ frameworks

### ISSUE THREAD

**Issue by vasily-kirichenko** [Microsoft/visualfsharp#3484]
I don't know if this is a problem, but it seems we don't handle .NET 4.6.2, 4.7.x here and in the entire file:

https://github.com/Microsoft/visualfsharp/blob/master/src/fsharp/MSBuildReferenceResolver.fs#L86-L107

**Comment by KevinRansom** [comment]
That durned resolver is a pain.  However, we build 4.6.2 and 4.7 fine.  This file is interesting and a complete PITA because it supports magic references in the language service and FSI (I.e. not guided by a project file).  When we finally have package management in FSI I hope and pray that this kind of magic goes away.

**Comment by vasily-kirichenko** [comment]
OK :)

**Comment by KevinRansom** [comment]
Every time I see it, I die a little.  There is that whole reshaped_msbuild code in the coreclr build that I really want to throw away.
