### ISSUE TITLE
Array shows as list in tooltips

### ISSUE THREAD

**Issue by rojepp** [Microsoft/visualfsharp#364]
I've always considered this a bug, so I'm reporting it here. 
I encounter this frequently, hover over a variable to see if it's an array or list, and argh:

![screenshot 2015-04-14 00 31 30](https://cloud.githubusercontent.com/assets/445888/7126890/af3c51bc-e23d-11e4-994d-82ee3ad4eba7.png)

Basically I have to send it to FSI to get a glimpse of the type, which is not always tractable.

**Comment by forki** [comment]
It shows `int []`, that's correct, right?

**Comment by rojepp** [comment]
`int []` looks like a list, you can't tell that it's an array.

**Comment by forki** [comment]
IIRC that's  default .NET notation, what would you change?

**Comment by isaacabraham** [comment]
I get the issue but for lists doesn't it says e.g. Int list?

**Comment by rojepp** [comment]
Yes, it says `int list` for lists. `int array` would be fine when it is one-dimensional, just to remove the confusion?

**Comment by forki** [comment]
I have to admit I have exactly this discussion in every introduction workshop that I give. 
I wonder what negative effects this change could bring.

**Comment by dsyme** [comment]
Technically speaking, nothing would break to change that to ``int array`` or ``array<int>``.

But yes, ``int[]`` is the normalized presentation used for array types as of F# 2.0, and because that's the normalized textual presentation then we would recommend that form in source code too..  

As an aside, some would say that everyone should write ``list<int>``, ``option<int>``, ``array<int>``. (Clearly the ``C<x,y,z>`` syntax is here to stay, and beginners do find the existence of the alternative post-fix syntax ``x list`` confusing).  I'm actually surprised there hasn't been a user voice item suggesting this - it seems that advanced users really do like postfix form for seq, list and array.

**Comment by forki** [comment]
I never heard someone complain about postfix notation. But the `[| |]` array comprehension vs. `[]` type name is apparently confusing for beginners.

**Comment by isaacabraham** [comment]
@dsyme I actually do sometimes find myself wondering about that sort of thing. You can do the same for option as well etc. - sometimes I like to think of it as "int option" and "int list" but if you come from the C#/VB background it can be disconcerting.

Slightly off topic but I wonder about the same for function signatures - beginners find the ```'a 'b 'c``` syntax for generics confusing as opposed to ```T1 T2 T3``` as well as the whole ```(int -> string -> int)``` syntax for function signatures.

**Comment by latkin** [comment]
I agree the display form is kind of confusing at times, especially for beginners.

Changing to `int array` or `array<int>` would require some care for multi-dimensional arrays.  How would you differentiate between true multi-dimensional arrays (`int [,]`) and jagged arrays (`int [][]`)?  `int array array` would seemingly map to `int [][]`.  For `int[,]` maybe `int array2D` or `array2D<int>`?

At least the current solution keep the tooltips in sync with real signatures, which certainly aren't going to change. e.g. `let arrLen (a : 't[]) = a.Length`

**Comment by dsyme** [comment]
This is a design issue for http://fslang.uservoice.com
