### ISSUE TITLE
With dotnet core sdk F# projects, Visual Studio's NuGet package manager is confused about the version of FSharp.Core

### ISSUE THREAD

**Issue by dhwed** [Microsoft/visualfsharp#3656]
To reproduce:
```
mkdir NuGetBug
cd NuGetBug
dotnet new console -lang F#
```

A NuGetBug.fsproj is created:
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Program.fs" />
  </ItemGroup>

</Project>

```

Open NuGetBug.fsproj in Visual Studio, right click the project, and 'Manage NuGet Packages...'

![image](https://user-images.githubusercontent.com/10184638/30929304-b1329756-a383-11e7-85f1-ef8af2b027dd.png)

The Solution explorer shows that FSharp.Core 4.2.3 is installed, but the NuGet Package Manager UI shows the installed version of FSharp.Core as 4.2.0.

If you click the Update button, a `PackageReference` is added to the NuGetBug.fsproj:
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Program.fs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Update="FSharp.Core" Version="4.2.3" />
  </ItemGroup>

</Project>
```
But, the NuGet Package Manager UI still displays the installed version of FSharp.Core as 4.2.0.

By the way, I have been unable to figure out where the magic is that causes the FSharp.Core NuGet package to be implicitly added to all fsproj files - does anybody know how this is implemented?

**Comment by dsyme** [comment]
> By the way, I have been unable to figure out where the magic is that causes the FSharp.Core NuGet package to be implicitly added to all fsproj files - does anybody know how this is implemented?

@KevinRansom Is there any way we can just make this less magic? I know it was discussed but I can't remember the reason why we do it?

**Comment by KevinRansom** [comment]
@dsyme 
It's not magic, this way there is no need for the majority of projects to explicitly reference FSharp.Core, or System.ValueTuple.dll

**To disable implicit FSharp.Core reference**:
````
<DisableImplicitFSharpCoreReference>true</DisableImplicitFSharpCoreReference>
````
**To specify a specific version of the FSharp.Core nuget package**:
````
<FSharpCoreImplicitPackageVersion>4.2.3</FSharpCoreImplicitPackageVersion>
````
**Similarly for System.ValueTuple.dll**:
````
<DisableImplicitFSharpCoreReference>true</DisableImplicitFSharpCoreReference>
````

**Comment by dsyme** [comment]
@KevinRansom But why don't we want to make this explicit?  I mean, is it to make project files smaller?  Or easier to shift to newer versions of F#?

**Comment by dhwed** [comment]
@KevinRansom Thanks, I can use those to fix my issue.

And you meant:

```xml
<DisableImplicitSystemValueTupleReference>true</DisableImplicitSystemValueTupleReference>
```

Out of curiosity, where is the FSharpCoreImplicitPackageVersion originally defined?

**Comment by KevinRansom** [comment]
Simpler project files.  And it doesn't make upgrading F# core harder.

Effectively the project file only needs to express the developer required customizations.  And since all F# projects will need to specify an F# core it is not itself a customization.

Implicit FSharp.Core selection is specified as:
````
<FSharpCoreImplicitPackageVersion>4.2.*</FSharpCoreImplicitPackageVersion>
````
so we will automatically upgrade the project to the latest FSharp.Core, that matches the F# compiler.
This way the project says as little as the developer desires for upgrading FSharp.Core

We will not upgrade to 4.3.* until we upgrade the compiler anyway, ... reasons "versioning"

**Comment by KevinRansom** [comment]
@dhwed Copy and past error :-)

It's in: Microsoft.FSharp.NetSdk.targets

https://github.com/Microsoft/visualfsharp/blob/780b6c4ad1e13b3bc60dd2b1589220bf5fc4f601/src/fsharp/FSharp.Build/Microsoft.FSharp.NetSdk.targets#L72

**Comment by dhwed** [comment]
@KevinRansom Thanks again.

My understanding is that .NET Framework 4.7 includes `System.ValueTuple` in `mscorlib`, so I would not expect `_FrameworkNeedsValueTupleReference` to be true with a `TargetFramework` of `net47`.

Is this a mistake, or does .NET 4.7 actually need a `System.ValueTuple` NuGet package?

&nbsp;

Also, it looks like the real problem here is that the NuGet Package Manager UI does not understand wildcard versions.  If I put this into a csproj:
```xml
<PackageReference Include="FSharp.Core" Version="4.2.*" />
```
then I get the same problem where the Package Manager UI shows the installed version as 4.2.0 instead of the actual installed version of 4.2.3.

I'm not sure where to report this issue.

**Comment by KevinRansom** [comment]
@dsyme there was a bug there.  They put the type in mscorlib, but didn't include the shim, or add the reference to the framework.  I believe 4.7.1 is the one where everything is fixed.  Regardless ... most folk are going to be downlevel for quite a while.  Hence the _FrameworkNeedsAValueTuple test.

**Comment by forki** [comment]
/cc @matthid

Am 27.09.2017 22:17 schrieb "Kevin Ransom (msft)" <notifications@github.com

**Comment by rrelyea** [comment]
@patobeltran - this is the issue you are looking to address (how floating versions show up in NuGet PM UI, right?)

**Comment by matthid** [comment]
Yes this issue seems to have been hijacked because of the last by the way sentence. the reported issue seems to be just a ui bug in how to report floating versions.

I'd assume C# has the same problem?
This is actually quite funny because what is the "installed" version? Nobody knows as it could change between showing in ui and running the application?

**Comment by PatoBeltran** [comment]
Yes, this issue is the same as https://github.com/NuGet/Home/issues/3788 ... NuGet team is currently working on fixing it. [Here](https://github.com/NuGet/Home/wiki/%5BSpec%5D-NuGet-Build-Integrated-Project-handling-of-floating-versions-and-ranges-in-Visual-Studio-Client) is a link to the spec that gives more info on the proposed solution

**Comment by dhwed** [comment]
Thanks everyone; I'm going to go ahead and close this issue since the root cause is already being tracked by the NuGet team.
