### ISSUE TITLE
F# program doesn't continue linearly

### ISSUE THREAD

**Issue by haf** [Microsoft/visualfsharp#367]
When the record-update syntax is called with a null value as the record, the program jumps to a random location in the code-base.

Example:

``` fsharp
type B =
 { y : string }
type A =
  { x : B }
let test () : A =
  let n = Unchecked.defaultOf<obj>
  { n with x = { y = "test" } }
test ()
```

This should probably throw a NullReferenceException?

I get the null from C# interop; but since I'm deserialising to a Record it 'should never be null' according to the static typing rules, but the C# lib (Newtonsoft) deserialises to null if it can't deserialise the record.

**Comment by latkin** [comment]
I do not see anything resembling "jumps to a random point in the codebase" -- can you provide a complete, self-contained repro that illustrates this?

Since `x` is the only field on the type, and you are updating its value, the compiled form of the `test` function actually never even looks at the input.

```fsharp
let doUpdate n = { n with x = { y = "test" } }
```
Compiles simply to
```csharp
public static A test(A n)
{
	return new A(new B("test"));
}
```
If your record type has multiple properties, then you indeed get a nullref, as expected.

```fsharp
type C = { w : string; z : int }
let doUpdate n = { n with z = 42 }
doUpdate Unchecked.defaultof<C>  // NullReferenceException
```

Current behavior seems reasonable to me.  I guess one could opine that copy and update should *always* throw if in the input is null, but it seems odd to check for null of an input that is never otherwise used.

**Comment by haf** [comment]
I tried reproducing it in the small, but wasn't able. I can let someone from your team have access if you want?

**Comment by latkin** [comment]
You can email private info to fsbugs@microsoft.com if needed

**Comment by haf** [comment]
Let's close this to celebrate F# 4.0 and write it down to a mono bug. =) This was one of the strangest bugs I've seen though :)
