### ISSUE TITLE
[From 15.5 preview test day] - Newly-added file is not recognized

### ISSUE THREAD

**Issue by cartermp** [Microsoft/visualfsharp#3677]
Give this test script: https://gist.github.com/cartermp/b19e80506b6a51c54cb9006fcd6eb07b

Step 13 fails because IntelliSense does not pick up the file.  This was working when I tested out #3564, and afterwards when I reviewed the script, so something may have gone awry between after we merged and when we tested a build of 15.5 internally.

**Comment by KevinRansom** [comment]
That issue is because of:
https://github.com/Microsoft/visualfsharp/blob/master/vsintegration/src/FSharp.Editor/LanguageService/LanguageService.fs#L418

There was a huge performance degrade for legacy projects with the updated event.  However, that is now fixed and the updated event is in the Project References PR.

https://github.com/KevinRansom/visualfsharp/blob/d887a3b7feb998ccbda584bf458793d47cf7e87d/vsintegration/src/FSharp.Editor/LanguageService/LanguageService.fs#L378

Kevin

**Comment by cartermp** [comment]
@KevinRansom awesome.  Sounds great.  #3653.

**Comment by cartermp** [comment]
Fixed by #3777
