### ISSUE TITLE
Inconsistency in Constructor tooltips

### ISSUE THREAD

**Issue by tldrlol** [Microsoft/visualfsharp#3715]
Windows 10, vanilla VS 2017 install.

Given this (non-compiling code):

```fsharp
type Foo() =
  new(_: int) = Foo ()
  new(_: string) = Foo ()

System.String
Foo
```

There is an inconsistency between the tooltips generated over the `System.String` line, and the one for `Foo`.

To illustrate:

![String c'tor tooltip](https://i.imgur.com/aruoQsM.png)

![Foo c'tor tooltip](https://i.imgur.com/o61fe1f.png)

**Comment by ReedCopsey** [comment]
Given that we can now treat ctor as a function (ie: you can pipe into a ctor, etc), it seems like String should definitely be  `new : char [] -> String` and similar in order to make sense from a discoverability POV.

**Comment by matthid** [comment]
Just to add, this would probably fix some open bugs in [FSharp.Formatting](https://github.com/fsprojects/FSharp.Formatting) as well

**Comment by dsyme** [comment]
Yes, I agree

**Comment by dsyme** [comment]
I presume this issue is around here https://github.com/Microsoft/visualfsharp/blob/44fa027b308681a1b78a089e44fa1ab35ff77b41/src/fsharp/NicePrint.fs#L1302 

I think we should use this instead https://github.com/Microsoft/visualfsharp/blob/44fa027b308681a1b78a089e44fa1ab35ff77b41/src/fsharp/MethodCalls.fs#L589

**Comment by vasily-kirichenko** [comment]
Fixed in https://github.com/Microsoft/visualfsharp/pull/3754

**Comment by dsyme** [comment]
@vasily-kirichenko Thanks for fixing this!
