### ISSUE TITLE
Fsharp preview 20171024 lose File resort and cause errors

### ISSUE THREAD

**Issue by Huqin-China** [Microsoft/visualfsharp#3817]
Already know that f# modules read by a sorted file order. A+B file,B file can open fileA's module,but fileA can not find fileB module.

Its been solved before use a alt+arrow to sort files manually,but the lastest version remove this function,so errors shows again.

#### Repro steps

Provide the steps required to reproduce the problem

1. Create a net standard project,target .net standard1.6

2. Add a codefile ,name B,some basic module

3.Add another coldfile, name A

These files will be auto sorted by filename ,so B will under A even B is created first.

#### Expected behavior

A can open a module in B

#### Actual behavior

according to the file order, A can not open modules in B, but B can read modules in A

#### Known workarounds

No, since the alt+arrow be removed

**Comment by cartermp** [comment]
@Huqin-China This actually has nothing to do with the visual order in the UI, but rather the project file:

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="A.fs" />
    <Compile Include="B.fs" />
    <Compile Include="Library.fs" />
  </ItemGroup>

</Project>
```

For .NET Core/.NET Standard projects, when you add a new file the `<Compile>` tag gets added to the **top** of the list of files.  This is why `A.fs` cannot use anything defined in `B.fs`.  You'll need to manually change the ordering in the project file.  This is actually quite easy now:

![edit-project-file](https://user-images.githubusercontent.com/6309070/32011464-b99f587e-b969-11e7-9ea8-15c0e2ecdf59.PNG)

No need to unload the project in VS.  The two issues you mention:

1. Compile order not shown in the UI
2. Lack of right-click gestures to move them around in the UI

Are tracked with these issues in the project system repository:

https://github.com/dotnet/project-system/issues/2793
https://github.com/dotnet/project-system/issues/2887

I'll close this for now, since the experience gaps are going to come from work in the project system repository rather than this one.

**Comment by Huqin-China** [comment]
@cartermp ,tks.
Hope the projectsystem team  solve the compile problems soon without adjust the project file.
I used to the F# file order feature.This solution, UI order is different from compile order(what u see is not what u get). 
thanks again.
