### ISSUE TITLE
NetSDK projects when loading stop colourising

### ISSUE THREAD

**Issue by KevinRansom** [Microsoft/visualfsharp#3824]
The work around is to delete the .vs folder from alongside the project.

Sometimes somehow the underlying project system decides not to notify us with the command line options.

Still working on why!

**Comment by cartermp** [comment]
I don't quite understand the issue.  What is the scenario here?

**Comment by dhwed** [comment]
Similarly to #3695, this only happens when a file from the project was open the last time you closed VS.  If you close all files and then re-open VS, the tooling works properly.  I expect this is why deleting the .vs folder causes things to work, since that's where the list of previously open files is stored.

Also, if you close VS, delete the bin and obj folders, and then open VS again, the tooling works properly even if files in the NetSDK project were already open.
