### ISSUE TITLE
FCS nightly NuGet feed

### ISSUE THREAD

**Issue by Krzysztof-Cieslak** [Microsoft/visualfsharp#3871]
As we now have enabled FCS build on the CI server it would be cool to have some easy and manageable way of using it (at least nicer than manual downloading it ;-) ).

I wonder if it would be possible to create NuGet feed (on MyGet) with FCS nightly build just like we have feed for VF#.

**Comment by KevinRansom** [comment]
@Krzysztof-Cieslak 

Thanks for this suggestion.  It is a great suggestion, however, the way to think about __fcs__ as it is currently positioned in the visual F# tools repo is that it is a set of acceptance tests, to make sure that updates that we make to the F# compiler don't break __fcs__.  Or at least ... if it does then we can be forewarned, and deal with the break early.

We don't currently want to ship any binaries from these acceptance tests because ... they are currently an incidental part of this testing process and not anything that we wish to be committed to in the long term.

Taking a dependence on __fcs__ packages that are not from the FCS repo, may be a bit too aggressive, because it is not clear when they will be officially published.

I don't know what we want the long term future of the FSharp.CompilerService to look like, I do have opinions though.  Should it remain a separate repo or merges with this one, or something else entirely?

We should probably have a discussion about that.

/cc @brettfo, @dsyme, @cartermp

**Comment by forki** [comment]
Didn't @cartermp write in one of the other issues that VF# VS addin should
be put on top of FCS?

Am 02.11.2017 21:27 schrieb "Kevin Ransom (msft)" <notifications@github.com

**Comment by Krzysztof-Cieslak** [comment]
> We don't currently want to ship any binaries from these acceptance tests because [...] Taking a dependence on fcs packages that are not from the FCS repo, may be a bit too aggressive, because it is not clear when they will be officially published.

I understand what you try to say...  but that's not stopping anyone from using those binaries - they are easily buildable from source, and they are available on the CI server as release artefacts.  FWIW, Ionide is using a custom build of FCS for the last couple of weeks ;-) But the process is tedious for us - downloading NuGet packages manually and using them as a local source is not something I like to do. With the feed, I can normally use Paket to ensure versioning (assuming that we would add build number or current date to the version of the package to ensure SemVer).

> I don't know what we want the long term future of the FSharp.CompilerService to look like, I do have opinions though. Should it remain a separate repo or merges with this one, or something else entirely? We should probably have a discussion about that.

I think it's really interesting discussion (and not only about FCS, but also VS plugin vs compiler vs FCS) but I think it's rather an orthogonal issue to the problem of having NuGet feed.

**Comment by KevinRansom** [comment]
@Krzysztof-Cieslak, 
if a developer takes the source and builds it and makes a dll or a nuget package dll, that's just open source software ... more power to them.  

If a developer takes binaries provided by Microsoft, then there are obligations that may be assumed by them and us, unless we spell them out in the form of a license, which will necessarily be very restrictive.
  
At this time ... we don't know that we want to assume those obligations, for what is essentially a convenience.  We may do so at some point, and then it won't be a convenience instead it will be a necessary part of product development, but right now we are comfortable using that code as an acceptance test to ensure we don't break FCS.  Going further than that will require a lot more discussion.

@forki that is an issue ... until it happens or it is incorporated in a plan, it is "wish" and it certainly doesn't address the many currently internal fsharp.compiler APIs that are made into public ones by the FSC build.

**Comment by Krzysztof-Cieslak** [comment]
Fair enough, thanks for explaining :-)
