### ISSUE TITLE
"Only functions may be marked 'inline' " error for function binding

### ISSUE THREAD

**Issue by auduchinok** [Microsoft/visualfsharp#4045]
```fsharp
module M

let inline isNotNull = isNull >> not
```
```
Program.fs(3, 12): [FS0832] Only functions may be marked 'inline'
```

**Comment by vasily-kirichenko** [comment]
Yeah, point free stuff are not functions.

**Comment by dsyme** [comment]
Yes, this is by design.  In particular there's no way to tell if the r.h.s. has an effect or not without knowing the implementation of ``>>`` or special-casing that combinator.  And ``inline`` is intended to be semantically neutral (except for the cases where it allows extra tailcalls or allows extra genericity)

**Comment by OlegAlexander** [comment]
Hi @auduchinok, not sure if you're still interested 5 years later, but my workaround for this error is:

```console
> let inline isNotNull x = (isNull >> not) x;;
val inline isNotNull: x: 'a -> bool when 'a: null
```

@dsyme, would it make sense to clarify the error message to something like: "Only functions with one or more parameters may be marked 'inline'"?
