### ISSUE TITLE
Support for "fsc" and "fsi" in the .NET CLI

### ISSUE THREAD

**Issue by cartermp** [Microsoft/visualfsharp#4060]
~~Global commands will be a new feature in the .NET Core CLI.  This will allow us to install `fsc` and `fsi` as commands you can invoke from the command line.~~

**Comment by cartermp** [comment]
#3994

**Comment by cartermp** [comment]
Due to security considerations we will not be using global tools. Instead, we will have reserved commands distributed with the .NET CLI for `fsc` and `fsi`.

**Comment by cartermp** [comment]
The `dotnet` commands have been added in the .NET SDK that will map to VS 2019 GA.

**Comment by WalternativE** [comment]
Just out of curiosity and because I can't find documentation that would contradict the last comment: the `fsc` command has not been implemented, right? Just the `fsi` one - at least I wouldn't be able to use `fsc` in a current .NET Core 3.1.x project.

**Comment by WalternativE** [comment]
Thanks for the clarification! 🙇‍♂️

**Comment by KevinRansom** [comment]
@WalternativE, @cartermp, 

we are unlikely to support dotnet fsc ever.  fsc.exe is supported via msbuild FSharp projects, .fsproj.

Manually gathering the assembly references is nightmarish and msbuild has all of the rules to do that for all tfms that can be built and includes first class nuget support.  Without using msbuild a command line build would be really … really hard to type.

For fsi, we could relatively conveniently build a bunch of logic into it for the reference searches, that is because we absolutely know what the target framework is for the build.

Anyway that is why we didn't add support for a dotnet fsc command.  It would be relatively trivial to add the command, but it would be more or less unusable and so we didn't add the command.

I hope this helps

Kevin
