### ISSUE TITLE
Using a nonexistant namespace should be a compiler error or warning

### ISSUE THREAD

**Issue by vasily-kirichenko** [Microsoft/visualfsharp#4103]
![image](https://user-images.githubusercontent.com/873919/33805019-57d7e1c4-ddc2-11e7-8496-97e2ba9635df.png)

**Comment by saul** [comment]
What happens if you fix/comment out the other errors in the file?

**Comment by cartermp** [comment]
This seems to be the same as in C#.
![same-cs](https://user-images.githubusercontent.com/6309070/33848798-a84c6264-de63-11e7-92a7-47d6e93b9998.PNG)

An F# program which has this `open` statement and nothing else will also compile if you run it, so I'm not entirely convinced that there should be an error here.

**Comment by vasily-kirichenko** [comment]
I tend to consider this as a bug - even though it’s not used, the very fact that we open unexisting namespace should result with an error.

**Comment by cartermp** [comment]
I agree that the behavior isn't in the spirit of F#, and that trying to use a namespace that literally doesn't exist shouldn't really compile.  But ultimately I think we'd have to change compiler behavior to not compile on this, or at least add a warning.  Then tooling could be updated.

**Comment by cartermp** [comment]
I updated the issue and tagged this appropriately

**Comment by cartermp** [comment]
cc @dsyme  - there is a denied uservoice suggestion here: https://github.com/fsharp/fslang-suggestions/issues/439

But I think this issue is a bit different than the closed suggestion.  While it's true that the namespace System.Drawing is unused, it literally _cannot_ be used because the System.Drawing .dll is not referenced.

**Comment by dsyme** [comment]
``System.dll`` has a single type in ``System.Drawing``:

![image](https://user-images.githubusercontent.com/7204669/34003964-9aa58400-e0ee-11e7-92f0-f0b0a7ea29ec.png)

**Comment by dsyme** [comment]
Oh, that type is private, so in theory it's definitely reasonable to argue that we could give an error.  

However I don't believe we want to fix this - because we don't want to check the accessibility of every type in a namespace just because we open the namespace.  So I will still close this as by-design

**Comment by vasily-kirichenko** [comment]
If it’s just a corner case, I’m agree it’s not a problem.
