### ISSUE TITLE
PackageReferenece nuget option 

### ISSUE THREAD

**Issue by noelmcgrath** [Microsoft/visualfsharp#4152]
nuget PackageReferenece  option not working for f# library 4.7 framework 

![image](https://user-images.githubusercontent.com/671790/34270938-04179624-e682-11e7-8662-b2cbd8cc93a2.png)

Steps

1.  Create f# library .net 4.7
2. Have nuget packages options set, see image

2. Add nuget package e.g. Newtonsoft.Json

#### Expected behavior

Reference would be added to fsproj. No packages.config file created

#### Actual behavior

packages.config file created

#### Related information 
Works for .Net Standard library

**Comment by cartermp** [comment]
I don't think we have plans to add this support into our legacy project system now that we have good support on the new one. My advice is to convert an existing .NET Framework application to use the new project file format. This works as expected in that situation.

**Comment by noelmcgrath** [comment]
thanks for reply
Can you explain what you mean by:
My advice is to convert an existing .NET Framework application to use the new project file format

**Comment by cartermp** [comment]
The easiest thing to do would be the following:

Assuming that you have a .NET Framework-based library targeting .NET Framework 4.6.1...

1. Create a new .NET Standard library for F#
2. Right-click the project node and select "Edit project file"
3. Change `<TargetFramework>` from `netstandard2.0` to `net461`
4. Save the project file
5. Copy source code from your existing library into this new one
6. Edit the project file as-needed
7. (This is a temporary bug) reload the new project so that the file ordering is shown in Solution Explorer

Now all things pacakgereference will work.

In the long term (that is, 2018), we're going to aim for _all_ F# project types to use this new project file format.

**Comment by noelmcgrath** [comment]
ok thanks, can u link to where this "new project file format." is documented

**Comment by cartermp** [comment]
This is the closest we have right now: https://docs.microsoft.com/en-us/dotnet/core/tools/csproj

Note that although it says "csproj", everything applies for fsproj as well.

This blog post is also an excellent migration guide: http://www.natemcmaster.com/blog/2017/03/09/vs2015-to-vs2017-upgrade/

**Comment by noelmcgrath** [comment]
ok thanks for links
