### ISSUE TITLE
QuickAction on unfinished let block is unhelpful

### ISSUE THREAD

**Issue by asik** [Microsoft/visualfsharp#4224]
Actual error is FS0588 "The block following this 'let' is unfinished, but the QuickAction offers to fix warning FS1182 "The value is unused" instead (a warning that does not show up anywhere). This is confusing and does not help the user at all.

![image](https://user-images.githubusercontent.com/1631157/35158633-b3a0e87c-fd05-11e7-827c-a3f7b4788d22.png)

### Expected
No Quick Action unless there's a useful fix that makes sense in this scenario

VS 2017 15.5.4
Visual F# Tools 15.4.1.18011902

**Comment by cartermp** [comment]
Unfortunately, I don't think there's a way to be able to differentiate between:

1. This value is unused; you should consider prefixing or renaming it so it's more clear
2. This value is unused, but that's okay because we know you're not done yet

C# does similar things you'd likely consider unhelpful with quick actions, such as endlessly cycling between "turn into expression-bodied member" and "make this a full method body" on a one-line method. The hypothesis is that even though this isn't helpful in that instance, it is helpful in other cases and does make the editor feel more "alive".

In the next VS update, the unused value analyzer will be capable of being toggled on/off, which should make this better for people who get annoyed by it. But I don't think we can proceed any other way without some kind of machine learning component which estimates when someone is unfinished with the body of the function.

**Comment by asik** [comment]
@cartermp I was thinking you could differentiate based on whether the let blocked is unfinished. The F# compiler seems to already make that distinction, since it doesn't issue the warning.

**Comment by cartermp** [comment]
Not sure if this is something we could actually do in the language service. The analyzer is fairly straightforward:

1. Collect declaration symbols.
2. Collect usage symbols.
3. Find the declarations which aren't used.

What you're asking for is to effectively do this for any entity which has a return value if and only if a return value exists.

Here's an example of where it could get tricky:

```fsharp
let f xs =
    let (a, b) = someOtherFunction
    xs |> Array.filter (fun x -> x > a) |>
```

I haven't used `b` - do I intend to use it somewhere, or did I just type `(a, b)` out of habit? Impossible to tell. I still think it would be helpful to see that it's unused and offer to ignore it via an underscore, especially if I realized midway through typing something that I wasn't going to use it.

The F# compiler can make the distinction you mention because it doesn't have to "work" on constantly broken and incomplete code. For example, if I compile with `--warnon:1182` on this:

```fsharp
let f x =
    let y = x + 1
```
I don't get the warning on `y` because the code doesn't compile. Only until it compiles do I see a warning about `y` being unused.

But for IDE tooling, I'd certainly expect to get IntelliSense and other features in the middle of that unfinished function body, including analysis to see if things have been unused.
