### ISSUE TITLE
What is the plan for "VS Code" support

### ISSUE THREAD

**Issue by forki** [Microsoft/visualfsharp#428]
I wonder if we can start an open discussion about how [VS Code will support F#](https://visualstudio.uservoice.com/forums/293070-visual-studio-code/suggestions/7756026-f-great-support). There is a lot of discussion going on on Twitter, but nobody knows anything. We don't even know if this is the right place to talk about it and who are the people to ask. 

So will this be an open source project and can it cooperate with projects like 
https://github.com/fsprojects/FSharp.Atom?

**Comment by dsyme** [comment]
This feels a bit off-topic for this repro, since it's neither VF# Tools (except by association), nor core F# compiler/library.  VSCode needs to have a place to discuss these things.

**Comment by forki** [comment]
yes that's a bit what I mean. I think it's important to have discussion about it, but I don't know where.

**Comment by Krzysztof-Cieslak** [comment]
Well, as far as I know only place to discuss VS Code features is their user voice ( here is F# idea - https://visualstudio.uservoice.com/forums/293070-visual-studio-code/suggestions/7756026-f-great-support). However, I am not sure user voice is good medium for such discussion.

**Comment by dsyme** [comment]
I think you just have to wait/agitate/...

**Comment by KevinRansom** [comment]
This will be one of the places where F# support for VS Code is handled.  This project is the Visual F# Tools project and for sure VS Code falls under that banner.  We don't have anything to share right now because we are heads down trying to ship F# 4.0 and VS 2015.

I'm sorry we can't be definitive right now, but shipping F# 4.0 is front and center for us.

Thanks
Kevin

**Comment by Krzysztof-Cieslak** [comment]
@KevinRansom, Can You even confirm if there are plans for official (driven by Visual F# Team) support of F# in VS Code or it will need to be comunity driven plugin (like in case of Atom / Vim / Emacs)? I would like to notice that F# idea in uservoice (https://visualstudio.uservoice.com/forums/293070-visual-studio-code/suggestions/7756026-f-great-support) is not marked as "Planned" or even "Under Review" by VS Code Team.

**Comment by TonyAbell** [comment]
What does is say that Haxe support as more votes then F#.  

https://visualstudio.uservoice.com/forums/293070-visual-studio-code/suggestions/7756341-haxe-support

I think it is great that a non .net languages will have an audience in VS Code. 

Should there be an effort to get F# folks to vote on the user voice?

**Comment by enricosada** [comment]
First, really good job!
You two have done two migrations (closed codedrop -> codeplex -> github) that's a lots of work.
And i know there is only you @KevinRansom and @laktin, so thanks!

Some things i liked:

- Detailed comments, feedbacks and review to pull requests/issues
- it's lots easier to develop now than months ago ( codeplex ok, but also better experience on clone -> run debug ).
- Twitter
- Patience :smile:
- Actively search for bug on stackoverflow, twitter

I'll add references where possible, but i dont want to discuss here the single issues, these are examples.

I'll add the really good issue dotnet/coreclr/issues#744 , duplicated in corefx dotnet/corefx#1445 and dotnet/roslyn#2156
 , because some problems/suggestions apply here too.

### Create a vision for this repo

Right or wrong, i see you @latkin and @KevinRansom like roslyn/corefx teams, the goto persons to ask questions about MS F# tech future.
There are some open questions not addressed about future like netcore, asp.net vNext, universal app, collaboration with open source projects.
Add long term goals and create big issues, and enable contributors to work with you on that.
An example: the vs project system. It's really in bad shape, is really behind pytools/nodetools, not speaking about c# or vb. 
Some are not missing features anymore, are bugs (folders/templates/show all files).
We can slowly fix each bug. Or we can discuss how to improve, maybe importing pytools/roslyn code or rewriting stuff ( the vb project pages as example: i want to add the exe icon picker? too annoying write f# + c# + vb , so zero contributions ).
Maybe some refactoring/changes/mistake are needed but in the long run, is going to be better. 

### Roadmap and open source development

There are lot of components in this repo, you have limited bandwidth, that's ok, ask help from contributors, but not only about bugfix. 
Develop the next version in the open, create issues (coreclr/aspnetvNext/universal/vs project system/etc) and engage contributors for help. No time to work with asp.net? i think there are someone who want to do that.
People like to work on different areas, you can create multiple teams, and coord the efforts ( like the coreclr porting teams, external contributors with review from ms and help when stuck/questions ).
I understand is more work, but you'll have more hands. Otherwise is only you two + @dsyme and sporadic pr for bugfix/feature.
If you think about what the @VisualFSharpPowerTools team has done, that's amazing.

### Continue to make it easier to contribute.

We cannot use your workflow, is different.
The initial work is done (build + smoke test with app-veyour.bat, open solution -> debug -> vs extension ready, easier build etc)
The repo source is big ( fsc/fsi/vs extension/language service/core libraries/type providers ) + test suite for each components.
Some examples:
- there isn't an official public build server (appveyour is only smoke tests, not complete test suite Debug+Release). I can submit a pr, but i'd like to see the tests suite's results because i cannot run the whole suite each time (Debug/Release/Profiles), that's the ci server job, can you help me with that?
- This repo is also the home of the fsc/fsi/core library, not only the vs extension. Make it easier to contribute from osx/unix folks, pull from openfsharp repo, not push only ( the build script, use an xplat tests runner ). Obv openfsharp repo is for packaging but visualfsharp is the source code. Ideally i can code, test and submit a new pr of fsc without Windows (ci server/review). also useful for future xplat coreclr.

### Make the code easier to accept changes, to fear a bit less the regressions

This repo contains lots of things. Is like the full .net fw distribution ( .net bcl = core library, msbuild, vs ext, compiler )
Trying to split when possibile (roslyn+corefx vs fsc+corelibrary ) and use nuget workflow is good ( like corefx ).
Less stuff, lower barrier to contribution ( less code to read and faster test suite ).
An example are the type providers (wsdl/odata). I know is more work to create another repo and migrate code (i cant help with ms internal work, but i can help with code inside this repo) but medium/long term is easier to fix/evolve/document.
Easier to review and add a feature/bugfix, because is easier to release a bugfix as nuget instead of an official/outofband vs release. Easier also to fix mistakes (i dont want buggy code, but happen. have a sane workflow + fast distribution helps alot).

### Do not stop contribution flow

I know that from now until vs2015 release there is no more new work here, no new development, only some little bugfix (there are no more issues i can fix with this lockdown, too large diff, too much refactoring needed, too much time required to debug things i know less, like compiler ).
I think this may drive people away, is already difficult start to contribute, more when a fix is probably going to be accepted but not merged. 
Or a refactoring is waiting because of lockdown, so next refactoring is not going to happen ( i dont refactor stale source code ).
Git branch helps, i know branches are not free because needs yours supervision/review.
Better skip one or two bugfix but create an active development story. I don't work full time on this, fix a bug **and** do that with a small diff is hard, lot of time is needed (see #391 , my third attempt, but is incomplete because the complete fix is too large for vs2015 ).
I can do an easier fix for next version, but i need a branch to do that. If i don't send an easier pr this weekend, that's one weekend lost. 

### Don't do skip answers or communications

Some things are open questions (netcore/vNext/universal ) i understand you can't answer now but if you can't, just say so.
No answers, "we can't speak about it now" or marketing lingo is worst.

Examples 

- coreclr #263 , 2 months ago: priority issue, see roadmap (where?) and closed.
- asp.net vNext #264 , 2 months ago: same, closed.
- coreclr #387 , 1 month ago: no answer, that's worst because told by @visualfsharp via twitter to open the issue	

Another good idea i'd like is the weekly corefx or aspnet team recorded meetings, that help us be in the loop

**Comment by forki** [comment]
@enricosada wrong issue? =>> https://github.com/Microsoft/visualfsharp/issues/451

**Comment by enricosada** [comment]
thx @forki , moved the comment

**Comment by KevinRansom** [comment]
@Krzysztof-Cieslak 

you can be quite sure that VS-Code will support fsharp dynamically, it already does in a static way.  And that we will do what is necessary to make it work, either here or in collaboration with some other community project.  I can't commit how we will do it, or what it will look like because frustratingly for all of us, we are still nailing down, activities, priorities and resources.  

The environment in which we operate has changed immensely over the last year what with:
* The recent expansion of .NET into cross platform
* Roslyn has expanded the minimum acceptable set of acceptable editor services immensely, and F# has a bunch of catching up to do
* The open source initiative
* The announcement of VScode
* The integration of Xamarin into VS
* ASP v.next looming on the horizon
* {MBrace} being the coolest thing in the cloud
* Azure being hotness that suits the F# code first approach to development

there are many things we could be doing for the next release, and we are working through which of them we are actually going to do.  

The reason it is taking so long, is that: 
1: we are winding down on our VS 2015 release, clearing up ship stopping bugs and the like,
2: we are winding down on our VS 2015 release, clearing up ship stopping bugs and the like,
3: we are winding down on our VS 2015 release, clearing up ship stopping bugs and the like
Finally: 
99999: There are many stake holders with so many options that it is hard to get definitive about which is the highest value set of activities for us to pursue.

You have my sympathies, I know you want to know what's next, and which of the new stuff will be jumping all over to make great.  When I know, you will know.

This is not intended as a tease, but we consider porting the compiler and running great on the CORECLR to be __table stakes__, It can therefore a commitment from us that we will work to make that work in the near term.

Kevin

**Comment by forki** [comment]
https://twitter.com/k_cieslak/status/608753036836663296 <- shows you should really make it a community project ;-)

**Comment by dsyme** [comment]
Closing this since [Ionide](http://ionide.io/) provides VSCode support for F#, thanks to all the hard work of @Krzysztof-Cieslak and the many contributors.  And I note that even the VSCode user voice marks this issue as "closed" and links to Ionide :)
