### ISSUE TITLE
F# assemblies display obsolete linker version with dumpbin /headers

### ISSUE THREAD

**Issue by SteveGilham** [Microsoft/visualfsharp#4291]
Running `dumpbin /headers' on an F# assembly generated by VS 2017 (v15.5.5) shows linker version 8.0 (VS2005); this is true for both .net framework and .net core.
```
OPTIONAL HEADER VALUES
             10B magic # (PE32)
            8.00 linker version
```
whereas corresponding C# ~(and native C/C++)~ binaries show linker version 48.00 -- which means that F# artifacts show up when looking for code built with outdated tool chains (and hence possible intrinsic vulnerabilities).

#### Repro steps

Provide the steps required to reproduce the problem

1. build any assembly

2. run  `dumpbin /headers'

#### Expected behavior

Linkers and their declared versions should be reasonably consistent across the whole tool-set release -- they might not be exactly the same but they should be close.

#### Actual behavior

As above

#### Known workarounds

With a private fork of Mono.Cecil I can rewrite the linker version bytes to contain to anything I choose.  How truthful that might be is an entirely different question.

#### Related information 

Provide any related information 

* Operating system -- Windows 10
* Branch
* .NET Runtime, CoreCLR or Mono Version 
* Editing Tools (e.g. Visual Studio Version)  -- vs 15.5.5
* Links to F# RFCs or entries on https://github.com/fsharp/fslang-suggestions
* Links to performance testing scripts
* Indications of severity -- this was picked up in a security oriented scan.

**Comment by dsyme** [comment]
@SteveGilham Should definitely be fixed. I'm not sure where the data is written but I suspect it's somewhere around here?

https://github.com/Microsoft/visualfsharp/blob/master/src/absil/ilwrite.fs#L3969

**Comment by SteveGilham** [comment]
Thanks for the pointer into the codebase -- saved me a lot of hunting

This seems to be the place where the linker version is written into the optional header
https://github.com/Microsoft/visualfsharp/blob/master/src/absil/ilwrite.fs#L3929
having been computed at
https://github.com/Microsoft/visualfsharp/blob/master/src/absil/ilwrite.fs#L628

The comments in both locations seem to suggest that the values have been arrived at by some reverse engineering and treated as "magic numbers -- better not touch". 

This issue turns out to be a bigger can of worms than I'd expected.  I'm used to the 0x30 version for C# from https://github.com/dotnet/roslyn/blob/5c3dff5ba9c7905b8b194378acca7f0b288e366e/src/Compilers/CSharp/Portable/Compilation/CSharpCompilation.cs#L2387 but delving into the rest of the Roslyn codebase I find to my surprise that https://github.com/dotnet/roslyn/blob/e2fda399f9bc77b662f9b7f07898fbfd7c6a741e/src/Compilers/VisualBasic/Portable/Compilation/VisualBasicCompilation.vb#L2131 gives &H50 for the Roslyn VB compiler (decimal 80).

Meanwhile as native C++ executable from the latest Visual Studio has linker version 14.12 as does a C++/CLI assembly.

So much for consistency.

What number to choose for F# becomes a little trickier in this case, beyond suggesting that it should still be adjusted to be distinct from the native linker range, and perhaps based on the compiler version -- say 0x41 for Visual F# 4.1, placing it between the C# and VB numbers.

**Comment by KevinRansom** [comment]
@dsyme, @SteveGilham.

I don't believe any purpose would be served by changing the value.   The value is not indicative of anything  ... beyond, some number had to go there.  For sure if any tool was using the value to identify some specific linker behavior that behavior would be missing from our P.E. file anyway, after all it is merely a bunch of IL.

I would imagine to be useful, any such tool that checked this flag, would also need to look for the CLR header, and say .... ohhhh!!! an il assembly ... let's move on.

So I'm not inclined to change the value ... especially to some other arbitrary value thats somewhere between C# and VB.

Does that make sense?

Kevin

**Comment by SteveGilham** [comment]
As it stands, a tool that checks the value given by `dumpbin` does indeed have to check whether or not the file is an assembly, as the 8.00 value makes the provenance of the file ambiguous.  Even if there is no consistency in claimed versions between languages, removing the ambiguity would provide some benefit.

**Comment by KevinRansom** [comment]
Can you explain?  And what is the consistency you would like to see?

**Comment by dsyme** [comment]
Steve can you give us an actual example of a tool that triggers this:

> "when looking for code built with outdated tool chains (and hence possible intrinsic vulnerabilities)."

If we change then using the same value as C# seems best.

**Comment by KevinRansom** [comment]
But Don …

no linker was used … and so the value of the field indicates nothing about possible intrinsic vulnerabilities addressed by various versions of the Linker.  At best the tool would flag us as a false positive for a particular issue … hmm you are using version 8.0 of the linker and that didn’t have xyz mitigations in it.  However, the analysis is a naïve one, since PE files are not always created with a linker.  The analysis would need to recognize the CLR Header, and then analyze the binary based on that.

Regardless, changing this value to a different one is a risk since we don’t know how someone may have code that depends on this value.  In order to do due diligence I have chatted with Roslyn Compiler team, and the C++ team, who own the linker,  no one thought it was a good idea to change this to a different arbitrary value, given that no linker was involved in the creation of the P.E, it was suggested that probably we should have originally written out 0.0 as the value, but no one thought that was a particularly beneficial approach now.

Kevin

**Comment by SteveGilham** [comment]
For the decade up to 2015, the displayed linker version -- however purely cosmetic in managed assemblies -- for C# and VB matched the Visual Studio version (and the actual native linker version).  This was more than sufficient time for the value to become (ab)used as a shorthand for determining the toolchain used to produce the binaries and entrenched in processes.

Assemblies presenting a linker version of 8.00, by giving the appearance of having been built with an obsolete tool-chain, have been a pain-point for me, when audits are performed that work upon that appearance alone, and the blacklist all binaries showing versions below 12 as "insecure" based on known issues in the native linker.  How prevalent this exact style of check is, I am not sure, but I have observed a general attitude of "even the false positives need fixing" from corporate security organizations over a wide range of issues.

Exactly because there is no linker involved, as Kevin rightly points out, and the number is thus purely decorative, I worked around this by patching the version to an acceptable value.  It would have been nice not to have had to do so.

With the value of that optional header field now scattered, post Roslyn, there is no obvious right answer to the question "what should F# binaries show?", but 8.00 -- or indeed any value likely to be overtaken by the native linker in the near future -- is clearly not an optimal choice.

**Comment by KevinRansom** [comment]
Steve,

If you want to know the version of the toolchain that built an F# assembly use the ProductVersion and File Version attribute.  

This will exactly describe the version of the F# Compiler because when we build to ship we build the product with a proto compiler built from that same source code.  The binary is produced entirely from code shipped with the compiler.

From VS2017.6 to be released shortly this attribute has the exact prodcuct version of the F# compiler, including the githash of the source.

If your goal is to figure out which version of VS that version of the compiler was shipped with ... well ... I guess a web page could contain that information.  Although we also ship the compiler in a seperate msbuild sku, and within the dotnet cli and as a nuget package.

Regardles, the coincidence of linker version number does not offer any usefull analytical information, and apparently even the C# and VB compilers have stopped offering that guide.


Kevin

**Comment by cartermp** [comment]
Closing out old discussion. @KevinRansom's guidance here is accurate, and with the commit hash that we'll have the commit hash of the source for the shipped version. Hopefully this is adequate traceability.
