### ISSUE TITLE
Typo in CompiledNameAttribute

### ISSUE THREAD

**Issue by bert2** [Microsoft/visualfsharp#4297]
Just a little typo I found by chance. It says "Min-u-mumElement" instead of "Min-i-mumElement".

https://github.com/Microsoft/visualfsharp/blob/5d88640df70e27d5116f9c32fa10cce489a34836/src/fsharp/FSharp.Core/set.fs#L816

**Comment by KevinRansom** [comment]
@bert2 

oops .... looking at blame (https://github.com/Microsoft/visualfsharp/blame/5d88640df70e27d5116f9c32fa10cce489a34836/src/fsharp/FSharp.Core/set.fs#L816), it would seem as if it has been wrong, since the beginning of time.  So changing it would be a breaking change.

The CompiledName is the actual name used in the assembly, and so would be used when invoked from a C# assembly.

I think we will have to live with it.  We could make an additional correctly named API, I'm not sure how high a priority that would.

Kevin

**Comment by cartermp** [comment]
@dsyme thoughts on this?

> I think we will have to live with it. We could make an additional correctly named API, I'm not sure how high a priority that would.

I wouldn't place that as a high priority, even though the spelling error is embarrassing.
