### ISSUE TITLE
Suggestion: restrict "private" for items in namespaces to mean "private to the namespace declaration group"

### ISSUE THREAD

**Issue by KevinRansom** [Microsoft/visualfsharp#43]
Opened at CodePlex by ovatsus

This should give a compile time error, but doesn't:
[File1.fs]
```FSHARP
namespace MyApp

module private Module1 =
    let f x = x
```
[Program.fs]
```fsharp
namespace MyApp

module Module2 =
    open Module1
    let y = f 1

    do
        printfn "%O" y
```
When evaluating in fsx the error is correctly issued

**Comment by latkin** [comment]
@dsyme - related to https://visualfsharp.codeplex.com/workitem/29 and/or https://github.com/Microsoft/visualfsharp/issues/27 ?

**Comment by dsyme** [comment]
No.

**Comment by dsyme** [comment]
For F# 4.0 (and F# 3.x) it seems best to resolve this as by design.

In F#, "private" means "private to the enclosing module or type". However, the meaning of "private" for a construct in a namespace needs clarification.  

The F# Language Spec for F# 2.x-4.0 will be adjusted to clarify that "private" on a type or module in a namespace declaration group NDG for namespace N means "accessible from NDG, or any namespace declaration group in the same assembly contributing to the same namespace N or a sub-namespace of N."   This means that a construct is accessible from other namespace declaration groups in other files within that assembly which contribute to that namespace.

I understand that this is a weaker form of "private" than simply "private to the encloding namespace declaration group" or "private to the file". However, it is as F# 2.0-3.x has always implemented.  Any adjustment to restrict this is surprisingly non-trivial since we must give a warning for existing uses, rather than an error. This needs a lot of care beyond what I'd like to see for F# 4.0 at this stage.

(The only other modification that looks reasonable here for F# 4.0 would be to simply give a warning to recommend that people use "internal" rather than "private" for types and modules in namespaces)

**Comment by dsyme** [comment]
Tracked by the user voice request
