### ISSUE TITLE
Missing mutable colorization in Visual Studio 

### ISSUE THREAD

**Issue by wanton7** [Microsoft/visualfsharp#4303]
Currently Visual Studio shows mutable variables and mutation in different color (yellow in dark theme) like in code below foo is colored yellow
![mutable-color](https://user-images.githubusercontent.com/1009930/35727226-1626233a-0810-11e8-85ff-cb61832facb7.png)

But lst.[0] <- is not colorized
![mutable-not-colored](https://user-images.githubusercontent.com/1009930/35727287-49f83720-0810-11e8-99e8-44bfdc9114e9.png)

Same problem here
![mutable-not-colored2](https://user-images.githubusercontent.com/1009930/35727707-b6bd2bd0-0811-11e8-89f9-1d5f0c2375a7.png)

Would it be possible to also colorize known mutable methods? like example. System.Collections.Generic.List's Add, Remove Sort
This might be a huge list or different types and methods, so i'm not sure if it's feasible.

#### Related information 

Provide any related information 

* Operating system
Windows 10 64bit
* .NET Runtime, CoreCLR or Mono Version
CoreCLR 2.1.4
* Editing Tools (e.g. Visual Studio Version)
Visual Studio 2017 15.5.6
* Indications of severity
Not severe

**Comment by cartermp** [comment]
This is a bit tricky. The colorizer is for mutable _bindings_, which means that it's technically fulfilling its role here. Although the contents of the array `foo3` can change, `foo3` itself will always refer to that array.

Colorizing all things whose contents could be mutated is tricky. That would require all classes which hold values that can change to be colored in this manner as well - this is tricky because you're now also differentiating between objects whose contents can change and objects whose contents cannot. This was discussed briefly in #3455, but it wasn't clear what the takeaway was.

**Comment by wanton7** [comment]
Ok then working as intended. Thanks for info! I'll close this.
