### ISSUE TITLE
What's the master branch?

### ISSUE THREAD

**Issue by dsyme** [Microsoft/visualfsharp#4346]
@KevinRansom @brettfo The master branch has diverged from dev15.6 and dev15.7.  

* In master, [FSCoreVersion is 4.4.1.0](https://github.com/Microsoft/visualfsharp/blob/master/src/FSharpSource.Settings.targets#L41)
* In [dev 15.6](https://github.com/Microsoft/visualfsharp/blob/dev15.6/src/FSharpSource.Settings.targets#L23) and [dev 15.7](https://github.com/Microsoft/visualfsharp/blob/dev15.7/src/FSharpSource.Settings.targets#L23), FSCoreVersion is 4.4.3.0

What's the role of the master branch please?

Note, if ``master`` = "able to be built, installed and used in dev15.5, i.e. latest default public VS installation" then I understand what's going on and am ok with this, though it confused me for a bit.

Thanks

**Comment by cartermp** [comment]
> Note, if master = "able to be built, installed and used in dev15.5, i.e. latest default public VS installation" then I understand what's going on and am ok with this, though it confused me for a bit.

@KevinRansom and @brettfo can confirm, but this has been our working understanding ever since RTW

**Comment by dsyme** [comment]
OK, thanks, understood.  It's strange because I think of master as logically ahead of dev15.6 and dev15.7, but in some ways it isn't (e.g. it still produces FSharp.Core 4.4.1.0)

**Comment by brettfo** [comment]
Correct.  `master` is meant to always work with public RTM releases.

`dev15.x` branches contain changes specific to those releases.  As soon as 15.6 publicly ships then `dev15.6` will merge back into `master`.

**Comment by dsyme** [comment]
@forki See https://github.com/Microsoft/visualfsharp/pull/4351

**Comment by KevinRansom** [comment]
Master is the normal working branch.  
15.6 is the release branch for VS Next.  
15.7 is the release branch for VS Next + 1

A release branch is normally created off of Master at the start of the release.  The release branch will be kept up to date with master until Ask mode occurs, Ask mode is when Brett, Me and Will have extra paperwork in order to make changes to the release branch.

Work is normally checked into master, and cherry picked into the release branch

__Except:__
There is some versioning changes specific to the next release.  E.g. We are picking up new Roslyn or VS dependencies.  Or there is a bug fix required in the release branch.

**Comment by dsyme** [comment]
> Work is normally checked into master, and cherry picked into the release branch
> There is some versioning changes specific to the next release. E.g. We are picking up new Roslyn or VS dependencies. Or there is a bug fix required in the release branch.

I think what surprised me is that some feature work is in dev15.x, including publishing new versions of FSharp.Core. It makes total sense I just needed to do a double take to work it out.
