### ISSUE TITLE
Update on RTM closedown

### ISSUE THREAD

**Issue by latkin** [Microsoft/visualfsharp#459]
We continue to get closer to VS 2015/F# 4.0 RTM.  Starting today, all further changes for F# need explicit approval by the managed languages team directors before we can merge them.  Over the coming weeks, the bar will get steadily higher regarding what they will approve.

That means PR merge rates will be much lower, starting now.  Just giving everyone a heads up.

##### What will be accepted?
Bugs tagged as part of the [VS 2015 milestone](https://github.com/Microsoft/visualfsharp/milestones/VS%202015) have a decent shot of being approved if a fix arrives soon, and if the required changes are not too invasive.

##### What else can I do to help?
We should have a new preview build out soon, please take it for a spin and make sure all of your projects still build and run as expected.  Please continue dogfooding VS 2015 RC, as well.  Just use F# 4.0 and/or VS 2015 in whatever capacity you can!

##### What happens to PRs that won't make it for VS 2015?
Once we get a bit further ahead on stuff from https://github.com/Microsoft/visualfsharp/issues/386, we will open up a vNext branch and start merging PRs into there. Bear with us in the meantime.

##### This post needs more cats

I agree! 

![image](https://cloud.githubusercontent.com/assets/5943573/7717651/be425480-fe59-11e4-81ff-bbf795818991.png)

**Comment by enricosada** [comment]
Can we use a single branch ( like `master` ) for development instead of create a new branch each time (`vNext`, `fsharp4`, `netcore`, etc)?
At rc/beta/lockdown time a new release branch (`v4.1`, `fsharp4.1`) can be created, used for release process and hotfix ( `4.1.1`, `4.1.2`, etc ). meanwhile work on `master` ( `4.2` ) can continue.

We dont need another branch to update/merge and using `master` for development is pretty common (less friction to contribution) instead of `vNext`. Is ok also `vNext` but as a stable development branch.
Easier also to align with openfsharp repo or build infrastructure or performance history ( like the amazing http://speed.pypy.org/ ).

I dont understand the current flow, the `fsharp4` branch is going to be merged inside `master` after rtm? because currently both `master` and `fsharp4` accepts pr, but i dont think a new version will ever be created from `master`

if a v3.1 branch is needed, it is easy to branch the current master ( a release branch, like `v3.1` or `fsharp3.1` )

**Comment by latkin** [comment]
Will update with branching plans this week
