### ISSUE TITLE
Same document opened twice in 15.6

### ISSUE THREAD

**Issue by jaredpar** [Microsoft/visualfsharp#4626]
In Dev15.6 in F# I'm getting in cases where the same document gets opened multiple times. Once that happens editing in one file + saving turns into an external edit in the other document resulting in a reload prompt. Took me a while to realize what was happening here because I had a lot of tabs open and hence the duplicate open wasn't obvious. 

I'm unsure of the exact steps to produce this but definitely seems to be related to F12 / Go to definition. Once I get into that state any F12 to a type in the same file will cause the active document to be opened in a new tab.

**Comment by cartermp** [comment]
@jaredpar I haven't seen this in VF# (mixed classic/.NET SDK) with Go to Def and lots of tabs. Have you seen this recently? Also cc @ricksladkey if he's seen it in VsVim recently.

**Comment by ricksladkey** [comment]
@cartermp Indeed, I have seen this and, of course, it happens when a zillion tabs are open and so you are not quite convinced it's not just your imagination. I heavily use a mix of "Find in Files" with a lot of F8 and `Ctrl+Comma` "Go To All" and F12 "Go To Definition". I can't say that it's happened in the last week or so, but it I think it happened several times before that. I will keep my eye out for it and see if we can create a repro, or at least catch the problem in the wild.

**Comment by ricksladkey** [comment]
I should add that I am now on 15.7.6 and don't know exactly when I upgraded (probably when I got a notification), and so it may be that the problem doesn't occur with 15.7 and my recollection of the problem was with some 15.6 version.

**Comment by jaredpar** [comment]
I haven't seen this in a while.

**Comment by cartermp** [comment]
Okay. I'll close this for now, but if you see it ping here and I'll re-open. There was some work in 15.7 and the forthcoming 15.8 that may have affected this.
