### ISSUE TITLE
Types/names not visible in tooltip in latest nightly

### ISSUE THREAD

**Issue by cmeeren** [Microsoft/visualfsharp#4695]
Using the latest nightly (15.6.20180406.3), types/names are frequently not visible in mouseover tooltips (it seems to work occasionally, but mostly not).

![image](https://user-images.githubusercontent.com/7766733/38444149-82f5ffb6-39ee-11e8-9a35-b3f71be7ae14.png)

![image](https://user-images.githubusercontent.com/7766733/38444220-c3388d96-39ee-11e8-97a6-ce2488968c55.png)

![image](https://user-images.githubusercontent.com/7766733/38444283-026ecce6-39ef-11e8-8f4e-676d1cf1f649.png)

This one seems to work fine:

![image](https://user-images.githubusercontent.com/7766733/38444354-263c595e-39ef-11e8-820a-5d7e6fb99b09.png)

**Comment by majocha** [comment]
I have this, too. It's because resources are being loaded from the older .dll

Some ugly workaround:
Go to the installation directory of the released version e.g. `Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\CommonExtensions\Microsoft\FSharp`

and rename the file `FSharp.UIResources.dll` so it doesn't get picked up by the nightly.

**Comment by cmeeren** [comment]
@majocha, your workaround didn't work. It just made VS crash.

**Comment by majocha** [comment]
OK, I have a proper fix. Will make a PR later today.
