### ISSUE TITLE
FSI: Incorrect execution of side effects in Seq functions

### ISSUE THREAD

**Issue by moonPtr** [Microsoft/visualfsharp#4733]
Sorry for the vague / inaccurate title, I don't really know how to abstractly describe what's happening here:
![cmd_2018-04-18_18-15-11](https://user-images.githubusercontent.com/32428601/38944863-40b47c86-4335-11e8-8cda-76613d045eef.png)

#### Repro steps

Run the following in FSI:
```fs
open System

Seq.initInfinite (ignore >> Console.ReadLine)
|> Seq.takeWhile (not << String.IsNullOrEmpty)
|> Seq.iter      (printfn "STRING: %s")
```

#### Expected behavior

All strings should be printed at once when `Seq.takeWhile` returns.

#### Actual behavior

Strings are printed immediately after `Console.ReadLine` returns in `Seq.takeWhile`. 

#### Known workarounds

Passing the result of `Seq.takeWhile` to `Seq.toList` and then using `List.iter`
![cmd_2018-04-18_18-22-42](https://user-images.githubusercontent.com/32428601/38944971-87cc905e-4335-11e8-8f6d-647852565d4f.png)

#### Related information 

using Microsoft (R) F# Interactive version 10.1.0 for F# 4.1 on Windows 10

**Comment by isaacabraham** [comment]
This is expected behaviour. Sequences thread messages through a pipeline, and `takeWhile` doesn't "wait" until the stopping condition is hit. The second example is as you would expect, since it forces the sequence to complete and converts to a list, at which point it prints them all out.

I don't think that this is a bug per se.

**Comment by moonPtr** [comment]
Ah, I was under the misconception that elements are requested/evaluated in `takeWhile` and not in ìter`
My bad, closing!
