### ISSUE TITLE
Make warning FS1190 an error and fix <^T> parser bug

### ISSUE THREAD

**Issue by moonPtr** [Microsoft/visualfsharp#4794]
In regards to §5 of the [spec](http://fsharp.org/specs/language-spec/4.0/FSharpSpec-4.0-latest.pdf), Warning FS1190 should be an error (especially when lightweight syntax is disabled), not a warning.

("In a type instantiation, the type name and the opening angle bracket must be syntactically adjacent with no intervening whitespace [...]")

Furthermore, a statically resolved type variable currently requires a space between it and the opening angle bracket, otherwise it fails to compile with FS0010: Unexpected infix operator in pattern

![code_2018-04-27_14-26-31](https://user-images.githubusercontent.com/32428601/39362517-04314052-4a27-11e8-908b-b438b5556400.png)

**Comment by abelbraaksma** [comment]
> the type name and the opening angle bracket must be syntactically adjacent with no intervening whitespace

I understand that it only applies to the opening angle bracket. Are you suggesting a syntax change? Because some things currently aren't even possible without whitespace within the brackets:

    array<^int>  //syntax error
    array< ^int>  //legal

I believe the first line to be a parser bug, but it also means that there's a lot of code out there that would be affected if we change these rules to be stricter. 

And besides, in more complex type definitions (they can get very long, especially static types) it's just wonderful to be able to put them on multiple lines.

**Comment by moonPtr** [comment]
Updated issue to be more concrete, hopefully.

**Comment by dsyme** [comment]
Please make this a language suggestion at http://github.com/fsharp/fslang-suggestions, thanks
