### ISSUE TITLE
Stepping in computation expressions steps out on let!/do!

### ISSUE THREAD

**Issue by cmeeren** [Microsoft/visualfsharp#4835]
When stepping through computation expressions, the debugger seems to step out on `let!`/`do!` expressions. This is easily reproduced with `async` expressions, but I have also observed it for custom CEs. Setting breakpoints or using Run To Line works correctly, but Step Over or Step Into seems to break out on `let!`/`do!`.

Step Over:

![step-over](https://user-images.githubusercontent.com/7766733/39655245-e066f9c8-4ff8-11e8-9b7c-c4ef2d2c5d6d.gif)

Step Into (note also that it doesn't break out to `main` like Step Over does above - is this another bug?):

![step-into](https://user-images.githubusercontent.com/7766733/39655244-e03ff3d2-4ff8-11e8-9ec5-730d13aef44d.gif)

Run To Line:

![run-to-line](https://user-images.githubusercontent.com/7766733/39655246-e0858a5a-4ff8-11e8-8b73-6ab97ead760a.gif)

Breakpoints:

![breakpoints](https://user-images.githubusercontent.com/7766733/39655247-e0a663f6-4ff8-11e8-90a1-6b45a57b7d1b.gif)

#### Repro steps

[ReproSolution.zip](https://github.com/Microsoft/visualfsharp/files/1976027/ReproSolution.zip)

#### Expected behavior

Step Over and Step Into should not step out of the expression after breaking on a `let!` or `do!`.

#### Actual behavior

Step Over and Step Into steps out of the expression after breaking on a `let!` or `do!`.

Furthermore, note in the Breakpoints example above that it breaks twice on the `let!` and `do!` lines. Is this another bug?

#### Known workarounds

None that I know of.

#### Related information 

It's been like this for a long time, but this report was made using VS 15.6.4 and Visual F# nightly 15.6.20180504.1.

**Comment by abelbraaksma** [comment]
I'm not sure, but isn't this related to the asynchronous nature of, well, `async`? Does it exhibit the same behavior if you use, say, `seq`, `query` or a `result` builder?

**Comment by abelbraaksma** [comment]
> In this seq expression it doesn't break at all, even if I set breakpoints on every line in the expression:

That's correct, because you don't evaluate the `seq` expression, you only instantiate the builder, so it indeed never hits _inside_ the builder. Try it with `Seq.toList` or `Seq.toArray` or `Seq.iter` to force evaluation.

> though it breaks twice in a row on every do! line

I suspect that's because there's two function calls, one for `Ok()` and one for evaluating `do!` (which calls `ResultFrom` iirc).

You may see different lines hit when you run it in Release mode, as some lines will be optimized away.

> except that Step Into now jumps out after do! Async.Sleep.

My guess is here that during the sleep, the other methods have already been evaluated. But I agree, when you break, you should have 'break on all threads", which should block further processing. But since this is `async`, when the processor hits the break on your sleep-line, the other statements may have already been processed and only that line is still waiting completion. I'd assume that a similar thing can happen in C#, but the unwrapping of the code is quite different there so it may be hard to compare.

To fix that, you can place a breakpoint inside the builder itself, upon creation. I sometimes simply create a second builder-creation (let's say `asyncResult2`) for this purpose. Or place a breakpoint on the exact lines you want to step through (but you figured that out already in the OP).

All that doesn't mean it cannot be improved. I'm just trying to figure out what causes this behavior, and to me, while a frustrating debugging experience, it isn't completely unexpected.

**Comment by cmeeren** [comment]
> That's correct, because you don't evaluate the seq expression, you only instantiate the builder, so it indeed never hits inside the builder. Try it with Seq.toList or Seq.toArray or Seq.iter to force evaluation.

Ah, sorry for the brain fart. Using `Seq.toList`, Step Over and Step Into seem to work correctly (and identically) for the code I posted.

**Comment by abelbraaksma** [comment]
@cmeeren, happens to me all the time ;). I've updated my post while you were typing, maybe the code sample is useful :).

**Comment by cmeeren** [comment]
Thanks for the note. I like your solution and will keep it in mind. :) Though of course I don't like the fact that it's necessary.

A simpler alternative if one just wants the value at some point in a pipe chain (or something to mouse over at design time to see the type at that point), `|> fun x -> x` works well.

**Comment by abelbraaksma** [comment]
>  `|> fun x -> x` works well.

Yes, I've used that often, but with composition that can quickly get messy with added parens and everything. Here I wanted to break inside the list items, not the whole list.

But it would be so much nicer if this wasn't a (necessary) workaround for improving the debugging experience.

**Comment by dsyme** [comment]
I don't think this is a bug in the core F# implementation, since we don't specify the debugging behaviour of arbitrary CEs.  

Related in #4867. As I outline there, getting good debugging even for the synchronous parts of delayed computations is hard, though progress has been made.  And that only deals with stack traces, and not stepping.

What's I think is really needed is a comprehensive guide to writing CEs that have good debugging experiences (stack, stepping, exception stacks, breakpoints).  The notes in #4867 are a good starting point for stacks.

I will close this as it's not specifically an actionable  bug in the compiler.
