### ISSUE TITLE
namspace rec

### ISSUE THREAD

**Issue by RoswellMiller** [Microsoft/visualfsharp#4858]
Please provide a succinct description of the issue.

Provide the steps required to reproduce the problem

1. Copied example of namespace rec from documentation in docs.Microsoft
2. Put it in an .fs file i visual studio
3. compiled
4. it failed to compile

If possible attach a zip file with the repro case. This often makes it easier for others to reproduce.
The zip file should ideally represent the situation just before the call/step that is problematic.

Provide a description of the expected behaviour.

compilation without error

Provide a description of the actual behaviour observed. 

3 FS0072 and 1 FS0027 errors

Provide a description of any known workarounds.

none

Provide any related information 

* Operating system Windows 10
* Branch Microsoft F# in VS2017
* .NET Runtime, CoreCLR or Mono Version
* Editing Tools (e.g. Visual Studio Version) VS2017
* Links to F# RFCs or entries on https://github.com/fsharp/fslang-suggestions
* Links to performance testing scripts
* Indications of severity RENDERS COMPILER USELESS

**Comment by cartermp** [comment]
@RoswellMiller Thanks, it appears that both the recursive module and namespace samples had an update at one point which broke them such that they wouldn't compile. Closing this issue as it's a doc bug that is fixed in these PRs:

https://github.com/dotnet/docs/pull/5240
https://github.com/dotnet/docs/pull/5239
