### ISSUE TITLE
Visual F# Nightly doesn't update after VS upgrade to 15.7.0 RTM

### ISSUE THREAD

**Issue by irium** [Microsoft/visualfsharp#4862]
#### Repro steps

I have installed Visual F# Nightly. After upgrading VS from 15.6.x to 15.7.0 it installed latest Visual F# RTM version (15.7.20180425.1) and don't see any updates from Nightly channel anymore :(

Trying installing downloaded *.vsix manually failed because "This extension is already installed to all applicable products."

RTM extension can't be uninstalled because other components now depends on it (.NET Core and others).

#### Expected behavior

Expected to be able to install and receive latest nightly builds updates of Visual F# in VS.

#### Actual behavior

No updates found.

#### Known workarounds

I'm not aware of any.

#### Related information 

Provide any related information 

* Operating system
Windows 10 Pro
* .NET Runtime, CoreCLR or Mono Version
```
.NET Core SDK (reflecting any global.json):
 Version:   2.1.300-rc1-008673
 Commit:    f5e3ddbe73

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.16299
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.300-rc1-008673\

Host (useful for support):
  Version: 2.1.0-rc1
  Commit:  eb9bc92051

.NET Core SDKs installed:
  2.1.200 [C:\Program Files\dotnet\sdk]
  2.1.300-rc1-008673 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.0-rc1-final [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.0-rc1-final [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 1.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.0-rc1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
```
* Editing Tools (e.g. Visual Studio Version)
VS 15.7.0
Visual F# 15.7.20180425.1

P.S.
Visual F# in VS 15.8.0 Preview 1 updated to 15.7.20180430.2 as it's latest version in "preview" channel.

**Comment by cartermp** [comment]
@brettfo Is the nightly feed up to date? I'm noticing that the base version for generated VSIXs is 15.6.

@irium Is there a need to use the nightly at this time? If not, I'd say just wait and we can figure it out.

> RTM extension can't be uninstalled because other components now depends on it (.NET Core and others).

F# has been required by the .NET Core component since VS 15.5. What you're describing has been the case for quite some time. My guess is that you cannot install a nightly build right now because the version is lower than the actual RTW build.

> P.S. Visual F# in VS 15.8.0 Preview 1 updated to 15.7.20180430.2 as it's latest version in "preview" channel.

This is also intentional. The F# tools version in both 15.7 and 15.8 is the same right now.

**Comment by irium** [comment]
@cartermp Yes, I can wait. But latest nightly versions brings some usefull performance and memory usage fixes. Also it has almost fixed previously broken Intellisense.

> because the version is lower than the actual RTW build.
Seems that this is the case.

**Comment by cartermp** [comment]
There aren't any significant performance or memory features, nor fixes for IntelliSense in the latest master compared with what was released in 15.7. Is there an issue with IntelliSense in 15.7?

**Comment by irium** [comment]
![image](https://user-images.githubusercontent.com/23728/39799397-c85b9da8-536c-11e8-98da-538c80025197.png)

As for performance - hadn't enough time to work with it to compare.

**Comment by cartermp** [comment]
Ah, yes; that particular fix is not in 15.7

**Comment by brettfo** [comment]
Good catch, @irium!  I was too busy with other stuff to realize that we'd shipped 15.7.  I just created PR #4877 which pulls all of the `dev15.7` branch into `master` including the nightly package version upgrade from 15.6 to 15.7.  The error message "This extension is already installed to all applicable products." was because the nightly package version is 15.6.x.y which is less than 15.7.x.y, even though it has a newer date stamp (the last part of the version number.)

Once the tests are green on that PR I'll kick off another internal build to generate a new nightly.  ETA is just over an hour after that PR merges.

**Comment by irium** [comment]
Thanks! Waiting for package to update.

**Comment by brettfo** [comment]
Build is still running; I'd guess ~45 minutes until it's done.  I'll keep an eye on its progress.

**Comment by irium** [comment]
Ok, thanks!!

**Comment by irium** [comment]
Got it! Thank you again!
