### ISSUE TITLE
Runtime error with SqlEntityConnection TP under VS 2015 RC and F# 3.1

### ISSUE THREAD

**Issue by toburger** [Microsoft/visualfsharp#492]
When I use the SqlEntityConnection Type Provider with Visual Studio 2015 RC (Visual FSharp 4.0 Preview 06-03-2015) I get a runtime error when I use a different Target Runtime than 4.0.

When running the project with 4.0 everything works as expected, but when I switch the Target Runtime to 3.1 I get a runtime error:

```
System.IO.FileNotFoundException was unhandled
Message: An unhandled exception of type 'System.IO.FileNotFoundException' occurred in mscorlib.dll
Additional information: Die Datei oder Assembly "tmp7234, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null" oder eine Abhängigkeit davon wurde nicht gefunden. Das System kann die angegebene Datei nicht finden.
```

Visual Studio 2013 with Target Runtime 3.1 doesn't crash (which uses v3.1\fsc.exe).

**Comment by latkin** [comment]
Hi @toburger - I can't repro the issue given the current description. My simple SQL entity app works fine targeting 3.1 from 4.0  Some further questions for you:

- Can you share any of the following with us? If not here on GH, then privately at fsbugs@microsoft.com.
  - Repro project/solution/source
  - Resulting binaries
- Is the problem new with the latest F# 4.0 preview? i.e. do you know if it worked ok with an earlier F# 4.0 build?

**Comment by latkin** [comment]
Someone else reported this internally, as well, and was able to share full repro.  I think I know the root cause now.

Query expressions get compiled into F# code quotations, and those get serialized in the resulting assembly. In this case the quotations contain a bogus reference to the temp assemblies used behind the scenes within the SQL type provider. They *should* reference the local assembly (where temp asms get statically linked), but for some reason in this cross-version scenario they are still pointing at the phantom temp assembly.

Workarounds:
- Reference FSharp.Core 4.4.0.0
- (Hack, but effective) Manually redirect the `tmpXYZ` assembly resolution back to the local assembly:
```fsharp
open System
open System.Reflection

AppDomain.CurrentDomain.add_AssemblyResolve(fun _ evtArgs ->
    // might want to make this a bit more robust
    if evtArgs.Name.StartsWith("tmp") then Assembly.GetExecutingAssembly()
    else null
)
```

**Comment by latkin** [comment]
Culprit is [here](https://github.com/Microsoft/visualfsharp/blob/fsharp4/src/fsharp/creflect.fs#L970) - this should be a call to `ConvILTypeRefUnadjusted`.  Looks like simple oversight with refactoring to new quotation references format, in [`640db00`](https://github.com/Microsoft/visualfsharp/commit/640db001bf4c91a31c45115355842205e9631e16#diff-58f43f706f29780d884d23a41f710571R963).

/cc @dsyme

**Comment by dsyme** [comment]
Wow good catch

**Comment by dsyme** [comment]
@latkin - agreed that should be a call to  ConvILTypeRefUnadjusted
