### ISSUE TITLE
Possible inconsistency in type unification

### ISSUE THREAD

**Issue by optimusbrine** [Microsoft/visualfsharp#498]
Suggesting was made in fsharp/fsharp#422 to open this issue here instead

    let foo (a: seq<seq<'a>>) = a
    let someCharArAr()        = [|[| 's' |]|]
    let quack                 = [|[| 's' |]|]
    let moo : char [][]       = quack
 
    foo [|[| 's' |]|]  |> ignore // OK
 
    foo (someCharArAr()) |> ignore // Fails
    foo moo   |> ignore // Fails
    foo quack |> ignore // Fails

I would think that if `foo [|[| 's' |]|]` type checked, that the other applications of `foo` would type check too, but they do not. Type checking for each of the others fails with:

    The type 'seq<'a>' does not match the type 'char []'

I am working with the version of the compiler packaged with VS2015pre, fsi reports a version of '14.0.22810.0'. It seems to be reproducible in 3.0 as well though.

**Comment by dsyme** [comment]
This is to do with how array expressions ``[| ... |]`` are checked as of F# 3.x. . See 6.3.4 in the F# 3.1 Language spec.   The rule says that where if the element type is known before checking the array expression then each element may upcast to that element type, e.g. cases such as ``let x : Widget[] = [| Label(); Button() |]`` .  We have generally been hesitant about adding such rules precisely because of the kind of effect shown above - this is one case where we eventually made an exception.

The workaround suggested in fsharp/fsharp#422  is the right one (use a flexible type in the signature of the function)
