### ISSUE TITLE
Changing a file triggers checking it in context of all projects it's included to

### ISSUE THREAD

**Issue by vasily-kirichenko** [Microsoft/visualfsharp#5125]
https://github.com/fsprojects/FSharp.TypeProviders.SDK includes (huge) `ProvidedTypes.fs` in several projects:
 
![image](https://user-images.githubusercontent.com/873919/41062210-ce8a5188-69dd-11e8-9367-287dbe6b31a3.png)

Any change in this file results with **1.5 minutes** high CPU load. 

After unloading all other projects (and restarting VS because unloading itself did not help) like this

![image](https://user-images.githubusercontent.com/873919/41062961-f756e0d4-69df-11e8-942b-c6a1e1162460.png)
 
(and targeting only netstandard2.0), CPU is load for about 15 seconds.

I think the file should not be checked in context of projects and target frameworks that are not active (for projects it means that no other files included to them are open, for frameworks - I don't know).

**Comment by 7sharp9** [comment]
It’s certainly very painful to edit this file.

**Comment by cartermp** [comment]
@TIHan mentioned this in recent work for consuming projects that use multitargeting. Work to handle this is possible, but not trivial. We're currently at parity with what C# does and decided to stop there for the time being.

I think it's worth doing, just not sure when the appropriate milestone would be. 15.8 is right out for now due to stabilizing the current tooling changes and new language version.

**Comment by cartermp** [comment]
This is not something we control (nor can control), since all contexts are built for each TFM by design in the project system. You could consider it fallout of multi-targeting, which (to my knowledge), no IDE actually has proper support for.

The fact that the TPSDK has these many targets is a bit nuts, though.
