### ISSUE TITLE
readonly field can't use at the ReflectedDefinition function.

### ISSUE THREAD

**Issue by bleis-tift** [Microsoft/visualfsharp#514]
## Description:
A readonly field that is defined by C# class can't use at the function with ReflectedDefinition attribute.

## Repro Steps:
```csharp
public class Class1
{
    public readonly string Value;
    public Class1(string v) { this.Value = v; }
}
```

```
[<ReflectedDefinition>]
let f () = Class1("aaa").Value
```

## Expected:
Compilation is successful.

## Actual:
Compile error.

```
Quotations cannot contain inline assembly code or pattern matching on arrays
```

## Version: Language, compiler, library, platform version
F# 3.1.2, .NET Framework 4.5, Visual Studio 2013

## Workaround: List any known workarounds
* remove `readonly`
* use property
* remove `ReflectedDefinition` (but this is unacceptable)

**Comment by latkin** [comment]
Root cause is [here](https://github.com/Microsoft/visualfsharp/blob/fsharp4/src/fsharp/creflect.fs#L447-L449).  This case handles both `[ldsfld]` and `[ldsfld; nop]`, but only captures `[ldfld]`.  In this case the op is `[ldfld; nop]` so it falls through to the error case.

The extra `nop` is deliberately added for readonly fields ([here](https://github.com/Microsoft/visualfsharp/blob/fsharp4/src/fsharp/tc.fs#L2931-L2932) for instance, [here](https://github.com/Microsoft/visualfsharp/blob/fsharp4/src/fsharp/tc.fs#L8301-L8302) for static), so it looks like it was just an oversight to miss this case.

**Comment by latkin** [comment]
Marking up for grabs, fix is described above.
