### ISSUE TITLE
Provided methods with static params can't be used as first-class function values

### ISSUE THREAD

**Issue by latkin** [Microsoft/visualfsharp#516]
I cobbled together a variation on the regex type provider sample, where the pattern string is now a static method argument, not a static type argument.

It works fine in direct usage, but I get an unexpected error when attempting to use the method as a function value.

```fsharp
let x = RegexTyped.Match< @"(?<first>\w+) (?<last>\w+)"> "John Doe"
printfn "First: %s Last: %s" x.first x.last  // works


let y =
    "Jane Doe"
    |> RegexTyped.Match< @"(?<first>\w+) (?<last>\w+)">
                        // error: unexpected type arguments
```

**Comment by dsyme** [comment]
I think this is consistent for F# 4.0 because methods instantiated with generic parameters also can't be used as first-class values

I do think it is worth addressing this in a future version of the language - please add an http://fslang.uservoice.com suggestion and we can mark it as approved for vNext.

```
type C() = 
   static member M<'T>(c:'T) = c

1 |> C.M<int>
```
