### ISSUE TITLE
Debugging VFT solution is practically impossible due to constant almost immediate crashes

### ISSUE THREAD

**Issue by vasily-kirichenko** [Microsoft/visualfsharp#5161]
![image](https://user-images.githubusercontent.com/873919/41204519-33cd532a-6cee-11e8-866f-3727bc62ff48.png)

I just launch Rider to debug it.

**Comment by vasily-kirichenko** [comment]
After that this appears

![image](https://user-images.githubusercontent.com/873919/41204534-583c48b0-6cee-11e8-9562-ae5715ca142a.png)

And pressing Yes kills the exp instance.

**Comment by dsyme** [comment]
This is almost certainly due to displays of debug information.  I think you have to track them down one by one.  I took a pass over the TAST structures recently to greatly reduce the amount of auto-formatting, and I've been happily debugging recently

Any context on what you were debugging and visualizing?  I've been only debugging fsc.exe.

I've not specifically seen the "LoadFrom" message.

**Comment by vasily-kirichenko** [comment]
A workaround: Ctrl+F5 in VS, then attach Rider to the exp instance. No crashes.

**Comment by cartermp** [comment]
No repro - additionally, with the VS debugger being out of process in VS 2019, these sorts of problems may not really be common anymore
