### ISSUE TITLE
Fully qualified discriminated unions in modules gives an error but shows up in intellisense

### ISSUE THREAD

**Issue by kasperhj** [Microsoft/visualfsharp#518]
```
module Module =
    type Result =
        | Success
        | Failure

    type Response  =
        | Result of Result        

let response = Module.Response.Result <| Module.Result.Success // <- ERROR HERE
```
Gives this error:

> The field, constructor or member 'Success' is not defined

`Module.Result.Success` does however show up in intellisense.

Removing `Module` and it works as expected.
```
type Result =
    | Success
    | Failure

type Response  =
    | Result of Result

let response = Response.Result <| Result.Success
```

**Comment by latkin** [comment]
Sorry, this slipped through the cracks a bit.

The problem is due to the overloaded `Result` name.  `Module.Result` is resolved to the union case `Module.Response.Result`, not to the union type `Module.Result`.

It does seem a bit odd that the second example works while the first doesn't, but it probably just some corner case of the resolution rules. @dsyme does this look like something worth investigation or is it by design?

**Comment by dsyme** [comment]
This is consistent with the expected behaviour - preference is given to the union case (we don't backtrack through all possibilities after a union case resolution)
