### ISSUE TITLE
Different results in Debug + Release for byrefs

### ISSUE THREAD

**Issue by TIHan** [Microsoft/visualfsharp#5235]
This is something @tannergooding found.

The code below:
```fsharp
open System

let cool (doIt) =
    let mutable x = 42
    let r =
        if doIt then
            let mutable y = 1
            &y
        else
            &x

    let c = 
        if doIt then
            let mutable z = 2
            &z
        else
            &x

    x + r + c

[<EntryPoint>]
let main argv =
    printfn "Hello World from F#!"
    let x = cool(false)
    printfn "%i" x
    let y = cool(true)
    printfn "%i" y
    0 // return an integer exit code
```
Outputs `45` in debug, `46` in release.

Two ways to fix it:
Add scoping for byrefs.
Or.
Fix the optimizer.

**Comment by tannergooding** [comment]
This comes from the optimizer determining that `y` and `z` can share the same local slot and not taking into account that they escape their "enclosing scope" due to the byref semantics.

Adding scoping rules like C# has (and not allowing byrefs to variables that would allow them to escape their enclosing scope) would be one way to fix it.

Fixing the optimizer to not have y and z share the same local slot when byrefs are involved should also work.

**Comment by TIHan** [comment]
This also gives different results in our new inref stuff.
```fsharp
let test () =
    let x = &1
    let y = &2
    x + y
```

**Comment by TIHan** [comment]
Also happens here to:
```fsharp
let cool () =
    let x =
        let mutable x = 1
        &x

    let y =
        let mutable y = 2
        &y

    x + y
```

**Comment by cartermp** [comment]
Moving out to 16.0 since the fix breaks optimizations

**Comment by TIHan** [comment]
I'm closing this as it is now not possible to write code like this in F# 4.5.
