### ISSUE TITLE
Should the props files be updated for net471 and net472?

### ISSUE THREAD

**Issue by cartermp** [Microsoft/visualfsharp#5368]
See here: https://github.com/Microsoft/visualfsharp/blob/master/src/fsharp/FSharp.Build/Microsoft.FSharp.NetSdk.props#L81

We do not account for net471 or net472, but these are both shipped versions of .NET Framework.

**Comment by cartermp** [comment]
cc @KevinRansom

**Comment by KevinRansom** [comment]
@cartermp no need.  The highlighted code enables the build to produce a ValueTupleReference for the dotnet frameworks that do not contain a ValueTuple in mscorlib.  4.7 still has an entry because it has the ValueTuple in mscorlib, however, it does not contain the unification from System.ValueTuple dll to System.Runtime dll.


Kevin

**Comment by cartermp** [comment]
👍
