### ISSUE TITLE
Visual F# not part of "typical" installation in VS2015

### ISSUE THREAD

**Issue by forki** [Microsoft/visualfsharp#544]
IIRC it was always part of the default installation. Even in the VS2015 beta I tried.

IMHO that's really really a bad thing.

**Comment by isaacabraham** [comment]
I’ve seen this as well. It’s not as bad as I initially thought – apparently you’ll still see all the F# project options in the dialogs, it’s just on first use it’ll download the templates; this is the same as C++ as well.

**Comment by forki** [comment]
So if I don't install it and open a F# project it will still work?

**Comment by isaacabraham** [comment]
My understanding is that at that point it will then download the templates and other pre-reqs. Perhaps someone on the VS / VF# teams can confim this.

**Comment by latkin** [comment]
The whole thing is not ideal, but the experience really isn't too bad.  This decision was made post-RC so unfortunately nobody had a chance to see it until now.  C++ and various other components were also moved to "off by default," this isn't F#-specific.

If you don't select the F# box at install, you will still see an F# node in "new project."  There will be a link that opens the setup dialog and lets you install F# at that point.  Same if you open a sln w/ an fsproj - a dialog will pop explaining "you don't have F# but click this button to install it".

**Comment by forki** [comment]
At least I'm getting the `Microsoft Advertising SDK`ootb.

**Comment by vasily-kirichenko** [comment]
> This decision was made post-RC so unfortunately nobody had a chance to see it until now.

:((((((

**Comment by isaacabraham** [comment]
@forki :-/

**Comment by damianh** [comment]
And I used to be able to de-select fuppin' VB.NET :|

**Comment by thinktainer** [comment]
> This decision was made post-RC so unfortunately nobody had a chance to see it until now.


[Trollolol](http://www.myinstants.com/instant/trololo/)

**Comment by forki** [comment]
Closing this. Since discussion is pointless.

**Comment by CumpsD** [comment]
On twitter, @LyalinDotCom and @shanselman just tweeted they'll help looking into this.

Personally, it would make more sense that all languages are treated like this and I can just select what I want during setup.

**Comment by forki** [comment]
For the record: I'm not against the lazy installation of VS features. In general that is a very good idea.
I guess my point is about commincation and testing. The language teams and the community tested A LOT in CTPs and RC. Then such a major change is forced on us. Nobody outside of MS tested it. That's a bit depressing.

**Comment by isaacabraham** [comment]
agree with @forki - i think the componentising is a great idea, lower download size etc. etc.. The communication could have been better handled and it's confusing that something like this went through right at the last minute with no community feedback.

**Comment by KevinRansom** [comment]
I've re-opened this so we can continue the discussion a little longer, and clear the air.

I think Steffen @forki  has hit the nail on the head with his last point.  It was done at the last minute, and without community consultation, we would have preferred not to do it that way, it was in fact one of our strongest arguments in favor of getting more resources to improve the experience following the decision to be hardcore about componentizing VS.

The decision to go ahead with componentization was take in the period before the most recent RC was released, and as such there was no way that we could do the componentization prior to that release, there just was not sufficient time.  We also could not release RTM Visual Studio without a large amount of componentization VS is simply too huge and has such a wide array of features and tools that a full install would be regarded by many as an unnecessary tax on their disk space.

The solution was to retain the full set of features and tools in a visual studio installation, but to enable many of those features and tools to become optional at setup.  By tracking usage telemetry over VS2013, it was determined what features were used the most and disabling those whose audience is more specialized.  You should note that C++ is similarly not enabled by default, which for sure surprised me, even though telemetry supports that.

Because it had to happen, we did our very best to ensure that the experience of installing VS and discovering that you had forgotten to install the features you need was not unpleasant.  I think in this we succeeded.

In a similar way to other optional VS technology, VS now displays an installer breadcrumb for Visual F# - a link in the new project dialog as an early indicator that Visual F# is installable.

For existing F# developers we ensured that when a project load occurs inside VS we check to see if the components required by the project are loaded, and if they are not loaded we will alert the developer to that fact and give him the option of installing them.  For us the most interesting of these are likely to be:  Visual F# Tools, the VSSDK and for mobile developers the Xamarin VS integration tools.

One scenario that is enabled now, that was not before is this:
* On a clean machine, install VS2015 with default install
* Clone the visual f# tools repo
* Open (deployment.sln) [https://github.com/Microsoft/visualfsharp/blob/fsharp4/vsintegration/src/Deployment.sln]
* VS will alert you to the missing dependencies visualfsharp tools and vssdk and allow you to install them directly from setup.

It is really great that it works and doesn't require you to pre-install everything, personally I am quite a fan of the changes, I am just regretful that it came too late for the proper consultation.

Thanks

Kevin

**Comment by forki** [comment]
What about fsx files? Does it break C# projects with FAKE build scripts? Did anyone tested this already?

**Comment by latkin** [comment]
Purely file-based stuff (File -> New -> File..., File -> Open -> File, loose files in a project) does not have any special support.  So FAKE scripts on a C# project will (I believe) just appear as text files.

**Comment by forki** [comment]
So that's one of the major use cases not working any more? That's a bit unfortunate. Will test myself tomorrow.

**Comment by isaacabraham** [comment]
Argh. That'll be a pain. I often have loose .fsx files in C# projects, either just for testing out some API or similar.

**Comment by dungpa** [comment]
Componentizing VS is a good idea. 

But changing VS installation model close to RTM is just so bad. So many scenarios used to work ootb are now broken. Here is one more bug adding to the pile https://github.com/fsprojects/VisualFSharpPowerTools/issues/1048. Even worse, there is no communication about the issue to set the right expectation for users.

I guess breaking C++ and F# users is not an issue for MS.

**Comment by Thorium** [comment]
This is significant as when enterprise companies with hundreds of developers install the VS, then when you take F# into use, will it just work, or will everyone's build fail. 

Not to mention the existing users: We are using Fake as our enterprise build script. Will this mean that we won't update to VS2015? I already have seen some pressure to move away from Microsoft Visual Studio as the main IDE.

**Comment by smoothdeveloper** [comment]
Considering that F# language has probably the lowest footprint of language support compared to other .net languages or c++, it would make sense to have it installed by default.

Disabling features based on telemetry makes sense when the features weight more than a couple hundred megabytes, but I believe F# is still bellow this threshold.

Also it seems lazy installation works for projects but doesn't work on opening individual .fs / .fsi / .fsx files, nor when installing plugins relying on the language service being installed.

Since VS2010, opening an .fsx on a default VS install would provide intellisense, full language support and interpreter interaction, that was a selling point for using F# for exploratory coding, that seems like a step backward to get people to use the language.

**Comment by forki** [comment]
related: https://github.com/Microsoft/visualfsharp/issues/565

**Comment by latkin** [comment]
Closing this out as I think feedback has been heard. We have forwarded it along to various internal people who are involved with this change.

For any specific bugs found due to the new installation behavior please open dedicated issues.

**Comment by forki** [comment]
Big thanks for forwarding this to the right people.

**Comment by forki** [comment]
> What about fsx files? Does it break C# projects with FAKE build scripts? Did anyone tested this already?

@KevinRansom is this fixed in VS2015 Update1? It's one of the major use cases for F#.

**Comment by dsyme** [comment]
@forki - I'd say you should open a specific new issue for that (Something like "Opening a project containing an .fsx - including C# projects - should trigger an install of the Visual F# Tools"). As part of that it would be useful to know if there are any other precedents where opening single files triggers installation of a toolchain.

**Comment by ptrelford** [comment]
For completeness, you can easily install the Visual F# Tools in Visual Studio 2015 editions even if you didn't tick the Visual F# box at install time.
Inside Visual Studio select File -> New Project and then locate the Visual F# template, when selected you should see a button to "Install Visual F# Tools":
![Screenshot of Visual Studio New Project wizard](https://i.snag.gy/ShmqzJ.jpg)

**Comment by forki** [comment]
@ptrelford that is a nice trick, but you really have to know wherre to look for this ;-)

**Comment by HelloKitty** [comment]
@ptrelford Doesn't appear to be the case in VS2015 Update 3.
