### ISSUE TITLE
An accessibility compilation error when a public type implements an internal interface that uses an internal type

### ISSUE THREAD

**Issue by zealisland** [Microsoft/visualfsharp#557]
The detail is at http://stackoverflow.com/questions/31598422/on-an-accessibility-compilation-error-when-a-public-type-implements-an-internal, is this a compiler bug or by design? If it's by design, please comment/answer at the stackoverflow thread.

**Comment by latkin** [comment]
So that others don't need to visit the link, the question is why there is an error in this case:

```fsharp
type internal Foo() = class end

type internal IMyInterface =
    abstract member Method1 : Foo -> unit

type Class1() =
    interface IMyInterface with
        // error FS0410: The type 'Foo' is less accessible than
        //  the value, member or type 'override Class1.Method1 : v:Foo -> unit' it is used in
        member this.Method1(v : Foo) = ()
```

Seems like a simple oversight for a slightly edge case.  It's only valid when the interface is implemented explicitly, however that's the F# default so in theory this should be legal.

I don't see this covered explicitly in the language spec (I might be missing it though) so I'll mark as a bug for now.
