### ISSUE TITLE
Symbols not found in rename

### ISSUE THREAD

**Issue by jdh30** [Microsoft/visualfsharp#5581]
Rename refactoring doesn't work in this case.

#### Repro steps

Type:

    type A_B = A of int | B of float
    let x : A_B = A 3

Right click on the second `A_B` on the second line and try to rename it to anything else.

#### Expected behavior

I expect the identifier to be renamed uniformly.

#### Actual behavior

Only the second instance is renamed. The first is ignored.

#### Known workarounds

Use OCaml.

#### Related information 

* Windows 10 (Microsoft Windows NT 6.2.9200.0)
* CLR 4.0.30319.42000
* VS 15.8.2

**Comment by Krzysztof-Cieslak** [comment]
> **Known workarounds**
> Use OCaml.

I know better workaround...
![2018-09-04 20 09 33](https://user-images.githubusercontent.com/5427083/45049332-99f2e380-b07e-11e8-927a-8c62c08f69d9.gif)

**Comment by cartermp** [comment]
So this is actually a timing issue, which might be related to some recent workspace-related changes.

For a script, this never reproduces:
![rename-script](https://user-images.githubusercontent.com/6309070/45050643-aeab8900-b036-11e8-8a13-9b07a52ab2ac.gif)

That's because it's a misc. files context, where everything is "available" almost instantly.

For a file within a project, I can reproduce this at first, but it works after some time (30 sec on my machine?):
![rename-sdkproj](https://user-images.githubusercontent.com/6309070/45050916-5759e880-b037-11e8-9763-9f89a3bf1073.gif)

Files in this context don't have all references loaded as quickly, though I think there may have been a regression w.r.t timing in 15.8 when we fixed our Roslyn hookups to address issues where the language service wouldn't load. Could that be the change?

cc @TIHan and @jasonmalinowski

**Comment by jdh30** [comment]
I'm not sure anything has changed: this kind of rename refactoring has never worked reliably for me whereas the old pre-VS2017 rename refactor always worked for me.

**Comment by jdh30** [comment]
Timing issues make sense though. I have found before that rename refactoring could be made to work by typing extremely slowly. Obviously at least one concurrency bug in there.

**Comment by cartermp** [comment]
Haven't been able to reproduce this in VS 2019, which I suspect is related to the work that went into cleaning up how the tools hook into Roslyn Workspaces. #6055 was another case that doesn't reproduce. And as per [this comment](https://www.reddit.com/r/fsharp/comments/b8m8up/announcing_f_46_net_blog/ek7zlfg/) I'll consider the issue resolved.
