### ISSUE TITLE
Reordering of methods causes code to be less generic

### ISSUE THREAD

**Issue by nikonthethird** [Microsoft/visualfsharp#5787]
Reordering two methods, where one calls the other, code can break if the method that's earlier in the code constrains type parameters of the second method.

#### Repro steps

```fsharp
type Works () =

    member _this.A<'T> (x : 'T) = x

    member this.B () = this.A ()




type DoesNotWork () =

    member this.B () = this.A ()
    //                 ^^^^^^^^^
    // This construct causes the code to be less generic
    // than indicated by the type annotations. The type
    // variable 'T has been constrained to be type 'unit'.

    member _this.A<'T> (x : 'T) = x
    //             ^^
    // This type parameter has been used in a way that
    // constrains it to always be 'unit'.
```

#### Expected behavior

Since I explicitly added a type parameter, this should have priority over any previous use of the method.

I think the behaviour is OK when the code is automatically generalized, but not if I explicitly want it to be generic.

#### Actual behavior

The type parameter is constrained by the earlier use of the method.

#### Known workarounds

Ensure that the ordering of the methods is always in favor of type inference.

#### Related information 

* F# 4.5
* Ionide

**Comment by dsyme** [comment]
This is by design.  You should fully annotate the type:


```
type ThisDoesWork () =

    member this.B () = this.A ()

    member _this.A<'T> (x : 'T) : 'T = x
```

**Comment by bender2k14** [comment]
I think @dsyme's workaround is specific to the implementation of `A`.  What if instead `A` were defined like this?
```
type ThisDoesWork () =

  member this.B () = this.A ()

  member _this.A (x : 'T) : string = sprintf "%A" x
```

This example applies @dsyme's suggestion of "fully annotating the type" by explicitly specifying the return type.  Now the only workaround I see is swapping the order in which the methods are defined as suggested by @nikonthethird.

Here is a more complex, and admittedly pathological, example.  Maybe it can be made realistic while continuing to reproduce the issue.  Anyway, I see no workaround in this case.
```
type ThisDoesWork () =

  member this.Foo (a1: 'a, a2: 'a, b: 'b) = this.Bar(a1, a2, b)

  member this.Bar (a: 'a, b1: 'b, b2: 'b) = this.Foo (a, b1, b2)
```

And to be clear, this issue is not specific to methods.  The key ingredient is the ability for a procedure (i.e. method or function) to call another that is defined after it.  For functions, this issue would look like this:
```
// nikonthethird's "Works" example
let Foo (a: 'a) = a
let Bar () = Foo ()

// nikonthethird's "DoesNotWork" example
let rec Bar () = Foo ()
and Foo (a: 'a) = a

// dsyme's workaround
let rec Bar () = Foo ()
and Foo (a: 'a) : 'a = a

// my pathological example
let rec Foo (a1: 'a) (a2: 'a) (b: 'b) = Bar a1 a2 b
and Bar (a: 'a) (b1: 'b) (b2: 'b) = Foo a b1 b2
```

Furthermore, @dsyme's workaround doesn't work in this case involving functions.

**Comment by dsyme** [comment]
> This example applies @dsyme's suggestion of "fully annotating the type" by explicitly specifying the return type. Now the only workaround I see is swapping the order in which the methods are defined as suggested by @nikonthethird.

To fully annotate, I believe you should give the generic parameter as well?

**Comment by bender2k14** [comment]
> To fully annotate, I believe you should give the generic parameter as well?

Oh, yes.  You are correct.  Very good :)

For completeness, here is that code.
```
type Works () =

  static member Bar =
    Works.Foo(0)

  static member Foo<'a>(a: 'a) : string =
    sprintf "%A" a
```

**Comment by bender2k14** [comment]
If I added type parameter declarations to my pathological example, then it doesn't compile.  Here I have also added a type annotation for the return type.  The compile error is the same even if those are omitted.
```
type DoesNotWork () =

  member this.Foo<'a, 'b>(a1: 'a, a2: 'a, b: 'b) : unit = this.Bar(a1, a2, b)

  member this.Bar<'a, 'b>(a: 'a, b1: 'b, b2: 'b) : unit = this.Foo(a, b1, b2)
```
