### ISSUE TITLE
Make Watch window work with F# syntax

### ISSUE THREAD

**Issue by xperiandri** [Microsoft/visualfsharp#582]
I used **FSharp.Text.RegexProvider**
And written

``` F#
type MatchIdRegex = Regex<"match\?m=(?<id>\d+)">
```

So than I use it this way:

``` F#
let m = matchIdRegex.Match(hrefAttribute.Value())
assert not(m.Success)
let matchId = m.id.Value
```

But when I tried to put `m.id.Value` into a Watch window there was an error.
Looks like this transformation from `m.id.Value` into `m.Groups["id"].Value` does not work nor in editor when hovering over this statement neither in Watch and Immediate windows.

Is this a problem with **FSharp.Text.RegexProvider** or TypeProviders infrastructure in F#?

**Comment by dsyme** [comment]
It's a limitation in the Visual F# Tools - the Watch and Immediate windows work w.r.t. C# syntax and compiled representations, rather than F# syntax.  

Adjusting them to use F# syntax is a feature request. In theory an implementation of that feature could host instances of the relevant type providers and determine the compilation mapping.

**Comment by dsyme** [comment]
Closing in favour of master bug #2544
