### ISSUE TITLE
SQL type provider - not all stored procedures are provided

### ISSUE THREAD

**Issue by Overlord-Zurg** [Microsoft/visualfsharp#597]
I'm trying to access an existing database via the Microsoft.FSharp.Data.TypeProviders.SqlDataConnection type. There are some stored procedures that are not provided (but most are).

I'm trying to determine what differentiates the unprovidable procedures from the others -- I believe that custom types are one reason the type-provision might fail, but they don't appear to be present here.

For what other reasons might our stored procedures be unprovidable?

Cross-posted at:
- http://stackoverflow.com/questions/29678958/f-sql-type-provider-why-arent-all-stored-procedures-provided

**Comment by latkin** [comment]
Hi @Overlord-Zurg, the actual communication with SQL and extraction of tables/sprocs is done by [SqlMetal.exe](https://msdn.microsoft.com/en-us/library/bb386987(v=vs.110).aspx), which is invoked by the type provider behind the scenes.  Any limitations of sqlmetal will be shared by the TP.

**Comment by latkin** [comment]
So I would recommend testing whether you can successfully extract all your sprocs via SqlMetal directly, then we can work backward and see what flags/params were needed that the TP is not using.

**Comment by Overlord-Zurg** [comment]
Thanks for the info! I'll try that.

**Comment by eriawan** [comment]
@Overlord-Zurg 

Could you tell us which version of Visual Studio you use? Also does your SQL Server tables and SP have multiple schemas?
What I'm trying to say is, SqlMetal in Visual Studio 2012 and Visual Studio 2013 doesn't support multiple schema scenarios.
A good sample on this is when you are dealing with AdventureWorks sample DB for SQL Server 2008 and above that contains tables that belongs to multiple different schemas. 
Although implicitly you can use dbo for all tables, but when mapping in LINQ to SQL, as far as I have tested, SqlMetal in VS 2012 and VS 2013 (hence valid in LINQ to SQL) only supports single schema only.
Support for multiple schemas has been provided by Entity Framework 6.0 (and above including 6.1) but this is another discussion for the way how SQL type provider should work using EF instead of using current SqlMetal.

CMIIW :smile:

**Comment by dsyme** [comment]
Please reopen this bug at github.com/fsprojects/Fsharp.Data.TypeProviders
