### ISSUE TITLE
Partially applied async function in module initialization hangs when compiled in release mode

### ISSUE THREAD

**Issue by jamesjrg** [Microsoft/visualfsharp#604]
Using .NET 4.5, F# 3.1, F# Core 4.3.1.0, Visual Studio 2013, Windows 8.1

This program hangs when compiled as Release, but not when compiled as Debug, not sure if it is a bug or if I just misunderstand something:

```
module Modulartastic =
    type MrsRecordType = {
        StringProperty : string }

    let partialAsyncFunc _ () = async { return true }

    let testFunc partialAsyncFunc = async {    
        return! partialAsyncFunc() }

    let parameter = {
        MrsRecordType.StringProperty = "hello" }

    let result =
        testFunc (partialAsyncFunc parameter)
        |> Async.RunSynchronously

[<EntryPoint>]
let main argv =
    0
```

**Comment by forki** [comment]
Also see discussion in https://github.com/fsharp/fsharp/issues/480

**Comment by latkin** [comment]
This is an example of static constructor deadlocking, see http://blogs.msdn.com/b/pfxteam/archive/2011/05/03/10159682.aspx.

F# modules can be thought of as static .NET classes. Initializing a module value will happen in the static constructor for that class.  In .NET, there is a runtime-level lock around type constructors in order to guarantee they run at most once.  If your static constructor (or module value) does some async stuff which, from another thread, needs to access a value on that selfsame class, you will deadlock.  .NET will not let you access a value on the class until it's type constructor is finished running, but that's what you are in the midst of doing...

So this is expected, though I won't quite call it "by design."  FWIW with this code I see a deadlock in both debug and release builds.  It's not a bug, really, just a limitation of what you can do in .NET code.

You can change `result` to a function `let result () = ...`, then call it from `main`, that will cause the work to be done outside of the type constructor and it should work.

**Comment by jamesjrg** [comment]
Ok, thanks! Changing result () to a function is what I did, though I didn't understand why it works. It sounds like maybe moving "parameter" to its own module might also work.
