### ISSUE TITLE
Possibly Infinite Loop in Recursive Function Under FSI.exe

### ISSUE THREAD

**Issue by Measter** [Microsoft/visualfsharp#606]
Note: I say 'possible' because I only let the program run for ~60 seconds before aborting.

To start with, a minimum example script demonstrating the problem is this:

```
let DoubleEquals (x:float) (y:float) = (System.Math.Abs (x-y)) < System.Double.Epsilon

let rec FixedPoint f x =
    let next = f x
    if DoubleEquals x next then x else FixedPoint f next

let res = FixedPoint System.Math.Cos 5.0
printfn "%f" res
```

When run under FSI.exe 14.0.23020.0 this program will not exit within 60 seconds. However, when run under FSIAnyCPU.exe 14.0.23020.0 it exits correctly in ~0.002 seconds (Timed with a Stopwatch removed from this example), as it also does when compiled through FSC.exe 14.0.23020.0

The command lines for running each was simply

* fsi RecTest.fsx
* fsianycpu RecTest.fsx
* fsc RecTest.fsx

Additionally, fsi can be convinced to execute properly by one of three ways: by printing `x` in each iteration as follows:

```
let rec FixedPoint f x =
    let next = f x
    printfn "%f" x
    if DoubleEquals x next then x else FixedPoint f next
```

By hardcoding the function:

```
let rec FixedPoint x =
    let next = System.Math.Cos x
    if DoubleEquals x next then x else FixedPoint next
```

Or by changing DoubleEquals to take the epsilon in an argument, and calling it like so:

 ```
let DoubleEquals (x:float) (y:float) (e:float) = (System.Math.Abs (x-y)) < e

let rec FixedPoint f x =
    let next = f x
    if DoubleEquals x next 1e-16 then x else FixedPoint f next
```

I'm running Windows 7 x64, with .Net 4.6.

**Comment by dsyme** [comment]
Thus looks like a difference in how 32bit and 64bit treat floating point convergence/equality. I don't think it's an F# bug, it would repro in C# as well?

**Comment by Measter** [comment]
OK, with the following C# code:

```
using System;

namespace RecTest
{
	class Program
	{
		static void Main( string[] args )
		{
			double res = FixedPoint( Math.Cos, 5.0 );
			Console.WriteLine(res);
		}

		private static double FixedPoint( Func<double, double> f, double x )
		{
			var next = f( x );
			return DoubleEquals( x, next ) ? x : FixedPoint( f, next );
		}

		private static bool DoubleEquals( double x, double y ) => Math.Abs( x - y ) < Double.Epsilon;
	}
}
```

Doing a release compile under x86 resulted in a StackOverflowException, while x64 did not. However, changing FixedPoint to this:

```
private static double FixedPoint( double x )
		{
			var next = Math.Cos( x );
			return DoubleEquals( x, next ) ? x : FixedPoint( next );
		}
```

Did not cause it to work, as it does in the F# version. Also, The F# version did not result in a stack overflow. Could the differing behaviour be explained by F# using tail call optimisation?

However, that doesn't seem to explain why making it print the value, or hardcoding the function, causes it to work. Is there a way to make FSI dump IL so that could be examined?

**Comment by latkin** [comment]
@measter, there is a way to have FSI dump its generated IL (the [`#ilcode` directive](https://github.com/Microsoft/visualfsharp/blob/master/src/fsharp/fsi/fsi.fs#L1665-L1667)), however you need a debug build of FSI to use it.  The generated IL is the same for both x86 and x64, so that's not the problem.

It's just a tricky bit of floating point trouble, there is no bug in the F# compiler or the JIT. The JITed x86 assembly is doing the following:

- Save `x` to the main stack as a 64-bit float
- Call `cos x` to compute `next`
  - This value is left on the top of the FPU floating point stack, with *full internal 80-bit representation*
- Load `x` back from main stack and push it onto the floating point stack as an 80-bit value
  - It's now stored as 80-bit, but of course there are only 64 bits of real precision
- Subtract*
- Absolute value
- Compare against `Epsilon`
- Go to top if comparison fails

So although `x` and `next` indeed represent the exact same 64-bit value, the crucial subtraction* is being done at 80-bit precision. Only `next` really has full 80-bit precision, so predictably the result is not 0 but some small remainder, and thus the epsilon comparison fails.

More effective methods of comparing floats are shown [here](https://msdn.microsoft.com/en-us/library/ya2zha7s(v=vs.110).aspx), I would recommend using one of those approaches.

**Comment by latkin** [comment]
If you add in another call after computing `next` (e.g. `Console.WriteLine(next)` or something), the assembly changes:

- Save result of previous iteration to the main stack as a 64-bit float `x`
- Call `cos x` to compute `next`
- Save `next` to the main stack as a 64-bit float
- Call `printf`/`Console.WriteLine` etc
- Load `next` back from the main stack and push it onto the floating point stack as an 80-bit value
- Load `x` back from main stack and push it onto the floating point stack as an 80-bit value
- Subtract
- Absolute value
- Compare against `Epsilon`
- Go to top if comparison fails

In this case, both operands have been rounded to 64-bit precision before comparing, so you get a perfect 0.0000 result.
