### ISSUE TITLE
TcSymbolUseData[] accounting for 19.1 MB on the LOH

### ISSUE THREAD

**Issue by cartermp** [Microsoft/visualfsharp#6084]
This was after opening VS (dev16.0, with built-in VSIX) for about three minutes, slowly implementing a function in FSharp.Editor that uses FCS and Roslyn types for about 3 minutes. I say slowly because I code slowly 🙂 

![image](https://user-images.githubusercontent.com/6309070/51067041-5a577d80-15c3-11e9-846d-5b083251512f.png)

This is  the `TcSymbolUses` ctor getting called 49 times, which is ~390k on the LOH each time. This is called by `TypeCheckTask` in the incremental builder:

https://github.com/Microsoft/visualfsharp/blob/631401a1cc7c487a6b27486242ac7df3e77bd495/src/fsharp/service/IncrementalBuild.fs#L1378

Since in my scenario the large majority of these symbols are the same (in fact they would probably be the mostly the same in nearly every scenario), I wonder if there's an opportunity to cache them.

**Comment by dsyme** [comment]
The way things are set up, we have to save _some_ information after checking a file - and the information we save is a dump of all the symbol resolutions.  For even a small file I'd imagine this can be 400K no problem.  The information is not particularly long lived - the next check of the file will make it irrelevant and the information will be collected.  I think this architecture is OK - if we were trying to reduce the amount of re-computed information we would do that by making all of checking more incremental from parsing through to type-checking.

SO it's not a priori _wrong_ to allocate this information, even in one linear array (note that pre-indexing the information or attempting to compress it is a waste of time since it is very often discarded).  It does however feel odd if the CLR is somehow assuming it is long-lived.  

Is the CLR applying the (in this case false) heuristic that all LOH objects are long-lived?  If so I suppose we could artificially chunk the array though it feels, well, artificial.  What's the minimum size on the LOH?

[ Aside: TBH much of this memory work would feel easier if the CLR just had a intrinsic allocation method that said "this object is big but transient", or magically worked that out.  From a GC perspective there should be no real problem with allocating short-lived big objects apart from the data-copying costs involved, as the data should just evaporate immediately on next collection.   ]

**Comment by dsyme** [comment]
BTW this is the definition of `TcSymbolUseData`:
```
[<Struct>]
type TcSymbolUseData = 
   { Item: Item
     ItemOccurence: ItemOccurence
     DisplayEnv: DisplayEnv
     Range: range }
```

Looking at this 
1. someone might want to turn `ItemOccurence` into a struct.  

For the others:
* `DisplayEnv` is generally a pointer to a shared object, not much to do there without too much work (well, ok, you could make it a uint16 indexing into an array of DisplayEnv)
* `Item` is a pointer to more information about the item that is a big discriminated union that's going to be hard to reduce
* `Range` is a struct already, and has recently got a tad bigger, not much we can do about that

**Comment by dsyme** [comment]
To answer my question:

> 'Big' objects go here – as the size at which an object may end up on this heap is 85,000 bytes, this usually means arrays with more than about 20,000 entries. https://www.red-gate.com/simple-talk/dotnet/net-framework/the-dangers-of-the-large-object-heap/

So we should chunk this thing I guess.  Ugh how artificial.  Fighting the memory manager is a PITA.

**Comment by dsyme** [comment]
If someone wants to look at this, it should be fairly easy to chunk the array allocated here, it's well encapsulated.  The member `AllUsesOfAllSymbols` is only ever iterated, so you simply need to change consumers to iterate an array-of-arrays 
```
type TcSymbolUses(g, capturedNameResolutions : ResizeArray<CapturedNameResolution>, formatSpecifierLocations: (range * int)[]) = 
    
    // Make sure we only capture the information we really need to report symbol uses
    let allUsesOfSymbols = [| for cnr in capturedNameResolutions -> { Item=cnr.Item; ItemOccurence=cnr.ItemOccurence; DisplayEnv=cnr.DisplayEnv; Range=cnr.Range } |]
    let capturedNameResolutions = () 
    do ignore capturedNameResolutions // don't capture this!

    member this.GetUsesOfSymbol(item) = 
        [| for symbolUse in allUsesOfSymbols do
               if protectAssemblyExploration false (fun () -> ItemsAreEffectivelyEqual g item symbolUse.Item) then
                  yield symbolUse |]

    member this.AllUsesOfSymbols = allUsesOfSymbols

    member this.GetFormatSpecifierLocationsAndArity() = formatSpecifierLocations
```

**Comment by dsyme** [comment]
(I must add: it is great to see this LOH-analysis work beginning to hone in on the _actual_ data we need to save, rather than data that should never have been allocated/copied in the first place :) )

**Comment by cartermp** [comment]
FYI there is excellent information in our docs about this: https://docs.microsoft.com/en-us/dotnet/standard/garbage-collection/large-object-heap

**Comment by cartermp** [comment]
> SO it's not a priori wrong to allocate this information, even in one linear array (note that pre-indexing the information or attempting to compress it is a waste of time since it is very often discarded). 

This feels like a bit of a design smell to me. If we need to allocate ~390k of data very often (in this case, every 3-4 seconds), then it implies something needs to be cached. I was only working with two files and typing in one, and only adding a single function. I don't see why that requires

**Comment by cartermp** [comment]
But relatively speaking this is far less pressing than other issues filed

**Comment by dsyme** [comment]
> This feels like a bit of a design smell to me. If we need to allocate ~390k of data very often (in this case, every 3-4 seconds), then it implies something needs to be cached. I was only working with two files and typing in one, and only adding a single function. I don't see why that requires

Yes. The smell is really just a whiff of the much bigger stench of re-checking entire files very frequently even on small changes.  

We could in theory pool the arrays, to avoid the reallocation.  However that must be done with real care as the arrays contain references.  And, putting aside the LOH, I'm certain that the costs of actually doing the re-checking are much higher than the cost of allocating and filling this specific data structure.

**Comment by dsyme** [comment]
> FYI there is excellent information in our docs about this: https://docs.microsoft.com/en-us/dotnet/standard/garbage-collection/large-object-heap

Thanks, yes, that's great up-to-date info
