### ISSUE TITLE
Map does not expose a constructor that accepts a comparer

### ISSUE THREAD

**Issue by panesofglass** [Microsoft/visualfsharp#633]
`Map<_,_>` may not be used with specifications such as OWIN due to its lack of accepting a `comparer` parameter. The parameter exists but is not publicly exposed. I can fix this in an upcoming version of F#, should it be accepted, but I don't know the best course of action to deal with this issue in older versions of F#. Thoughts?

**Comment by dsyme** [comment]
This is currently by design - it ensures that the same consistent comparer is used for all instances of maps using the same key type, e.g. when unioning two maps.  It is, however, a design choice and other libraries have chosen different solutions (and presumably you could always use an alternative library?).  Could you add a suggestion to http://fslang.uservoice.com to start with?
