### ISSUE TITLE
Make the compiler check for CLS Compliance when the CLSCompliant attribute is used

### ISSUE THREAD

**Issue by willsb** [Microsoft/visualfsharp#634]
Researching to answer [this SO question](http://stackoverflow.com/questions/32581173/how-to-verify-f-code-is-cls-compliant) I found this [MSDN page](https://msdn.microsoft.com/en-us/library/vstudio/bhc3fa7f(v=vs.100).aspx) that states the `CLSCompliant` attribute is there to mark a class as CLS compliant or not, but can also be used by the compiler to make the check and ensure compliance. Roslyn supports this, but the F# compiler doesn't :cry:

I searched for previous discussion on this subject, but I found nothing [here](https://github.com/Microsoft/visualfsharp/search?l=fsharp&q=CLSCompliant&type=Issues&utf8=%E2%9C%93) or [here](https://github.com/fsharp/fsharp/search?utf8=%E2%9C%93&q=CLSCompliant&type=Issues). Being so, I'm opening this issue. Can this be implemented here or it's not important enough and should be an extension for Visual Studio instead?

I'm not an expert F# developer, but I'm more than willing to help if necessary

**Comment by dsyme** [comment]
This is not something we'd be likely to implement.  Unfortunately the "CLS" (Common Language Subset) doesn't seem to really be an active, working specification effective at arranging cross-language interop beyond the basics since at least C# 3.0.

Also, if this were to be implemented it should go into an external tool like FSharpLint.

Cheers!
don
