### ISSUE TITLE
Pattern matching in anonymous record types?

### ISSUE THREAD

**Issue by eiriktsarpalis** [Microsoft/visualfsharp#6665]
It seems that pattern matching is not supported for anon record types

#### Repro steps

```fsharp
> let f { contents = x } = x + 1 ;;
val f : Ref<int> -> int

> let f {| contents = x |} = x + 1 ;;

  let f {| contents = x |} = x + 1 ;;
  ------^^

stdin(12,7): error FS0010: Unexpected symbol '{|' in pattern
```

#### Expected behaviour

Should compile to a `val f : {| x : int |} -> int` function.

**Comment by dsyme** [comment]
This is by design for the RFC, see https://github.com/fsharp/fslang-design/blob/master/FSharp-4.6/FS-1030-anonymous-records.md#pattern-matching.  So this should be a language suggestion

(The omission of this really shows my strong bias against pattern matching on records at all - I nearly always dislike code that uses this and I don't think it adds to the robustness of code since pattern matching on records is "flexible", i.e. fields can be omitted.  I know others will disagree.  I will add this note to the RFC for the record)

**Comment by eiriktsarpalis** [comment]
> I nearly always dislike code that uses this and I don't think it adds to the robustness of code since pattern matching on records is "flexible", i.e. fields can be omitted

There are exceptions where it can be useful, e.g. it's the only way to do nested pattern matches. E.g.
```fsharp
match foo with
| Some { value = Some x } -> ..
```
has to be rewritten to
```fsharp
match foo with
| Some x -> match x.value with Some y -> ..
```
In any case, it does raise an issue of consistency. Why should nominal records allow it, but anon records don't allow it?

**Comment by cartermp** [comment]
> In any case, it does raise an issue of consistency. Why should nominal records allow it, but anon records don't allow it?

Even if it were allowable with no changes today, it would be inconsistent because there is no structural subtyping allowed. In many (most?) cases it would be more verbose than just using `if` and `.`-notation.

I proposed this as an alternative: https://github.com/fsharp/fslang-suggestions/issues/713

That at least makes it sorta equivalent to what you can do with Records today, though it does open up the question of why Anonymous Records don't support structural subtyping.

**Comment by xperiandri** [comment]
> I don't think it adds to the robustness of code since pattern matching on records is "flexible", i.e. fields can be omitted. I know others will disagree. I will add this note to the RFC for the record

About omitted fields yes, but this limitation forced me to add additional record

``` F#
type VirtualNetworkConnectionWebReference =
    { Id : ResourceId
        SubnetName : ResourceName option }

type VirtualNetworkConnection =
    { Name : ResourceName
        Location : Location
        WebApp : ResourceId
        Kind : string option

        VNet : VirtualNetworkConnectionWebReference option
        //{| Id : ResourceId
        //   Subnet : ResourceName option |} option
        CertBlob : string option
        DnsServers : string option
        IsSwift : bool option

        Tags: Map<string,string>  }
    interface IArmResource with
        member this.ResourceId = virtualNetworkConnections.resourceId this.Name
        member this.JsonModel =
            let dependsOn =
                [ Some this.WebApp; this.VNet |> Option.map (fun vnet -> vnet.Id) ]
                |> List.choose id
            {| virtualNetworkConnections.Create(this.Name, this.Location, dependsOn, this.Tags) with
                kind = this.Kind |> Option.toObj
                properties =
                        {| vnetResourceId =
                            match this.VNet with
                            | Some { Id = vnet; SubnetName = None } -> vnet.Eval()
                            | Some { Id = vnet; SubnetName = Some subnet } ->
                                Network.subnets.resourceId(vnet.Name, subnet).Eval()
                            | None -> null
                        certBlob = this.CertBlob |> Option.toObj
                        dnsServers = this.DnsServers |> Option.toObj
                        isSwift = this.IsSwift |> Option.toNullable |}
            |} :> _
```
