### ISSUE TITLE
Many many false positive unused variables in paket project

### ISSUE THREAD

**Issue by forki** [microsoft/visualfsharp#6675]
With the latest VS 16.0.3 I see lots and lots of false positive grey outs in the Paket.sln

![image](https://user-images.githubusercontent.com/57396/57126690-211f6500-6d8e-11e9-8586-982d38831a09.png)

Any ideas why that is?

**Comment by forki** [comment]
Even worse: I can't build from VS anymore. because of some missing method exn

![image](https://user-images.githubusercontent.com/57396/57126853-b9b5e500-6d8e-11e9-958a-f65b79925614.png)

**Comment by forki** [comment]
it builds fine from cmd line

**Comment by cartermp** [comment]
There's a deeper problem here that's probably causing this.

If you tun on navigation bars, you can see the file opening in F# Miscellaneous Files, which means the file is "floating in space" and disassociated from the rest of the project:

<img width="426" alt="image" src="https://user-images.githubusercontent.com/6309070/57589513-4bcd9400-74d9-11e9-88cc-c161d4463256.png">

**Comment by cartermp** [comment]
@TIHan FYI

**Comment by cartermp** [comment]
Actually I wonder if this is due to `FSharp.Compiler.Tools`.

**Comment by forki** [comment]
Yes it seems to be related to the fact that vs 2019 can't handle FCT

Phillip Carter <notifications@github.com> schrieb am Mo., 13. Mai 2019,
02:33:

**Comment by cartermp** [comment]
I've attempted to remove FCT but I've been unsuccessful. The project files are encoded weirdly and can't be parsed even after:

* Removing from `paket.dependencies`
* Removing from each `paket.references`
* Removing the reference from each project

Unfortunately that means this is just guesswork, since I can't confirm that IDE tooling works or is broken in Paket _without_ FCT.

**Comment by forki** [comment]
the problem is really related to FCT and VS not caring about this use case. which means many things in F# ecosystem now won't work with VS 2019 and need to convert. It's making things harder than it should be, but seems I'm alone with that opinion and only happy case and dotnet SDK is honored these days.

**Comment by cartermp** [comment]
> the problem is really related to FCT and VS not caring about this use case.

There's no way to know that, as I've not been able to remove FCT from Paket to confirm that FCT is the culprit here. If it is, then this issue should be closed, but at this point it's just a guess. FCT has historically made the IDE tooling not really work well (or at all) so I think it's likely, but not confirmed.

> seems I'm alone with that opinion and only happy case and dotnet SDK is honored these days.

This is not true.

**Comment by forki** [comment]
well I confirmed it indirectly. In the very tedious process to move to new SDK I managed to have an intermediate step where the project compiles. The false positives are gone.

**Comment by cartermp** [comment]
Thanks
