### ISSUE TITLE
Compiler error when passing named parameters to attributes

### ISSUE THREAD

**Issue by eiriktsarpalis** [Microsoft/visualfsharp#681]
Consider the following attribute definition:

``` fsharp
type FooAttribute(value : int) =
    inherit System.Attribute()
    new () = new FooAttribute(-1)
```

I can easily create instances of the attribute like so:

``` fsharp
let attr = new FooAttribute(value = 42)
```

However when adding the same attribute to a type definition:

``` fsharp
[<FooAttribute(value = 42)>]
type Bar = class end
```

The following compile error occurs:

```
error FS0041: A unique overload for method 'FooAttribute' could not be determined based on type information prior to this program point. A type annotation may be needed. Candidates: new : unit -> FooAttribute, new : value:int -> FooAttribute
```

The error goes away when removing the parameter name from the attribute:

``` fsharp
[<FooAttribute(42)>]
type Bar = class end
```

**Comment by panesofglass** [comment]
I thought named parameters to attributes were always property names. Is that not the case?

**Comment by rojepp** [comment]
In admittedly rare situations, this could improve readability a lot.
@panesofglass No, they are parameter names. Like in C#:

```csharp
MyMethod(1,2 myOptionalParam: 3) 
{
   MyProperty = 4
}
```

**Comment by PatrickMcDonald** [comment]
In C#, named arguments to attributes are named properties (See https://msdn.microsoft.com/en-us/library/bfz783fz(v=vs.110).aspx)

> Positional parameters are required and must come before any named parameters; they correspond to the parameters of one of the attribute's constructors. Named parameters are optional and correspond to read/write properties of the attribute.

This seems to be the same in F#, as the following code compiles:

```
type FooAttribute () =
    inherit System.Attribute()
    member val Value = -1 with get, set

[<FooAttribute(Value = 42)>]
type Bar() = class end
```

**Comment by 0x53A** [comment]
In C# Attributes, named parameters are denoted with a `param: value`, where as properties are specified with `Property=Value`.  

e.g.: 

    public class TestAttribute : Attribute
    {
        public string Prop { get; set; }
        public TestAttribute(int arg) { }
    }


    [Test(arg: 1, Prop = "2")]^


For F#, I read the MSDN spec as defining that named parameters always refer to properties, whereas positional parameters are ctor parameters:
https://msdn.microsoft.com/en-us/library/dd233179.aspx

e.g.:

    [<Test(1, Prop="2")>

This is in contrast to methods, where the `=` specifies either a named parameter OR a property initialization.

**Comment by kurtschelfthout** [comment]
This seems to be caused by this line:
https://github.com/Microsoft/visualfsharp/blob/f08fcd4245256166781e658ef3c53552147ec9c6/src/fsharp/MethodCalls.fs#L297

Which does something special for attributes. Note the comment:

```
// the assignment of names to properties is substantially for attribute specifications 
// permits bindings of names to non-mutable fields and properties, so we do that using the old 
// reliable code for this later on. 
```
I don't understand that comment to begin with - "permits bindings to non-mutable fields and properties"? Surely that isn't the case.

Anyway, unfortunately, in this case, the "old reliable code" is not even triggered, because since the `unassignedNamedItem` remains erroneously empty, the empty constructor is not filtered out in `ResolveOverloading` here:  https://github.com/Microsoft/visualfsharp/blob/08c6ebcf9fe1de06054793e4e4aa102a695be566/src/fsharp/ConstraintSolver.fs#L2125

`IsCandidate` tries to figure out if a caller assigns all named arguments for the candidate; since in the attribute case this is empty, neither candidates can be filtered and the code causes a compiler error a bit further down.

In the normal constructor call, the default ctor of `FooAttribute` gets filtered out and code proceeds as normally.

So I guess my question is - do we still need the "old reliable code"? I'm not sure if there is still any difference, and if so what it would be.

**Comment by dsyme** [comment]
@kurtschelfthout Apologies I didn't answer when you wrote your comment above.  You were exactly right - the code there needed to be adjusted, and I fixed the garbled comment

See https://github.com/Microsoft/visualfsharp/pull/3251

Thanks!

**Comment by kurtschelfthout** [comment]
No worries, thanks for fixing!
