### ISSUE TITLE
Async.StartWithContinuations not tail calling, possible trampoline bug?

### ISSUE THREAD

**Issue by eiriktsarpalis** [Microsoft/visualfsharp#686]
Consider the following snippet:

``` fsharp
let foo x = Async.FromContinuations(fun (s,e,c) -> Async.StartWithContinuations(x,s,e,c))

let rec test n = async {
    if n = 0 then return ()
    else
        return! foo <| test (n-1)
}

Async.RunSynchronously (test 1000000) // stack overflow
```

I would expect the above piece of code to function without incident, however the process dies with a stack overflow. It looks like Async.StartWithContinuation is not making tail calls properly, and at the same time the Trampoline mechanism seems to fail in offloading the stack.

**Comment by eulerfx** [comment]
The following works fine. 

```fsharp
let foo x = 
  Async.FromContinuations(fun (s,e,c) -> 
    let x = async { 
      do! Async.SwitchToThreadPool ()
      return! x 
    }
    Async.StartWithContinuations (x,s,e,c))

let rec test n = async {
    if n = 0 then return ()
    else
        return! foo <| test (n-1)
}

Async.RunSynchronously (test 1000000)
```

The stackoverflow seems consistent with the behavior of the trampoline [here](https://github.com/fsharp/fsharp/blob/master/src/fsharp/FSharp.Core/control.fs#L429)

**Comment by eiriktsarpalis** [comment]
@eulerfx The problem with `SwitchToThreadPool` is that it *always* enqueues the current continuation to the threadpool, which I assume might create latency issues. Regardless of how `Async.FromContinuations` behaves, I think that something goes wrong with the trampoline bind count in the current thread; it should have reached that 300 bind limit way before a stack overflow happened by virtue of all the bindings that compose with `foo`.

**Comment by radekm** [comment]
IMO it should be expected:

1) I don't think that `Async.StartWithContinuations` can be protected by trampoline. The reason is that some help from its caller would be needed. But usually callers of `Async.StartWithContinuations` don't know anything about trampolines. IMO this holds for all public functions from `Async` module which don't return `Async`.

2) `Async.FromContinuations` cannot protect given function from stack overflow. To do so some help from the given function would be needed (eg. the given function should interrupt itself and store current continuation somewhere when running low on stack space).

**Comment by eiriktsarpalis** [comment]
I think that the problem boils down to the fact that `Async.StartWithContinuations` creates a fresh TrampolineHolder instance and this seems to be resetting the bind count every time it is called. In MBrace (which is a continuation library very similar to async) we solve this problem by assigning a unique bind counter to each thread. So the equivalent code does not fail:
```fsharp
#r "MBrace.Core.dll"
open MBrace.Core
open MBrace.Core.Internals

let foo x = Cloud.FromContinuations(fun e c -> Cloud.StartImmediateWithContinuations(x,c,e))

let rec test n = cloud {
    if n = 0 then return ()
    else
        return! foo <| test (n-1)
}

Cloud.RunSynchronously (test 1000000) // stack overflow
```

**Comment by radekm** [comment]
@eiriktsarpalis Interesting. If I understand approach of MBrace correctly it executes `fun e c -> Cloud.StartImmediateWithContinuations(x,c,e)` in a new thread whenever `bindCount` reaches 300? And since 300 (or less) calls to `fun e c -> Cloud.StartImmediateWithContinuations(x,c,e)` terminate quickly the number of `ThreadPool` threads is low.

Clever, I was not considering using more threads.

BTW why not base `Async` implementation on MBrace?

**Comment by eiriktsarpalis** [comment]
@radekm Correct. Async does more or less the same, but `Async.StartWithContinuations` seems to be somehow resetting the trampoline state. At the same time, the logic of the Async trampoline implementation seems strangely convoluted to me, I'm not sure if it serves a purpose I do not grasp or if it's simply a historical artifact. 

In MBrace the trampoline is much more simplistic: https://github.com/mbraceproject/MBrace.Core/blob/master/src/MBrace.Core/Utils/Trampoline.fs#L18
As you can see the bind counter is global to current thread, so if `Cloud.StartImmediateWithContinuations` is being called deep in the stack, this information will be passed on to nested workflows for timely offloading.

**Comment by dsyme** [comment]
Closing this old discussion
