### ISSUE TITLE
Improving VS Tooling 

### ISSUE THREAD

**Issue by cloudRoutine** [Microsoft/visualfsharp#730]
@KevinRansom  At the standup on monday you talked about some VB code that needed to be upgraded to F#, were you refering to [FSharp.Project]
https://github.com/Microsoft/visualfsharp/tree/master/vsintegration/src/vs/FsPkgs/FSharp.Project/VB/FSharpPropPage)

@enricosada You mentioned improving the REPL window, was it based on the code in [VisualStudio-SharedProject](https://github.com/Microsoft/VisualStudio-SharedProject/tree/master/Product/ReplWindow) or something else?

Are there other areas that need improvement that have been stuck on the backlog?

**Comment by enricosada** [comment]
@cloudRoutine that's the only vb code (property pages), some xaml+fs will be awesome (high dpi and easier to maintain). If we remove the VB proj, we can merge two c# proj inside the solution, used only because it was needed as reference (less code).

about the repl, it's the [ReplWindow](https://github.com/Microsoft/VisualStudio-SharedProject/tree/master/Product/ReplWindow), just install python extension or nodejs, you'll see the improvemenent (coloring, autocomplete, tooltip). I know fsharpi need to change, but at least the vs ui is done.
 
i think it's the same code as roslyn repl windows for vs < 2015, with 2015 they reference the one in roslyn assembly directly.

i added #496 and a pr to add the sharedproj as submodule ( #733 ), so we can cleanup easier (without duplicate the code)

**Comment by dsyme** [comment]
Closing old discussion
