### ISSUE TITLE
No FSharp.Data.TypeProviders in extensions list in a fresh VS 2015 (Update 1) installation

### ISSUE THREAD

**Issue by vasily-kirichenko** [Microsoft/visualfsharp#749]
It was referenced in VS 2013, F# 3.1.2 as 

``` xml
<Reference Include="FSharp.Data.TypeProviders, Version=4.3.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" />
```

Now it's missing:

![image](https://cloud.githubusercontent.com/assets/873919/11496820/bd6ee166-9825-11e5-92a9-88d07d44f03b.png)

Should it be installed separately (via NuGet?)?

**Comment by xenocons** [comment]
I have had the exact same troubles since Update 1, I went from a working Update 1 RC to a broken Update 1.

**Comment by dsyme** [comment]
(changed the title as I don't think it's about the GAC)

That list is populated by the presence of ``AssemblyFolderEx`` registry keys.  Specifically

- ``FSharp.Data.TypeProviders.dll`` should be at the path  ``c:\Program Files (x86)\Reference Assemblies\Microsoft\FSharp\.NETFramework\v4.0\4.3.0.0\Type Providers``.  Please check if it is or not

- The registry key ``HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Microsoft\.NETFramework\v4.0.30319\AssemblyFoldersEx\F# 4.0 Type Providers``  should be present with value ``C:\Program Files (x86)\Reference Assemblies\Microsoft\FSharp\.NETFramework\v4.0\4.3.0.0\Type Providers\``

My guess

- If both of those are present after an update, then it seems some other change in Visual Studio Update 1 is to blame.

- If the registry key is missing (please check), and a repair of the Visual F# Tools fixes things, then there is some installation interference, possibly related to a .NET update

- If the registry key is missing (please check), but the DLL is present, and a repair of the Visual F# Tools does not fix things, then some change in the Visual F# Tools installer is to blame.  You should be able to workaround by adding the registry key or browsing to the above folder.

- If both the registry key is missing and the DLL is missing, then there's been some more serious change in behaviour for the Visual F# Tools installer.

Please let us know which of the above apply on your system, and send system details.

**Comment by xenocons** [comment]
@dsyme to answer your bullet points inline:
```
C:\Program Files (x86)\Reference Assemblies\Microsoft\FSharp\.NETFramework\v4.0\4.3.0.0\Type Providers>dir
 Directory of C:\Program Files (x86)\Reference Assemblies\Microsoft\FSharp\.NETFramework\v4.0\4.3.0.0\Type Providers

12/01/2015  09:06 AM    <DIR>          .
12/01/2015  09:06 AM    <DIR>          ..
04/14/2015  03:24 PM           462,688 sqlceca40.dll
04/14/2015  03:24 PM           104,288 sqlcecompact40.dll
04/14/2015  03:24 PM           154,464 sqlceer40EN.dll
04/14/2015  03:24 PM            80,736 sqlceme40.dll
04/14/2015  03:24 PM           908,128 sqlceqp40.dll
04/14/2015  03:24 PM           128,000 SqlCeScripting40.dll
04/14/2015  03:24 PM           543,072 sqlcese40.dll
04/14/2015  03:24 PM           465,248 System.Data.SqlServerCe.dll
04/14/2015  03:24 PM           239,968 System.Data.SqlServerCe.Entity.dll
               9 File(s)      3,086,592 bytes
```

The registry key you mentioned definetly points to the same file path as the one pasted above.

However, I installed F# 3.0 over the top of VS2015 Update1, and the problem is solved.

**Comment by pottereric** [comment]
@xenocons How did you install F#?

**Comment by xenocons** [comment]
@pottereric i used http://download.microsoft.com/download/0/5/E/05E5C5E3-2A52-434F-A09E-C8150B987D09/VWD_FSharp.exe

**Comment by dsyme** [comment]
@KevinRansom reports this as no repro when we do a clean install on our VMs in #753.  It would be great to get to the bottom of this.

**Comment by pottereric** [comment]
I had a clean install of Windows 10 and Visual Studio 2015 shortly after VS2015 came out. I've been using it for my daily work ever since. Unfortunately, this makes it hard to know what changes I've made to the state of the machine. I was experianceing Issue #637 on this machine. I installed Update 1 on top of my VS2015 install. Now when I try to add a revernce to the TypeProviders dll, it doesn't appear. 

![typeprovidersissue](https://cloud.githubusercontent.com/assets/1797047/11562434/ee4247a2-999b-11e5-9c19-10a6cd2ea0d1.png)
 
Under HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Microsoft\.NETFramework\v4.0.30319\AssemblyFoldersEx\F# 4.0 Type Providers, the value is "C:\Program Files (x86)\Reference Assemblies\Microsoft\FSharp\.NETFramework\v4.0\4.3.0.0\Type Providers\"

But the folder doesn't exist. This is what I have in C:\Program Files (x86)\Reference Assemblies\Microsoft\FSharp\.NETFramework\v4.0\4.3.0.0.

![notypeprovidersfolder](https://cloud.githubusercontent.com/assets/1797047/11562626/1bd2d0c8-999d-11e5-809f-b11ae0cf8d38.png)

**Comment by eriawan** [comment]
@pottereric, @vasily-kirichenko,

cc @dsyme 

I have clean install of Visual Studio 2015 Update 1 and the folder and the file is there

![vs2015update1_fstypeprovidersfolder](https://cloud.githubusercontent.com/assets/8773147/11572285/f8da42cc-9a32-11e5-8020-e5f029e8eb28.png)

As Don said, the folder and the file is there.

Now on adding references:

![vs2015update1_references](https://cloud.githubusercontent.com/assets/8773147/11572463/04977480-9a34-11e5-995f-47f9f0497585.png)

The reference to F# Type Provider is there.

To all:
I have tested this: I target my project to use .NET 4.6 to really match Vasily's screen capture (he targeted .NET 4.6).
I have captured again and here it is:

![vs2015_update1_fsharp_net46](https://cloud.githubusercontent.com/assets/8773147/11572652/ec180ff4-9a34-11e5-8d3d-059bd6c1f53d.png)

The type provider is still available.

**Comment by xenocons** [comment]
@eriawan you are targeting 4.6.0 in your screenshot, @vasily-kirichenko is targetting 4.6.1?

**Comment by vasily-kirichenko** [comment]
@eriawan did you install VS 2015 on a just installed Windows? No VS 2013 installed or used to be installed on it?

**Comment by eriawan** [comment]
@xenocons You are right, I was reading 4.6 instead of 4.6.1. My mistake :blush: 
Thanks for reminding me :+1: 
Still, if I target to 4.6.1, the type provider is still available:

![vs2015_update1_fsharp_net461](https://cloud.githubusercontent.com/assets/8773147/11583576/fc06ab6a-9a8d-11e5-9fc9-f070ad42689d.png)

The type provider is still available.

**Comment by eriawan** [comment]
@vasily-kirichenko 
Here's the condition of my machine: (and the order of installations)
1. Windows 10 build 1511
2. Visual Studio 2013 Update 5
3. Visual Studio 2015 Update 1

So basically I install Visual Studio 2015 Update 1 after I install Visual Studio 2013 Update 5. 
As far as I know and I have experienced myself, installing VS 2013 after installing VS 2015 always brings bad experiences, and I have to repair VS 2015 installation after installing VS 2013.

**Comment by vasily-kirichenko** [comment]
@eriawan If you have (or had) VS 2013 installed, then there's no problem with the TP assembly.

My scenario is:
* install win 10
* install VS 2015
* no FSharp.Data.TypeProviders assembly in GAC

**Comment by eriawan** [comment]
@vasily-kirichenko 
I have another machine with this condition:
1. Win 10 build 1511
2. Visual Studio 2015 Update 1

And the FSharp.Data.TypeProviders assembly is still available from the Reference Manager.

**Comment by vasily-kirichenko** [comment]
Hm. My actual scenario is a bit different:
* install win 10
* install VS 2015
* install VS 2015 Update 1 RC
* install VS 2015 Update 1

**Comment by xenocons** [comment]
@vasily-kirichenko this is my exact same scenario.

**Comment by vasily-kirichenko** [comment]
Aha. So we can close it if anyone tell us how we can get our installations work now.

**Comment by eriawan** [comment]
@vasily-kirichenko I think your scenario is different from me. I agree.

As for having installing VS 2015 Update 1 RC, this is my suggestion for your installation issue. I suggest to read email John Montgomery's on the Visual F# insiders mailing list dated on 1st December. I believe you got his email too.

I quoted his message:

> If you’ve installed one of these recent pre-release builds (24709, 24711, 24713), then please follow these instructions to fully upgrade all of your installed features to the final RTW versions:
> Download and Run: Visual Studio 2015 Update 1

Actually I haven't tried it myself (because I never install VS 2015 Update 1 RC), but some of my friends have installed Update 1 RC and they solve some installations and different reference problems by running the cleanup script and then install the VS 2015 Update 1 RTW (final release of VS 2015 Update 1).

I have looked at the script, and it says that it fixes some installation issues of VS 2015 RC 1 installations, including failing to uninstall when installing VS 2015 Update 1 on VS 2015 Update 1 RC. So the script has to be ran *before* installing VS 2015 Update 1 RTW.

I hope this helps your installation issue.

**Comment by joaomello** [comment]
I have same cenario of @vasily-kirichenko , and not wotking

**Comment by dsyme** [comment]
So has anyone tried the steps linked above? https://github.com/Microsoft/visualfsharp/issues/749#issuecomment-161902755

Equally, can anyone confirm that a repair of the Visual F# Tools doesn't work? 

Finally, people reported that installing the Visual F# Tools 3.1.2 into Visual Studio 2013 (if you have it) fixed the problem.  Could anyone confirm that?

**Comment by pottereric** [comment]
@dsyme, When you mention running a repair of the Visual F# Tools, are you talking about running the installer for Visual Studio 2015 Update 1, or is there a stand alone install?

**Comment by eriawan** [comment]
Has everybody tried the script that I mentioned above?

cc @vasily-kirichenko

**Comment by joaomello** [comment]
I'm not in insiders, how can I get the script?

**Comment by joaomello** [comment]
I installed the from @xenocons, but now Iam getting this error:

    Severity	Code	Description	Project	File	Line	Suppression State
    Error		The type provider 'Microsoft.FSharp.Data.TypeProviders.DesignTime.DataProviders'     reported an error: The .NET SDK 4.0 or 4.5 tools could not be found

**Comment by vasily-kirichenko** [comment]
@joaomello I saw the same error when Update 1 RC was installed.

**Comment by eriawan** [comment]
@joaomello what kind of link from @xenocons ? which link?

**Comment by joaomello** [comment]
this http://download.microsoft.com/download/0/5/E/05E5C5E3-2A52-434F-A09E-C8150B987D09/VWD_FSharp.exe

**Comment by s952163** [comment]
This has happened to me on one  PC as well on Windows 7, VS2015 Community + Update 1. Installing VS2015 Update 1 will break Immutable Collections and TypeProviders. On another PC (win10 + VS2015 + UPdate1) the TypeProvider stayed. As I cannot tell if the TypeProvider was removed by Update 1 or some other program sweeping for unknown dlls I just copied it from another PC.

The easiest fix is to copy the TypeProviders folder with the dll into the GAC.

**Comment by pottereric** [comment]
Running the VWD_FSharp.exe script referenced by @joaomello resolved the issue for me.

**Comment by eriawan** [comment]
@joaomello ok, got it. Good to know if it works for you :+1: 

@pottereric That link is an installer for Visual Web Developer's F# tool, not a script, IMHO. 
All, good to know if installing the tool fix the issue.

**Comment by joaomello** [comment]
@eriawan after installing I can find the assemblies to add, but on compile recive this error https://github.com/Microsoft/visualfsharp/issues/749#issuecomment-162368762

**Comment by fjoppe** [comment]
I have the same problem on my Work's laptop. I had a clean install to Windows 10, clean install from VS2015 Enterprise, installed Update 1 last week. 

I tried several times the VWD_FSharp.exe link mentioned above.

This is the error I get in the fsi:
[..] error FS3033: The type provider 'Microsoft.FSharp.Data.TypeProviders.DesignTime.DataProviders' reported an error: The .NET SDK 4.0 or 4.5 tools could not be found

If I build a project using the WsdlProvider then I get the same error.

I also installed a Windows SDK last week, added a couple of registry keys. 

This folder has no subfolder "TypeProviders": c:\Program Files (x86)\Reference Assemblies\Microsoft\FSharp\.NETFramework\v4.0\4.3.0.0\

I also check other Fsharp versions, same story. 

I also installed "Fsharp.Data.TypeProviders 0.0.1" via the nuget packet manager and linked the dll in the fsi.

No luck until now. So I am a bit stuck..

**Comment by s952163** [comment]
1. Install the windows 8 SDK https://msdn.microsoft.com/en-us/windows/desktop/hh852363.aspx (or possibly windows 8.1) that should fix the registry keys for .NET
2. After that just create the folder manually and put the TypeProvider dll inside it. If you have built something before it will be in the bin folder under the project. Or copy from another PC (with a stock VS2013 or VS2015) install.

**Comment by s952163** [comment]
Here's the typeprovider itself
https://dl.dropboxusercontent.com/u/10709237/Type%20Providers.zip

**Comment by matteot31415** [comment]
I am running into a similar issue - and I think this started when Update 1 started being installed with VS2015 (it is the default), i.e. I do not recall seeing this when I was installing CTPs/RCs Update1 on top of RTM VS2015.

*My simple repro:*
* On a clean machine running Win10 x86
* Install VS2015 Enterprise:
   * In the custom options, select just: FSharp and Visual Studio Update 1
   * Leave the installation path to its default value

*Observed result:*
* In the early stages of setup, _C:\Program Files\Reference Assemblies\Microsoft\FSharp\.NETFramework\v4.0\4.3.0.0\Type Providers_ is there
* When the _Visual Studio Update 1_ part of setup kicks in, the same folder is removed

You can see all that in the following picture:
![picture001](https://cloud.githubusercontent.com/assets/12504075/11765851/4ceba570-a11f-11e5-807f-7b61d9a2942b.png)

Repairing Visual Studio 2015 seems to bring back the _Type Providers_ folder, so at least there seems to be a workaround.

I've given @KevinRansom access to my machine so he can have a look at all the setup logs generated by VS.

**Comment by xperiandri** [comment]
@vasily-kirichenko, 2015 Update 1 RC was extremely buggy. I don't remember so many issues with RC before.
Only complete uninstallation of RC, folders cleanup and installation of RTM fixed issues.

**Comment by eriawan** [comment]
@xperiandri, agree.

The VS 2015 Update 1 RC has many problems.

@vasily-kirichenko and others,
For those who want to try the script from John Montgomery, here's the script from John Montgomery on my GitHub Gist:

https://gist.github.com/eriawan/7fb431913cd3f15cd898

This is my own experience based on the Vasily's scenario.
I have tried to install VS 2015 on a VM and then do these installations:
* VS 2015 Update 1 RC
I checked the type provider availability, and it was missing!

After that, I do these:
* run the script
* VS 2015 Update 1 
Fortunately I can fix the issue of the missing Type Provider using the steps above. As far as I have tested, this was caused by faulty installation of VS 2015 Update 1 RC. This DLL is somehow missing at the time of VS 2015 Update 1 RC installation.

After I have tried to run script as Administrator, then re-install VS 2015 Update 1, the missing type provider is available again.

**Comment by fjoppe** [comment]
About a week later... 

Thanks @s952163 for the info above, this worked for me:
"Install the windows 8 SDK https://msdn.microsoft.com/en-us/windows/desktop/hh852363.aspx (or possibly windows 8.1) that should fix the registry keys for .NET"

Last week I installed the SDK for 8.1 and that did not work. I did not install the type provider seperately.

**Comment by vasily-kirichenko** [comment]
Closing this old VS 2015 issue.
