### ISSUE TITLE
No debugger tooltips, close to no Locals

### ISSUE THREAD

**Issue by vasily-kirichenko** [Microsoft/visualfsharp#782]
Scenario: debug a test from VFPT solution (built in Debug configuration):

![1](https://cloud.githubusercontent.com/assets/873919/11709486/17599f4a-9f29-11e5-871f-404a3b4673a9.gif)

**Comment by forki** [comment]
Same here. If you are inside async you basically end up without debugger support. I always thought I did something wrong and felt back to printf debugging.

**Comment by dsyme** [comment]
I'm trying to work out what specifically is the bug here. What I observe from the above: 

* You don't get any quick info hover tips about types.  That's expected though could be changed.  I don't think there's been a change here has there?

* In all the cases of hover in the above screencast, I think the variable is either not captured by the async closure or the variable has not yet been defined.  So no value is expected (though better feedback like ``value not available`` or ``value not yet computed`` would be better).  Hovering over ``view`` looks like it should give a result.

I tried the program below, setting breakpoints on ``return`` and both  ``let!``.  The debugging experience seemed oK to me - the ``x`` and ``y`` values showed value tips (expected), breakpointing worked correctly (good).   

    let g (x:int, y: int) = 
        async { return (x+y) }

    let f (x:int, y: int) = 
        async { 
            let! z1 = g(x,y) 
            let! z2 = g(x,y) 
            return z1 + z2 
        }

    [<EntryPoint>]
    let main argv = 
        let t1 = f (3,4) |> Async.StartAsTask
        let t2 = f (3,4) |> Async.StartAsTask
        let t3 = f (3,4) |> Async.StartAsTask
        t1.Result + t2.Result + t3.Result

Thanks
Don

**Comment by dsyme** [comment]
Note that it's a design decision that Debug code only makes locals for the values that are actually captured by the `async`.  We could consider an option to capture all expression-locals, though people would be unlikely to turn it on. Always capturing all expression-locals would lead to space leaks in debug code - though arguably might still be the right tradeoff.

**Comment by dsyme** [comment]
Closing this - see the analysis above - short of closing over all locals in debug code (which would be expensive) I'm not sure there's a specific bug here?
