### ISSUE TITLE
Debugger does not respect DebuggerStepThrough attribute

### ISSUE THREAD

**Issue by vasily-kirichenko** [Microsoft/visualfsharp#783]
![1](https://cloud.githubusercontent.com/assets/873919/11709792/79a2e1aa-9f2b-11e5-96ec-5f4fc1cfefde.gif)

**Comment by dsyme** [comment]
As I understand it this is by design.

The DebuggerStepThrough attribute applies to the method, not the body of the async expression that the method returns.  Don't forget that the ``async { ... }`` implies an ``async.Delay(fun () -> ...)`` around the body of the code.  

The same kind of problem will apply to a lot of expression-based control constructs, for example a method that returns a lambda expression. There is no way to apply the DebuggerStepThrough attribute through all lambda constructs in a method.

**Comment by dsyme** [comment]
Closing as by-design

However there may be a suggestion for a language change here, to apply the DebuggerStepThrough attribute through all lambda constructs in a method. There are pros and cons to that.  It's an interesting (and quite challenging) problem.
