### ISSUE TITLE
Presence of overload causes overload resolution to fail

### ISSUE THREAD

**Issue by JeffreySax** [Microsoft/visualfsharp#801]
When a method has an overload with the same number of parameters, some otherwise valid expressions may no longer be inferred correctly and overload resolution may fail.

In the code below, we have two methods: `count1` and `count2`. Both methods have an overload that takes a single `IList<Base>` argument. When calling this method with arrays containing various mixtures of instances of base and derived types, overload resolution succeeds always for `count1` but only in 1 out of 4 cases for `count2`.

The presence of an overload with the same number of parameters seems to be the trigger for the failure. Adding additional parameters to all overloads gives identical results.

    type Base(x : int) =
        member self.X = x
        static member count1(x : System.Collections.Generic.IList<Base>) = 0
        static member count1() = 0
        static member count1(x : int, y : int) = 0
        static member count2(x : System.Collections.Generic.IList<Base>) = 0
        static member count2(x : int) = 0 
    type Derived(x : int) = inherit Base(x)
    let a = Base(1)
    let b = Derived(1)

    let c1 = Base.count1([| a; a |]) // OK
    let c2 = Base.count1([| a; b |]) // OK
    let c3 = Base.count1([| b; a |]) // OK
    let c4 = Base.count1([| b; b |]) // OK

    let d1 = Base.count2([| a; a |]) // OK
    let d2 = Base.count2([| a; b |]) // b expected to have type Base
    let d3 = Base.count2([| b; a |]) // No overloads match
    let d4 = Base.count2([| b; b |]) // No overloads match

**Comment by abelbraaksma** [comment]
I can confirm this behavior for VS2015, F# 4.0.

* remove the last `count2` and it behaves normally
* add an extra param to the last `count2` and it behaves normally
* change the last `count2` to `count2()` and it behaves normally
* the same behavior can be observed when you change the `IList<Base>` type to `seq<Base>`
* a slightly different behavior can be observed when you change it to `seq<_>` (you cannot mix the types then, i.e. `[|a; b |]` and `[|b; a\]` then both fail, but that's perhaps by design/expected)
* another behavior can be observed with `static member count2<'a when 'a :> Base>(_ : seq<'a>)`, which I would take as an alternative syntax for the OP. Incidentally, it succeeds more lines, but it fails for the same reasons as the previous point. It accepts `Derived` and it accepts `Base`, but no mix. Again, I'm not sure if this is a co/contra variance restriction or part of this bug.

**Comment by dsyme** [comment]
This is by design. It happens when you combine the use of arrays of elements of different types with overload resolution.

F# has a rule where an array literal ``[| ... |]`` can have elements of different types when the array type is "known" before the array literal is checked.  The array type becomes known to type inference through the rules in the F# language spec.  One way that types become known is through the use of method overloads eagerly resolved according to the number of arguments. This means that adding new overloads can affect the set of known types.

F# uses rules like this (where known types permit further coercions when processing literals) very sparingly - array/list literals are one of the only such places.

A common workaround is to cast the elements of the array in the array literal ``[| (a :> A); (b :> A) |]``
