### ISSUE TITLE
C#-style provided extension members on non-statically-parameterized types

### ISSUE THREAD

**Issue by dmitry-a-morozov** [Microsoft/visualfsharp#826]
Resurrecting 
https://visualfsharp.codeplex.com/SourceControl/network/forks/dsyme/cleanup/contribution/7773
https://visualfsharp.codeplex.com/SourceControl/network/forks/dsyme/cleanup/contribution/7780

Also, it would be nice to have statically parameterized provided extension members for erased types.

**Comment by dsyme** [comment]
Hi @dmitry-a-Morozov, 

The end conclusion from those PRs was "not to be implemented".  I couldn't see a way to make the feature work

I suppose we should circle back and take the feature through fslang.uservoice.com - e.g. write up a speclet and link it there if you think there's a sensible spec to be found.

I'll close this, since per CONTRIBUTING.md an issue here should be either a bug report, discussion etc.  (though not language design discussions).

thanks
don
