### ISSUE TITLE
Cannot restore latest Microsoft.FSharp.Core.netcore package

### ISSUE THREAD

**Issue by enricosada** [Microsoft/visualfsharp#832]
using a sample project.json and latest compiler nuget  ( `Microsoft.FSharp.Compiler.netcore` ). 

- v1.0.0-alpha-151**221** fails
- v1.0.0-alpha-151**218** is ok.

```
System.ArgumentException: More than one runtime.json file has declared imports for 'win7-x86'
Parameter name: runtimeName
```

from standard dotnet cli ( this create a c# project, but that's ok )
 
```
dotnet new
#add compiler nuget to project json
dotnet restore
```

my `project.json`

```json
{
    "version": "1.0.0-*",
    "compilationOptions": {
        "emitEntryPoint": true
    },

    "dependencies": {
        "NETStandard.Library": "1.0.0-rc2-23616",

        "Microsoft.FSharp.Compiler.netcore": "1.0.0-alpha-151221"
    },

    "frameworks": {
        "dnxcore50": { }
    }
}
```

i think the error is case sensitivity of nuget package names, ref dotnet/cli#236

**Comment by enricosada** [comment]
same error with 

```
        "Microsoft.FSharp.Core.netcore": "1.0.0-alpha-151221"
```

it's FSharp.Core + `"NETStandard.Library": "1.0.0-rc2-23616"` the problem

i'll try a diff on project.json.lock files

**Comment by enricosada** [comment]
@KevinRansom i tried to check deps

the only strange thing i found is:

- runtime.any.System.Linq.Expressions

**Comment by enricosada** [comment]
minimal repro i can do ( `NETStandard.Library` is `NETStandard.Platform` + others packages  )

```
    "dependencies": {
        "NETStandard.Platform": "1.0.0-rc2-23616",

        "Microsoft.FSharp.Core.netcore": "1.0.0-alpha-151221"
    },
```

**Comment by KevinRansom** [comment]
I will take a look.

**Comment by iainnicol** [comment]
Some printf debugging in dnu's RestoreCommand tells me the clash is between
`~/.dnx/packages/Microsoft.NETCore.Platforms/1.0.1-rc2-23616/runtime.json` and
`~/.dnx/packages/Microsoft.NETCore.Platforms/1.0.0/runtime.json`

So maybe we can work around the clash by updating `FSharp.Core/project.json` (and other project.jsons) to use v`1.0.1-rc2-23616` of `Microsoft.NetCore.Platforms.

I won't try to create a patch with that change, because my CLA hasn't yet been verified.  And (and this isn't a complaint) with this being the holidays, there might be a delay in that happening.

**Comment by enricosada** [comment]
i'll try, thx a lot @iainnicol

**Comment by jeremymeng** [comment]
May be related to https://github.com/dotnet/cli/issues/236. I was able to workaround it by specifying the package name with correct case: `"Microsoft.NETCore.Platforms": "1.0.0-rc2-*",`

**Comment by KevinRansom** [comment]
Resolved

**Comment by dsyme** [comment]
Closing, this is old
