### ISSUE TITLE
Do we really need to continue with F#'s support for .net Framework 2.0 support.

### ISSUE THREAD

**Issue by KevinRansom** [Microsoft/visualfsharp#85]
We have a bunch of complexity around maintain .Net CLR 2.0 compatability.  At Microsoft we no longer ship an updated fsharp.core with VS.

What would be the impact to F# and the community if we removed it?

**Comment by latkin** [comment]
To be precise, this is about removing support for building/testing/maintaining the .NET 3.5 version of FSharp.Core.dll, not removing support for users to target .NET 3.5 with their code.

We would just continue shipping v 2.3.0.0, as was done in VS 2012 and 2013.

Current build support is maintained mostly out of the idea that "well, maybe someone somewhere wants to experiement with this".  But it would be nice to toss it all out, since we don't ship new bits here any more.

**Comment by dsyme** [comment]
Yes, I'm OK with no longer building updated versions of FSharp.Core for .NET 2.x, and just continuing to support the use of 2.3.0.0.

**Comment by dsyme** [comment]
Closing this since "net20" is no longer built AFAIK
