### ISSUE TITLE
[<DefaultParameterValue>] is ignored in F#-authored code

### ISSUE THREAD

**Issue by KevinRansom** [Microsoft/visualfsharp#96]
Originally opened at [CodePlex](https://visualfsharp.codeplex.com/workitem/67) [latkin](https://www.codeplex.com/site/users/view/latkin)

Reported by Tomas P via fsbugs. 

The F# compiler ignores the `[<DefaultParameterValue>]` attribute. For example, the following always prints null when called by C# code (calling from F# without specifying message is not supported):

``` fsharp
open System
open System.Runtime.InteropServices
type C = 
  static member Foo([<Optional; DefaultParameterValue("Hello world")>] message) =
         printfn "%s" message
```

Analysis from Don: 

This is correct, in F# 3.0 and F# 3.1 DefaultParameterValue is ignored for F#-authored code, both by F# consumers and .NET consumers of F# code. 

The relevant code is infos.fs GetParamAttribs, where we look for OptionalArgumentAttribute and not DefaultParameterValueAttribute:

``` fsharp
        | FSMeth(g,_,vref,_) -> 
            vref 
            |> ArgInfosOfMember g 
            |> List.mapSquared (fun (ty,argInfo) -> 
                let isParamArrayArg = HasFSharpAttribute g g.attrib_ParamArrayAttribute argInfo.Attribs
                let isOutArg = HasFSharpAttribute g g.attrib_OutAttribute argInfo.Attribs && isByrefTy g ty
                let isOptArg = HasFSharpAttribute g g.attrib_OptionalArgumentAttribute argInfo.Attribs
                // Note: can't specify caller-side default arguments in F#, by design (default is specified on the callee-side) 
                let optArgInfo = if isOptArg then CalleeSide else NotOptional
                (isParamArrayArg,isOutArg,optArgInfo))
```

Likewise in ilxgen.fs, we never generate a “Default” value in the Abstract IL metadata for an F# assembly. There is even a “TODO” marker there...

``` fsharp
       let param = 
            { Name=nmOpt;
              Type= ilArgTy;  
              Default=None; (* REVIEW: support "default" attributes *)   
              Marshal=Marshal; 
              IsIn=inFlag;    
              IsOut=outFlag;  
              IsOptional=optionalFlag; 
              CustomAttrs= mkILCustomAttrs (GenAttrs cenv eenv attribs) }
```

We should fix this.

**Comment by latkin** [comment]
This definitely feels like a bug but changing the behavior would seem to be a pretty serious breaking change, no? Omitted params are uninitialized in one version, given default values in the next.

**Comment by dsyme** [comment]
Whatever we call it, we really should just fix this and make it do the right thing by default.

But it is possible we need a "compat" flag to allow the previous behaviour.

**Comment by dsyme** [comment]
Hi @latkin  - I've been looking at this again - fixing this would only affect F# code that specifies the ``DefaultParameterValue("Hello world")>] `` attribute on parameters - it would cause the correct C#-compatible IL to be emitted for that case.

i don't think anyone is using that attribute on F# parameters today since it doesn't do anything (and it's quite hard to find it!)

So I think fixing this makes sense.

**Comment by latkin** [comment]
I agree it's a narrow slice of users would would be affected. In principle I'm against it since the behavior is dramatically different, but practically speaking we could probably get away with it.

In our changelist file maybe we should keep track of stuff like this that is technically breaking, but deemed to be acceptable.

**Comment by dsyme** [comment]
OK. I suppose my estimate is that there would be no F# code using  DefaultParameterValue today. And any code where it was being used would expect the fixed behaviour.  So yes, acceptable "breaking change in theory".

**Comment by haf-lynx** [comment]
Is this still an issue? Running into it when trying to create C#-friendly libraries over here. :(

**Comment by haf** [comment]
Ping, what's the plan for this issue?

**Comment by kurtschelfthout** [comment]
As atonement for creating the dup I have been looking at this :) 

My goal is to share some code tonight (GMT), so far it looks like I've been able to pass what I think is the right info to the `Default` field Don mentioned above, but that doesn't seem to have any effect on the IL. I think maybe something down the line in the IL generation needs to be added as well but got a bit lost there last night.

**Comment by kurtschelfthout** [comment]
I think we can close this now?

**Comment by dsyme** [comment]
Yes! :)

**Comment by tebjan** [comment]
Hello, why and how is this issue resolved? How do i set the default value attribute correctly so that the resulting IL resembles the C# one? I did several tests and these are my results:

This F# declaration:
```
open System.Runtime.InteropServices
module SomeFSharpVLOperations =
    //setting pin defaults
    let DefaultTest ([<DefaultParameterValue(42)>] input) : int = input
```
Outputs this IL code:
```
public static int DefaultTest([DefaultParameterValue(42)] int input)
{
	return input;
}
```
While a c# declaration:
```
public static int DefaultTest(int input = 42)
{
     return input;
}
```
Gives the expected IL:
```
// DemoLib.SomeStaticVLNodes
public static int DefaultTest(int input = 42)
{
	return input;
}
```
## Being very explicit
When using both _Optional_ and _DefaultParameterValue_ in F#:
```
//setting pin defaults
let DefaultTest ([<Optional; DefaultParameterValue(42)>] input) : int = input
```
This happens:
```
public static int DefaultTest([DefaultParameterValue(42)] int input = default(int))
{
	return input;
}
```
When using the same attributes in c#:
```
public static int DefaultTest([Optional][DefaultParameterValue(42)] int input)
{
    return input;
}
```
It also gives the expected IL:
```
public static int DefaultTest(int input = 42)
{
	return input;
}
```
ILSpy was used to decompile the assemblies and this is my F# project setting in VS 2015:
![image](https://user-images.githubusercontent.com/1094716/28986723-6e490802-7968-11e7-98da-7d2c84c66de7.png)
Do i have to upgrade the F# compiler somehow?

**Comment by cartermp** [comment]
Yes, you will need to use F# 4.1.  You can use the [FSharp.Compiler.Tools](https://www.nuget.org/packages/FSharp.Compiler.Tools/) package in your current projects, or move to Visual Studio 2017.

**Comment by tebjan** [comment]
thanks!

**Comment by levicki** [comment]
@latkin, @dsyme I apologize for a slight off-topic resurrection, but could you please advise where to direct bug report / feature request that default parameters be also supported in C++/CLI compiler?

This C++/CLI code doesn't work correctly when called from C# without parameter (value is 0 instead of 2), and I see no good reason why it wouldn't:
```
public ref class MyClass1
{
 public:
  MyClass1([System::Runtime::InteropServices::Optional]
           [System::Runtime::InteropServices::DefaultParameterValue(2)]
           int myParam1)                                            ↑
  {
    System::Console::WriteLine(myParam1);
  }
};
```

**Comment by dsyme** [comment]
@levicki I don't know I'm afraid, at least I don't know anything more than you'll find with a google search

**Comment by cartermp** [comment]
@levicki your best bet is to use https://developercommunity.visualstudio.com/search?space=8

**Comment by levicki** [comment]
@dsyme, @cartermp Thanks, and sorry again for off-topic.
